package servergo

import (
	"encoding/json"
	"fmt"

	agenttoolemit "github.com/Yacobolo/toolbelt/apigen/emit/agenttool"
	"github.com/Yacobolo/toolbelt/apigen/ir"
)

// emissionPlan is the immutable hand-off between discovery and rendering.
// Discovery derives all optional sections/imports once so render order cannot
// accidentally change feature detection or generated bytes.
type emissionPlan struct {
	packageName         string
	usesTime            bool
	hasStrictOperations bool
	hasRequestBodies    bool
	hasMultipartBodies  bool
	hasFileBodies       bool
	usesFmt             bool
	hasTools            bool
	hasCommands         bool
	toolContractsJSON   string
	specJSON            string
}

func discoverEmissionPlan(doc ir.Document, opts Options) (emissionPlan, error) {
	toolContracts, err := agenttoolemit.Build(doc)
	if err != nil {
		return emissionPlan{}, err
	}
	toolContractsJSON, err := json.Marshal(toolContracts)
	if err != nil {
		return emissionPlan{}, fmt.Errorf("marshal agent tool contracts: %w", err)
	}
	specJSON := opts.EmbeddedOpenAPISpecJSON
	if specJSON == "" {
		specJSON, err = emitSpecJSON(doc)
		if err != nil {
			return emissionPlan{}, err
		}
	}

	plan := emissionPlan{
		packageName: packageName(opts),
		usesTime:    docUsesTimeTypes(doc),
		// The generated registration surface always exposes strict dispatch and
		// its injected error responder, including health-only APIs.
		hasStrictOperations: true,
		hasFileBodies:       docUsesFileBodies(doc),
		hasTools:            len(toolContracts) > 0,
		toolContractsJSON:   string(toolContractsJSON),
		specJSON:            specJSON,
	}
	plan.usesFmt = plan.hasFileBodies
	for _, endpoint := range doc.Endpoints {
		if endpoint.Command != nil {
			plan.hasCommands = true
			plan.usesFmt = true
		}
		if endpoint.OperationID != "getHealth" {
			plan.hasStrictOperations = true
		}
		if endpoint.RequestBody != nil {
			plan.hasRequestBodies = true
			plan.usesFmt = true
			if content, ok := ir.PrimaryRequestBodyContent(endpoint); ok && content.BodyKind == "multipart" {
				plan.hasMultipartBodies = true
			}
		}
		for _, response := range endpoint.Responses {
			if len(responseHeaderFieldsWithDefaults(response)) > 0 {
				plan.usesFmt = true
			}
		}
	}
	return plan, nil
}
