-- Native dashboard authoring query leaves.
-- name: GetDashboard :one
SELECT project_id,dashboard_id,owner_principal_id,slug,title,semantic_model,visibility,status,created_at,updated_at FROM dashboard.authoring_dashboards WHERE project_id=sqlc.arg(project_id) AND dashboard_id=sqlc.arg(dashboard_id);
-- name: LockDashboard :one
SELECT 1::bigint AS locked FROM dashboard.authoring_dashboards WHERE project_id=sqlc.arg(project_id) AND dashboard_id=sqlc.arg(dashboard_id) FOR UPDATE;
-- name: ListDashboards :many
SELECT project_id,dashboard_id,owner_principal_id,slug,title,semantic_model,visibility,status,created_at,updated_at FROM dashboard.authoring_dashboards WHERE project_id=sqlc.arg(project_id) ORDER BY dashboard_id;
-- name: GetDraft :one
SELECT project_id,dashboard_id,draft_id::text,revision_id::text,revision_number,content_hash,provenance_json::text,updated_at FROM dashboard.authoring_drafts WHERE project_id=sqlc.arg(project_id) AND dashboard_id=sqlc.arg(dashboard_id);
-- name: GetPublished :one
SELECT project_id,dashboard_id,revision_id::text,revision_number,content_hash,compiled_revision_id::text,compiled_revision_number,compiled_content_hash,compiled_definition_hash,compiled_semantic_model_id,compiled_semantic_identity_json::text,provenance_json::text,published_at FROM dashboard.authoring_published WHERE project_id=sqlc.arg(project_id) AND dashboard_id=sqlc.arg(dashboard_id);
-- name: GetRevision :one
SELECT project_id,dashboard_id,revision_id::text,revision_number,document_json::text,content_hash,provenance_json::text,created_at FROM dashboard.authoring_revisions WHERE project_id=sqlc.arg(project_id) AND dashboard_id=sqlc.arg(dashboard_id) AND revision_id=sqlc.arg(revision_id)::uuid;
-- name: GetCommand :one
SELECT project_id,dashboard_id,command_id::text,request_fingerprint,action,provenance_json::text,occurred_at,result_revision_id::text,result_revision_number,result_content_hash,created_at FROM dashboard.authoring_commands WHERE project_id=sqlc.arg(project_id) AND dashboard_id=sqlc.arg(dashboard_id) AND command_id=sqlc.arg(command_id)::uuid;
-- name: GetCompilation :one
SELECT project_id,dashboard_id,revision_id::text,revision_number,content_hash,definition_json::text,definition_hash,semantic_model_id,semantic_identity_json::text,compiled_at FROM dashboard.authoring_compiled_revisions WHERE project_id=sqlc.arg(project_id) AND dashboard_id=sqlc.arg(dashboard_id) AND revision_id=sqlc.arg(revision_id)::uuid AND revision_number=sqlc.arg(revision_number) AND content_hash=sqlc.arg(content_hash) AND definition_hash=sqlc.arg(definition_hash) AND semantic_model_id=sqlc.arg(semantic_model_id) AND semantic_identity_json=sqlc.arg(semantic_identity_json)::jsonb;
-- name: CountBySemanticModel :many
SELECT semantic_model, count(*) FILTER (WHERE visibility='private') private_count, count(*) FILTER (WHERE visibility='organization') organization_count, count(*) total_count FROM dashboard.authoring_dashboards WHERE project_id=sqlc.arg(project_id) AND status <> 'archived' GROUP BY semantic_model ORDER BY semantic_model;
-- name: InsertDashboard :exec
INSERT INTO dashboard.authoring_dashboards(project_id,dashboard_id,owner_principal_id,slug,title,semantic_model,visibility,status) VALUES(sqlc.arg(project_id),sqlc.arg(dashboard_id),sqlc.arg(owner_principal_id),sqlc.arg(slug),sqlc.arg(title),sqlc.arg(semantic_model),sqlc.arg(visibility),sqlc.arg(status));
-- name: UpdateDashboard :execrows
UPDATE dashboard.authoring_dashboards SET slug=sqlc.arg(slug),title=sqlc.arg(title),semantic_model=sqlc.arg(semantic_model),visibility=sqlc.arg(visibility),status=sqlc.arg(status),updated_at=clock_timestamp() WHERE project_id=sqlc.arg(project_id) AND dashboard_id=sqlc.arg(dashboard_id);
-- name: ArchiveDashboard :execrows
UPDATE dashboard.authoring_dashboards SET status='archived',updated_at=clock_timestamp() WHERE project_id=sqlc.arg(project_id) AND dashboard_id=sqlc.arg(dashboard_id);
-- name: InsertRevision :exec
INSERT INTO dashboard.authoring_revisions(project_id,dashboard_id,revision_id,revision_number,document_json,content_hash,provenance_json,created_at) VALUES(sqlc.arg(project_id),sqlc.arg(dashboard_id),sqlc.arg(revision_id)::uuid,sqlc.arg(revision_number),sqlc.arg(document_json)::jsonb,sqlc.arg(content_hash),sqlc.arg(provenance_json)::jsonb,sqlc.arg(created_at));
-- name: InsertDraft :exec
INSERT INTO dashboard.authoring_drafts(project_id,dashboard_id,draft_id,revision_id,revision_number,content_hash,provenance_json) VALUES(sqlc.arg(project_id),sqlc.arg(dashboard_id),sqlc.arg(draft_id)::uuid,sqlc.arg(revision_id)::uuid,sqlc.arg(revision_number),sqlc.arg(content_hash),sqlc.arg(provenance_json)::jsonb);
-- name: UpdateDraft :execrows
UPDATE dashboard.authoring_drafts SET revision_id=sqlc.arg(revision_id)::uuid,revision_number=sqlc.arg(revision_number),content_hash=sqlc.arg(content_hash),provenance_json=sqlc.arg(provenance_json)::jsonb,updated_at=clock_timestamp() WHERE project_id=sqlc.arg(project_id) AND dashboard_id=sqlc.arg(dashboard_id) AND revision_id=sqlc.arg(expected_revision_id)::uuid AND revision_number=sqlc.arg(expected_revision_number) AND content_hash=sqlc.arg(expected_content_hash);
-- name: InsertCompilation :exec
INSERT INTO dashboard.authoring_compiled_revisions(project_id,dashboard_id,revision_id,revision_number,content_hash,definition_json,definition_hash,semantic_model_id,semantic_identity_json,compiled_at) VALUES(sqlc.arg(project_id),sqlc.arg(dashboard_id),sqlc.arg(revision_id)::uuid,sqlc.arg(revision_number),sqlc.arg(content_hash),sqlc.arg(definition_json)::jsonb,sqlc.arg(definition_hash),sqlc.arg(semantic_model_id),sqlc.arg(semantic_identity_json)::jsonb,sqlc.arg(compiled_at)) ON CONFLICT DO NOTHING;
-- name: UpsertPublished :exec
INSERT INTO dashboard.authoring_published(project_id,dashboard_id,revision_id,revision_number,content_hash,compiled_revision_id,compiled_revision_number,compiled_content_hash,compiled_definition_hash,compiled_semantic_model_id,compiled_semantic_identity_json,provenance_json,published_at) VALUES(sqlc.arg(project_id),sqlc.arg(dashboard_id),sqlc.arg(revision_id)::uuid,sqlc.arg(revision_number),sqlc.arg(content_hash),sqlc.arg(compiled_revision_id)::uuid,sqlc.arg(compiled_revision_number),sqlc.arg(compiled_content_hash),sqlc.arg(compiled_definition_hash),sqlc.arg(compiled_semantic_model_id),sqlc.arg(compiled_semantic_identity_json)::jsonb,sqlc.arg(provenance_json)::jsonb,sqlc.arg(published_at)) ON CONFLICT(project_id,dashboard_id) DO UPDATE SET revision_id=excluded.revision_id,revision_number=excluded.revision_number,content_hash=excluded.content_hash,compiled_revision_id=excluded.compiled_revision_id,compiled_revision_number=excluded.compiled_revision_number,compiled_content_hash=excluded.compiled_content_hash,compiled_definition_hash=excluded.compiled_definition_hash,compiled_semantic_model_id=excluded.compiled_semantic_model_id,compiled_semantic_identity_json=excluded.compiled_semantic_identity_json,provenance_json=excluded.provenance_json,published_at=excluded.published_at;
-- name: UpdateCompiledPointer :execrows
UPDATE dashboard.authoring_published SET compiled_revision_id=sqlc.arg(compiled_revision_id)::uuid,compiled_revision_number=sqlc.arg(compiled_revision_number),compiled_content_hash=sqlc.arg(compiled_content_hash),compiled_definition_hash=sqlc.arg(compiled_definition_hash),compiled_semantic_model_id=sqlc.arg(compiled_semantic_model_id),compiled_semantic_identity_json=sqlc.arg(compiled_semantic_identity_json)::jsonb WHERE project_id=sqlc.arg(project_id) AND dashboard_id=sqlc.arg(dashboard_id) AND revision_id=sqlc.arg(revision_id)::uuid AND revision_number=sqlc.arg(revision_number) AND content_hash=sqlc.arg(content_hash) AND compiled_revision_id=sqlc.arg(prior_compiled_revision_id)::uuid AND compiled_revision_number=sqlc.arg(prior_compiled_revision_number) AND compiled_content_hash=sqlc.arg(prior_compiled_content_hash) AND compiled_definition_hash=sqlc.arg(prior_compiled_definition_hash) AND compiled_semantic_model_id=sqlc.arg(prior_compiled_semantic_model_id) AND compiled_semantic_identity_json=sqlc.arg(prior_compiled_identity_json)::jsonb;
-- name: InsertCommand :exec
INSERT INTO dashboard.authoring_commands(project_id,dashboard_id,command_id,request_fingerprint,action,provenance_json,occurred_at,result_revision_id,result_revision_number,result_content_hash) VALUES(sqlc.arg(project_id),sqlc.arg(dashboard_id),sqlc.arg(command_id)::uuid,sqlc.arg(request_fingerprint),sqlc.arg(action),sqlc.arg(provenance_json)::jsonb,sqlc.arg(occurred_at),sqlc.arg(result_revision_id)::uuid,sqlc.arg(result_revision_number),sqlc.arg(result_content_hash));
-- name: GetCreateOperation :one
SELECT request_fingerprint,dashboard_id,result_revision_id::text,result_revision_number,result_content_hash FROM dashboard.authoring_create_operations WHERE project_id=sqlc.arg(project_id) AND actor_id=sqlc.arg(actor_id) AND operation_kind=sqlc.arg(operation_kind) AND idempotency_key=sqlc.arg(idempotency_key);
-- name: InsertCreateOperation :execrows
INSERT INTO dashboard.authoring_create_operations(project_id,actor_id,operation_kind,idempotency_key,conversation_id,tool_call_id,request_fingerprint,dashboard_id,result_revision_id,result_revision_number,result_content_hash) VALUES(sqlc.arg(project_id),sqlc.arg(actor_id),sqlc.arg(operation_kind),sqlc.arg(idempotency_key),sqlc.arg(conversation_id),sqlc.arg(tool_call_id),sqlc.arg(request_fingerprint),sqlc.arg(dashboard_id),sqlc.arg(result_revision_id)::uuid,sqlc.arg(result_revision_number),sqlc.arg(result_content_hash)) ON CONFLICT (project_id,actor_id,operation_kind,idempotency_key) DO NOTHING;
-- name: LatestRevalidationFailure :one
SELECT status,generation_id,generation_identity_json::text,dependency_ids_json::text,error_code,error_message,attempted_at FROM dashboard.authoring_revalidation_attempts WHERE project_id=sqlc.arg(project_id) AND dashboard_id=sqlc.arg(dashboard_id) ORDER BY attempted_at DESC,attempt_id DESC LIMIT 1;
-- name: InsertRevalidationSuccess :exec
INSERT INTO dashboard.authoring_revalidation_attempts(project_id,dashboard_id,generation_id,attempt_id,generation_identity_json,graph_digest,dependency_ids_json,authored_revision_id,authored_revision_number,authored_content_hash,prior_compiled_identity_json,status,compiled_definition_hash,compiled_semantic_model_id,compiled_semantic_identity_json,attempted_at) VALUES(sqlc.arg(project_id),sqlc.arg(dashboard_id),sqlc.arg(generation_id),sqlc.arg(attempt_id)::uuid,sqlc.arg(generation_identity_json)::jsonb,sqlc.arg(graph_digest),sqlc.arg(dependency_ids_json)::jsonb,sqlc.arg(authored_revision_id)::uuid,sqlc.arg(authored_revision_number),sqlc.arg(authored_content_hash),sqlc.arg(prior_compiled_identity_json)::jsonb,'succeeded',sqlc.arg(compiled_definition_hash),sqlc.arg(compiled_semantic_model_id),sqlc.arg(compiled_semantic_identity_json)::jsonb,sqlc.arg(attempted_at));
-- name: InsertRevalidationFailure :exec
INSERT INTO dashboard.authoring_revalidation_attempts(project_id,dashboard_id,generation_id,attempt_id,generation_identity_json,graph_digest,dependency_ids_json,authored_revision_id,authored_revision_number,authored_content_hash,prior_compiled_identity_json,status,error_code,error_message,attempted_at) VALUES(sqlc.arg(project_id),sqlc.arg(dashboard_id),sqlc.arg(generation_id),sqlc.arg(attempt_id)::uuid,sqlc.arg(generation_identity_json)::jsonb,sqlc.arg(graph_digest),sqlc.arg(dependency_ids_json)::jsonb,sqlc.arg(authored_revision_id)::uuid,sqlc.arg(authored_revision_number),sqlc.arg(authored_content_hash),sqlc.arg(prior_compiled_identity_json)::jsonb,'failed',sqlc.arg(error_code),sqlc.arg(error_message),sqlc.arg(attempted_at));
-- name: Ping :one
SELECT 1 AS ping;
