package authz

import (
	"context"
	"fmt"
	"strings"

	"github.com/flidai/leapview/internal/access"
	accesssnapshot "github.com/flidai/leapview/internal/access/snapshot"
	"github.com/flidai/leapview/internal/analytics/dataquery"
	projectgraph "github.com/flidai/leapview/internal/project/graph"
)

// SemanticConsumeAction is the target action name from ADR-0026. It is kept
// as a string in this package until the global action catalog grows the
// corresponding typed capability.
const SemanticConsumeAction = "semantic.consume"

// SemanticConsumptionRequirement describes the explicit semantic-consume
// fence used by governed dashboard execution. Capability is deliberately
// injectable so the compatibility binding can move to the typed global action
// without changing dashboard query control flow.
type SemanticConsumptionRequirement struct {
	Action     string
	Capability access.Capability
}

func (r SemanticConsumptionRequirement) withDefault() SemanticConsumptionRequirement {
	if strings.TrimSpace(r.Action) == "" {
		r.Action = SemanticConsumeAction
	}
	if r.Capability == "" {
		r.Capability = access.CapabilityResourceUse
	}
	return r
}

func (r SemanticConsumptionRequirement) validate() error {
	r = r.withDefault()
	if r.Action != SemanticConsumeAction {
		return fmt.Errorf("semantic consumption action must be %q", SemanticConsumeAction)
	}
	if err := r.Capability.Validate(); err != nil {
		return fmt.Errorf("semantic consumption capability: %w", err)
	}
	return nil
}

// RequiresSemanticConsumption identifies semantic data requests generated by
// the dashboard query service and preview operations that reach GovernDataQuery.
// Public publication requests have their own publication capability and are
// handled by GovernDataQuery's publication branch before this fence.
func RequiresSemanticConsumption(request dataquery.Query) bool {
	if request.Kind == dataquery.KindModelRows || request.Surface == dataquery.SurfacePublicDashboard {
		return false
	}
	if request.Surface == dataquery.SurfaceDashboard {
		switch request.Kind {
		case dataquery.KindSemanticAggregate, dataquery.KindSemanticRows,
			dataquery.KindSemanticHistogram, dataquery.KindSemanticDistribution,
			dataquery.KindSemanticSpatialTile, dataquery.KindSemanticSpatialTileBudget,
			dataquery.KindSemanticSpatialMetadata:
			return true
		}
	}
	// The preview operation is also used by semantic dataset previews. Keep
	// this compatibility fence limited to semantic kinds; source/model preview
	// remains governed by its backing physical resource.
	if request.Operation == dataquery.OperationAPIPreview || request.Operation == dataquery.OperationPreviewWindow {
		switch request.Kind {
		case dataquery.KindSemanticAggregate, dataquery.KindSemanticRows,
			dataquery.KindSemanticHistogram, dataquery.KindSemanticDistribution,
			dataquery.KindSemanticSpatialTile, dataquery.KindSemanticSpatialTileBudget,
			dataquery.KindSemanticSpatialMetadata:
			return true
		}
	}
	return false
}

// requireSemanticConsumption checks the exact SemanticModel resource in one
// authorization snapshot. It is intentionally separate from the historical
// semantic-or-physical closure in authorizeDataQuery: a physical Model grant
// may govern a model-row preview, but it cannot substitute for semantic
// consumption when a dashboard executes a semantic request.
func (m Metrics) requireSemanticConsumption(
	ctx context.Context,
	snapshot accesssnapshot.AuthorizationSnapshot,
	principalID string,
	request dataquery.Query,
	objects []access.ResourceRef,
) error {
	if !RequiresSemanticConsumption(request) {
		return nil
	}
	requirement := m.semanticConsumption.withDefault()
	if err := requirement.validate(); err != nil {
		return err
	}
	if strings.TrimSpace(request.ModelID) == "" {
		return ErrSemanticConsumerAuthorityUnavailable
	}
	semanticModel, ok := canonicalResourceForObjects(objects, request.ModelID, projectgraph.KindSemanticModel)
	if !ok {
		return ErrSemanticConsumerAuthorityUnavailable
	}
	subjects, err := m.subjects(ctx, principalID)
	if err != nil {
		return err
	}
	for _, subject := range subjects {
		allowed, err := snapshot.Allows(subject, semanticModel, requirement.Capability)
		if err != nil {
			return err
		}
		if allowed {
			if credential, ok := m.currentCredential(ctx); ok && !m.tokenAllowsCapability(ctx, snapshot, principalID, credential.Token, requirement.Capability) {
				return DeniedError{PrincipalID: principalID, Capability: requirement.Capability, Credential: true}
			}
			return nil
		}
	}
	return DeniedError{PrincipalID: principalID, Capability: requirement.Capability}
}

func canonicalResourceForObjects(objects []access.ResourceRef, id string, kind projectgraph.Kind) (access.ResourceRef, bool) {
	for _, object := range objects {
		if object.Kind() == kind && object.CanonicalID() == strings.TrimSpace(id) {
			return object, true
		}
	}
	return access.ResourceRef{}, false
}
