// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findQueryEventByIdentity = `-- name: FindQueryEventByIdentity :one
SELECT event_id::text AS event_id, retry_identity, project_id, principal_id,
       surface, operation, query_kind, model_id, target, object_type, object_id,
       request_id, correlation_id, status, duration_ms, queue_wait_ms,
       planning_ms, connection_wait_ms, database_ms, execution_ms,
       execution_state, rows_returned, bytes_estimate, error, sql_text,
       plan_text, query_json::text AS query_json, created_at
FROM audit.query_event
WHERE event_id = $1::uuid
   OR retry_identity = $2
ORDER BY (event_id = $1::uuid) DESC
LIMIT 1
`

type FindQueryEventByIdentityParams struct {
	EventID       pgtype.UUID `json:"event_id"`
	RetryIdentity string      `json:"retry_identity"`
}

type FindQueryEventByIdentityRow struct {
	EventID          string             `json:"event_id"`
	RetryIdentity    string             `json:"retry_identity"`
	ProjectID        string             `json:"project_id"`
	PrincipalID      string             `json:"principal_id"`
	Surface          string             `json:"surface"`
	Operation        string             `json:"operation"`
	QueryKind        string             `json:"query_kind"`
	ModelID          string             `json:"model_id"`
	Target           string             `json:"target"`
	ObjectType       string             `json:"object_type"`
	ObjectID         string             `json:"object_id"`
	RequestID        string             `json:"request_id"`
	CorrelationID    string             `json:"correlation_id"`
	Status           string             `json:"status"`
	DurationMs       int64              `json:"duration_ms"`
	QueueWaitMs      int64              `json:"queue_wait_ms"`
	PlanningMs       int64              `json:"planning_ms"`
	ConnectionWaitMs int64              `json:"connection_wait_ms"`
	DatabaseMs       int64              `json:"database_ms"`
	ExecutionMs      int64              `json:"execution_ms"`
	ExecutionState   string             `json:"execution_state"`
	RowsReturned     int64              `json:"rows_returned"`
	BytesEstimate    int64              `json:"bytes_estimate"`
	Error            string             `json:"error"`
	SqlText          string             `json:"sql_text"`
	PlanText         string             `json:"plan_text"`
	QueryJson        string             `json:"query_json"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindQueryEventByIdentity(ctx context.Context, arg FindQueryEventByIdentityParams) (FindQueryEventByIdentityRow, error) {
	row := q.db.QueryRow(ctx, findQueryEventByIdentity, arg.EventID, arg.RetryIdentity)
	var i FindQueryEventByIdentityRow
	err := row.Scan(
		&i.EventID,
		&i.RetryIdentity,
		&i.ProjectID,
		&i.PrincipalID,
		&i.Surface,
		&i.Operation,
		&i.QueryKind,
		&i.ModelID,
		&i.Target,
		&i.ObjectType,
		&i.ObjectID,
		&i.RequestID,
		&i.CorrelationID,
		&i.Status,
		&i.DurationMs,
		&i.QueueWaitMs,
		&i.PlanningMs,
		&i.ConnectionWaitMs,
		&i.DatabaseMs,
		&i.ExecutionMs,
		&i.ExecutionState,
		&i.RowsReturned,
		&i.BytesEstimate,
		&i.Error,
		&i.SqlText,
		&i.PlanText,
		&i.QueryJson,
		&i.CreatedAt,
	)
	return i, err
}

const getQueryEvent = `-- name: GetQueryEvent :one
SELECT event_id::text AS event_id, retry_identity, project_id, principal_id,
       surface, operation, query_kind, model_id, target, object_type, object_id,
       request_id, correlation_id, status, duration_ms, queue_wait_ms,
       planning_ms, connection_wait_ms, database_ms, execution_ms,
       execution_state, rows_returned, bytes_estimate, error, sql_text,
       plan_text, query_json::text AS query_json, created_at
FROM audit.query_event
WHERE event_id = $1::uuid
`

type GetQueryEventRow struct {
	EventID          string             `json:"event_id"`
	RetryIdentity    string             `json:"retry_identity"`
	ProjectID        string             `json:"project_id"`
	PrincipalID      string             `json:"principal_id"`
	Surface          string             `json:"surface"`
	Operation        string             `json:"operation"`
	QueryKind        string             `json:"query_kind"`
	ModelID          string             `json:"model_id"`
	Target           string             `json:"target"`
	ObjectType       string             `json:"object_type"`
	ObjectID         string             `json:"object_id"`
	RequestID        string             `json:"request_id"`
	CorrelationID    string             `json:"correlation_id"`
	Status           string             `json:"status"`
	DurationMs       int64              `json:"duration_ms"`
	QueueWaitMs      int64              `json:"queue_wait_ms"`
	PlanningMs       int64              `json:"planning_ms"`
	ConnectionWaitMs int64              `json:"connection_wait_ms"`
	DatabaseMs       int64              `json:"database_ms"`
	ExecutionMs      int64              `json:"execution_ms"`
	ExecutionState   string             `json:"execution_state"`
	RowsReturned     int64              `json:"rows_returned"`
	BytesEstimate    int64              `json:"bytes_estimate"`
	Error            string             `json:"error"`
	SqlText          string             `json:"sql_text"`
	PlanText         string             `json:"plan_text"`
	QueryJson        string             `json:"query_json"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetQueryEvent(ctx context.Context, eventID pgtype.UUID) (GetQueryEventRow, error) {
	row := q.db.QueryRow(ctx, getQueryEvent, eventID)
	var i GetQueryEventRow
	err := row.Scan(
		&i.EventID,
		&i.RetryIdentity,
		&i.ProjectID,
		&i.PrincipalID,
		&i.Surface,
		&i.Operation,
		&i.QueryKind,
		&i.ModelID,
		&i.Target,
		&i.ObjectType,
		&i.ObjectID,
		&i.RequestID,
		&i.CorrelationID,
		&i.Status,
		&i.DurationMs,
		&i.QueueWaitMs,
		&i.PlanningMs,
		&i.ConnectionWaitMs,
		&i.DatabaseMs,
		&i.ExecutionMs,
		&i.ExecutionState,
		&i.RowsReturned,
		&i.BytesEstimate,
		&i.Error,
		&i.SqlText,
		&i.PlanText,
		&i.QueryJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertQueryEvent = `-- name: InsertQueryEvent :one

INSERT INTO audit.query_event (
    event_id, retry_identity, project_id, principal_id, surface, operation,
    query_kind, model_id, target, object_type, object_id, request_id,
    correlation_id, status, duration_ms, queue_wait_ms, planning_ms,
    connection_wait_ms, database_ms, execution_ms, execution_state,
    rows_returned, bytes_estimate, error, sql_text, plan_text, query_json
) VALUES (
    $1::uuid, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15,
    $16, $17, $18,
    $19, $20, $21,
    $22, $23, $24,
    $25, $26, $27::jsonb
)
ON CONFLICT DO NOTHING
RETURNING event_id::text
`

type InsertQueryEventParams struct {
	EventID          pgtype.UUID `json:"event_id"`
	RetryIdentity    string      `json:"retry_identity"`
	ProjectID        string      `json:"project_id"`
	PrincipalID      string      `json:"principal_id"`
	Surface          string      `json:"surface"`
	Operation        string      `json:"operation"`
	QueryKind        string      `json:"query_kind"`
	ModelID          string      `json:"model_id"`
	Target           string      `json:"target"`
	ObjectType       string      `json:"object_type"`
	ObjectID         string      `json:"object_id"`
	RequestID        string      `json:"request_id"`
	CorrelationID    string      `json:"correlation_id"`
	Status           string      `json:"status"`
	DurationMs       int64       `json:"duration_ms"`
	QueueWaitMs      int64       `json:"queue_wait_ms"`
	PlanningMs       int64       `json:"planning_ms"`
	ConnectionWaitMs int64       `json:"connection_wait_ms"`
	DatabaseMs       int64       `json:"database_ms"`
	ExecutionMs      int64       `json:"execution_ms"`
	ExecutionState   string      `json:"execution_state"`
	RowsReturned     int64       `json:"rows_returned"`
	BytesEstimate    int64       `json:"bytes_estimate"`
	Error            string      `json:"error"`
	SqlText          string      `json:"sql_text"`
	PlanText         string      `json:"plan_text"`
	QueryJson        []byte      `json:"query_json"`
}

// Static PostgreSQL query leaves for query-audit persistence.
func (q *Queries) InsertQueryEvent(ctx context.Context, arg InsertQueryEventParams) (string, error) {
	row := q.db.QueryRow(ctx, insertQueryEvent,
		arg.EventID,
		arg.RetryIdentity,
		arg.ProjectID,
		arg.PrincipalID,
		arg.Surface,
		arg.Operation,
		arg.QueryKind,
		arg.ModelID,
		arg.Target,
		arg.ObjectType,
		arg.ObjectID,
		arg.RequestID,
		arg.CorrelationID,
		arg.Status,
		arg.DurationMs,
		arg.QueueWaitMs,
		arg.PlanningMs,
		arg.ConnectionWaitMs,
		arg.DatabaseMs,
		arg.ExecutionMs,
		arg.ExecutionState,
		arg.RowsReturned,
		arg.BytesEstimate,
		arg.Error,
		arg.SqlText,
		arg.PlanText,
		arg.QueryJson,
	)
	var event_id string
	err := row.Scan(&event_id)
	return event_id, err
}

const listKindFilterOptions = `-- name: ListKindFilterOptions :many
SELECT query_kind AS value, count(*) AS count
FROM audit.query_event
WHERE query_kind <> ''
  AND ($1::text = '' OR query_kind ILIKE '%' || $1::text || '%')
GROUP BY query_kind
ORDER BY count DESC, value ASC
LIMIT $2::int
`

type ListKindFilterOptionsParams struct {
	Search   string `json:"search"`
	PageSize int32  `json:"page_size"`
}

type ListKindFilterOptionsRow struct {
	Value string `json:"value"`
	Count int64  `json:"count"`
}

func (q *Queries) ListKindFilterOptions(ctx context.Context, arg ListKindFilterOptionsParams) ([]ListKindFilterOptionsRow, error) {
	rows, err := q.db.Query(ctx, listKindFilterOptions, arg.Search, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKindFilterOptionsRow{}
	for rows.Next() {
		var i ListKindFilterOptionsRow
		if err := rows.Scan(&i.Value, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrincipalFilterOptions = `-- name: ListPrincipalFilterOptions :many
SELECT principal_id AS value, count(*) AS count
FROM audit.query_event
WHERE principal_id <> ''
  AND ($1::text = '' OR principal_id ILIKE '%' || $1::text || '%')
GROUP BY principal_id
ORDER BY count DESC, value ASC
LIMIT $2::int
`

type ListPrincipalFilterOptionsParams struct {
	Search   string `json:"search"`
	PageSize int32  `json:"page_size"`
}

type ListPrincipalFilterOptionsRow struct {
	Value string `json:"value"`
	Count int64  `json:"count"`
}

func (q *Queries) ListPrincipalFilterOptions(ctx context.Context, arg ListPrincipalFilterOptionsParams) ([]ListPrincipalFilterOptionsRow, error) {
	rows, err := q.db.Query(ctx, listPrincipalFilterOptions, arg.Search, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPrincipalFilterOptionsRow{}
	for rows.Next() {
		var i ListPrincipalFilterOptionsRow
		if err := rows.Scan(&i.Value, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueryEventFilterOptions = `-- name: ListQueryEventFilterOptions :many
SELECT project_id AS value, count(*) AS count
FROM audit.query_event
WHERE project_id <> ''
  AND ($1::text = '' OR project_id ILIKE '%' || $1::text || '%')
GROUP BY project_id
ORDER BY count DESC, value ASC
LIMIT $2::int
`

type ListQueryEventFilterOptionsParams struct {
	Search   string `json:"search"`
	PageSize int32  `json:"page_size"`
}

type ListQueryEventFilterOptionsRow struct {
	Value string `json:"value"`
	Count int64  `json:"count"`
}

func (q *Queries) ListQueryEventFilterOptions(ctx context.Context, arg ListQueryEventFilterOptionsParams) ([]ListQueryEventFilterOptionsRow, error) {
	rows, err := q.db.Query(ctx, listQueryEventFilterOptions, arg.Search, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueryEventFilterOptionsRow{}
	for rows.Next() {
		var i ListQueryEventFilterOptionsRow
		if err := rows.Scan(&i.Value, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueryEvents = `-- name: ListQueryEvents :many
SELECT event_id::text AS event_id, retry_identity, project_id, principal_id,
       surface, operation, query_kind, model_id, target, object_type, object_id,
       request_id, correlation_id, status, duration_ms, queue_wait_ms,
       planning_ms, connection_wait_ms, database_ms, execution_ms,
       execution_state, rows_returned, bytes_estimate, error, sql_text,
       plan_text, query_json::text AS query_json, created_at
FROM audit.query_event
WHERE (NOT $1::boolean
       OR project_id = ANY($2::text[]))
  AND (NOT $3::boolean
       OR principal_id = ANY($4::text[]))
  AND (NOT $5::boolean
       OR surface = ANY($6::text[]))
  AND (NOT $7::boolean
       OR operation = $8::text)
  AND (NOT $9::boolean
       OR query_kind = ANY($10::text[]))
  AND (NOT $11::boolean
       OR model_id = $12::text)
  AND (NOT $13::boolean
       OR target = $14::text)
  AND (NOT $15::boolean
       OR status = ANY($16::text[]))
  AND (NOT $17::boolean
       OR search_document @@ websearch_to_tsquery('simple', $18::text))
  AND (NOT $19::boolean
       OR created_at >= $20::timestamptz)
  AND (NOT $21::boolean
       OR created_at <= $22::timestamptz)
  AND (NOT $23::boolean
       OR created_at < $24::timestamptz
       OR (created_at = $24::timestamptz
           AND event_id < $25::uuid))
ORDER BY created_at DESC, event_id DESC
LIMIT $26::int
`

type ListQueryEventsParams struct {
	HasProject   bool               `json:"has_project"`
	ProjectIds   []string           `json:"project_ids"`
	HasPrincipal bool               `json:"has_principal"`
	PrincipalIds []string           `json:"principal_ids"`
	HasSurface   bool               `json:"has_surface"`
	Surfaces     []string           `json:"surfaces"`
	HasOperation bool               `json:"has_operation"`
	Operation    string             `json:"operation"`
	HasQueryKind bool               `json:"has_query_kind"`
	QueryKinds   []string           `json:"query_kinds"`
	HasModel     bool               `json:"has_model"`
	ModelID      string             `json:"model_id"`
	HasTarget    bool               `json:"has_target"`
	Target       string             `json:"target"`
	HasStatus    bool               `json:"has_status"`
	Statuses     []string           `json:"statuses"`
	HasSearch    bool               `json:"has_search"`
	Search       string             `json:"search"`
	HasFrom      bool               `json:"has_from"`
	FromTime     pgtype.Timestamptz `json:"from_time"`
	HasTo        bool               `json:"has_to"`
	ToTime       pgtype.Timestamptz `json:"to_time"`
	HasCursor    bool               `json:"has_cursor"`
	CursorTime   pgtype.Timestamptz `json:"cursor_time"`
	CursorID     pgtype.UUID        `json:"cursor_id"`
	PageSize     int32              `json:"page_size"`
}

type ListQueryEventsRow struct {
	EventID          string             `json:"event_id"`
	RetryIdentity    string             `json:"retry_identity"`
	ProjectID        string             `json:"project_id"`
	PrincipalID      string             `json:"principal_id"`
	Surface          string             `json:"surface"`
	Operation        string             `json:"operation"`
	QueryKind        string             `json:"query_kind"`
	ModelID          string             `json:"model_id"`
	Target           string             `json:"target"`
	ObjectType       string             `json:"object_type"`
	ObjectID         string             `json:"object_id"`
	RequestID        string             `json:"request_id"`
	CorrelationID    string             `json:"correlation_id"`
	Status           string             `json:"status"`
	DurationMs       int64              `json:"duration_ms"`
	QueueWaitMs      int64              `json:"queue_wait_ms"`
	PlanningMs       int64              `json:"planning_ms"`
	ConnectionWaitMs int64              `json:"connection_wait_ms"`
	DatabaseMs       int64              `json:"database_ms"`
	ExecutionMs      int64              `json:"execution_ms"`
	ExecutionState   string             `json:"execution_state"`
	RowsReturned     int64              `json:"rows_returned"`
	BytesEstimate    int64              `json:"bytes_estimate"`
	Error            string             `json:"error"`
	SqlText          string             `json:"sql_text"`
	PlanText         string             `json:"plan_text"`
	QueryJson        string             `json:"query_json"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListQueryEvents(ctx context.Context, arg ListQueryEventsParams) ([]ListQueryEventsRow, error) {
	rows, err := q.db.Query(ctx, listQueryEvents,
		arg.HasProject,
		arg.ProjectIds,
		arg.HasPrincipal,
		arg.PrincipalIds,
		arg.HasSurface,
		arg.Surfaces,
		arg.HasOperation,
		arg.Operation,
		arg.HasQueryKind,
		arg.QueryKinds,
		arg.HasModel,
		arg.ModelID,
		arg.HasTarget,
		arg.Target,
		arg.HasStatus,
		arg.Statuses,
		arg.HasSearch,
		arg.Search,
		arg.HasFrom,
		arg.FromTime,
		arg.HasTo,
		arg.ToTime,
		arg.HasCursor,
		arg.CursorTime,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueryEventsRow{}
	for rows.Next() {
		var i ListQueryEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.RetryIdentity,
			&i.ProjectID,
			&i.PrincipalID,
			&i.Surface,
			&i.Operation,
			&i.QueryKind,
			&i.ModelID,
			&i.Target,
			&i.ObjectType,
			&i.ObjectID,
			&i.RequestID,
			&i.CorrelationID,
			&i.Status,
			&i.DurationMs,
			&i.QueueWaitMs,
			&i.PlanningMs,
			&i.ConnectionWaitMs,
			&i.DatabaseMs,
			&i.ExecutionMs,
			&i.ExecutionState,
			&i.RowsReturned,
			&i.BytesEstimate,
			&i.Error,
			&i.SqlText,
			&i.PlanText,
			&i.QueryJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusFilterOptions = `-- name: ListStatusFilterOptions :many
SELECT status AS value, count(*) AS count
FROM audit.query_event
WHERE status <> ''
  AND ($1::text = '' OR status ILIKE '%' || $1::text || '%')
GROUP BY status
ORDER BY count DESC, value ASC
LIMIT $2::int
`

type ListStatusFilterOptionsParams struct {
	Search   string `json:"search"`
	PageSize int32  `json:"page_size"`
}

type ListStatusFilterOptionsRow struct {
	Value string `json:"value"`
	Count int64  `json:"count"`
}

func (q *Queries) ListStatusFilterOptions(ctx context.Context, arg ListStatusFilterOptionsParams) ([]ListStatusFilterOptionsRow, error) {
	rows, err := q.db.Query(ctx, listStatusFilterOptions, arg.Search, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStatusFilterOptionsRow{}
	for rows.Next() {
		var i ListStatusFilterOptionsRow
		if err := rows.Scan(&i.Value, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSurfaceFilterOptions = `-- name: ListSurfaceFilterOptions :many
SELECT surface AS value, count(*) AS count
FROM audit.query_event
WHERE surface <> ''
  AND ($1::text = '' OR surface ILIKE '%' || $1::text || '%')
GROUP BY surface
ORDER BY count DESC, value ASC
LIMIT $2::int
`

type ListSurfaceFilterOptionsParams struct {
	Search   string `json:"search"`
	PageSize int32  `json:"page_size"`
}

type ListSurfaceFilterOptionsRow struct {
	Value string `json:"value"`
	Count int64  `json:"count"`
}

func (q *Queries) ListSurfaceFilterOptions(ctx context.Context, arg ListSurfaceFilterOptionsParams) ([]ListSurfaceFilterOptionsRow, error) {
	rows, err := q.db.Query(ctx, listSurfaceFilterOptions, arg.Search, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSurfaceFilterOptionsRow{}
	for rows.Next() {
		var i ListSurfaceFilterOptionsRow
		if err := rows.Scan(&i.Value, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
