// Command schemadocgen turns LeapView's JSON Schema contracts into the
// Markdown configuration reference consumed by the public documentation site.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	schemaDir := flag.String("schemas", "schemas/json", "JSON Schema input directory")
	exampleDir := flag.String("examples", "dashboards", "canonical YAML example directory")
	outDir := flag.String("out", "docs/reference/config", "generated Markdown output directory")
	flag.Parse()
	if err := generate(*schemaDir, *exampleDir, *outDir); err != nil {
		fmt.Fprintf(os.Stderr, "generate schema documentation: %v\n", err)
		os.Exit(1)
	}
}

type schema map[string]any

type catalog struct {
	Title     string     `json:"title"`
	Documents []document `json:"documents"`
}

type document struct {
	Slug    string `json:"slug"`
	Title   string `json:"title"`
	Summary string `json:"summary"`
}

func generate(schemaDir, exampleDir, outDir string) error {
	entries, err := os.ReadDir(schemaDir)
	if err != nil {
		return fmt.Errorf("read schemas: %w", err)
	}
	if err := os.RemoveAll(outDir); err != nil {
		return fmt.Errorf("clear output: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(outDir, "schemas"), 0o755); err != nil {
		return fmt.Errorf("create output: %w", err)
	}
	examples, err := examplesByKind(exampleDir)
	if err != nil {
		return err
	}
	documents := make([]document, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".schema.json") {
			continue
		}
		slug := strings.TrimSuffix(entry.Name(), ".schema.json")
		contents, err := os.ReadFile(filepath.Join(schemaDir, entry.Name()))
		if err != nil {
			return err
		}
		var value schema
		if err := json.Unmarshal(contents, &value); err != nil {
			return fmt.Errorf("decode %s: %w", entry.Name(), err)
		}
		kind := stringValue(value["properties"], "kind", "const")
		if kind == "" {
			return fmt.Errorf("schema %s has no kind", entry.Name())
		}
		title := humanize(kind) + " configuration"
		documents = append(documents, document{Slug: slug, Title: title, Summary: "Fields and validation rules for the " + kind + " YAML resource."})
		example := examples[kind]
		if example == "" {
			example, err = exampleFromSchema(value)
			if err != nil {
				return fmt.Errorf("generate %s example: %w", kind, err)
			}
		}
		if err := os.WriteFile(filepath.Join(outDir, slug+".md"), []byte(renderDocument(title, kind, slug, value, example)), 0o644); err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(outDir, "schemas", entry.Name()), contents, 0o644); err != nil {
			return err
		}
	}
	if len(documents) == 0 {
		return fmt.Errorf("no JSON Schema files found in %s", schemaDir)
	}
	sort.Slice(documents, func(i, j int) bool {
		return configurationDocumentOrder(documents[i].Slug) < configurationDocumentOrder(documents[j].Slug)
	})
	encoded, err := json.MarshalIndent(catalog{Title: "YAML configuration", Documents: documents}, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(outDir, "catalog.json"), append(encoded, '\n'), 0o644)
}

func configurationDocumentOrder(slug string) int {
	order := []string{"project", "connection", "source", "model", "semantic-model", "pipeline", "dashboard", "group", "role-binding", "grant", "data-policy", "dashboard-publication"}
	for index, candidate := range order {
		if slug == candidate {
			return index
		}
	}
	return len(order)
}

func examplesByKind(root string) (map[string]string, error) {
	examples := map[string]string{}
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || (!strings.HasSuffix(path, ".yaml") && !strings.HasSuffix(path, ".yml")) {
			return nil
		}
		contents, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		var value map[string]any
		if yaml.Unmarshal(contents, &value) != nil {
			return nil
		}
		kind, _ := value["kind"].(string)
		if kind == "" {
			return nil
		}
		if _, exists := examples[kind]; !exists {
			examples[kind] = string(contents)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("read canonical YAML examples: %w", err)
	}
	return examples, nil
}

func renderDocument(title, kind, slug string, root schema, example string) string {
	var out strings.Builder
	out.WriteString("<!-- Code generated by internal/app/tools/schemadocgen; DO NOT EDIT. -->\n\n# " + title + "\n\n")
	out.WriteString("[Download JSON Schema](/docs/schemas/" + slug + ".schema.json)\n\n")
	out.WriteString("## Example\n\n```yaml\n")
	out.WriteString(strings.TrimSpace(example))
	out.WriteString("\n```\n\n## Fields\n\n")
	writeFields(&out, root)
	defs, _ := root["$defs"].(map[string]any)
	if len(defs) > 0 {
		keys := sortedKeys(defs)
		out.WriteString("\n## Nested definitions\n")
		for _, key := range keys {
			value, _ := defs[key].(map[string]any)
			out.WriteString("\n### " + strings.TrimPrefix(key, "#") + "\n\n")
			writeFields(&out, value)
		}
	}
	return out.String()
}

func exampleFromSchema(root schema) (string, error) {
	value, err := exampleValue(root, root, map[string]bool{})
	if err != nil {
		return "", err
	}
	var encoded strings.Builder
	encoder := yaml.NewEncoder(&encoded)
	encoder.SetIndent(2)
	if err := encoder.Encode(value); err != nil {
		return "", fmt.Errorf("encode YAML: %w", err)
	}
	if err := encoder.Close(); err != nil {
		return "", fmt.Errorf("close YAML encoder: %w", err)
	}
	return encoded.String(), nil
}

func exampleValue(root schema, value map[string]any, resolving map[string]bool) (any, error) {
	if constant, exists := value["const"]; exists {
		return constant, nil
	}
	if values, ok := value["enum"].([]any); ok && len(values) > 0 {
		return values[0], nil
	}
	if reference, ok := value["$ref"].(string); ok {
		const prefix = "#/$defs/"
		if !strings.HasPrefix(reference, prefix) {
			return nil, fmt.Errorf("unsupported reference %q", reference)
		}
		name, err := url.PathUnescape(strings.TrimPrefix(reference, prefix))
		if err != nil {
			return nil, fmt.Errorf("decode reference %q: %w", reference, err)
		}
		if resolving[name] {
			return nil, fmt.Errorf("recursive reference %q", name)
		}
		definitions, _ := root["$defs"].(map[string]any)
		definition, ok := definitions[name].(map[string]any)
		if !ok {
			return nil, fmt.Errorf("missing definition %q", name)
		}
		resolving[name] = true
		result, err := exampleValue(root, definition, resolving)
		delete(resolving, name)
		return result, err
	}
	for _, union := range []string{"oneOf", "anyOf"} {
		if alternatives, ok := value[union].([]any); ok && len(alternatives) > 0 {
			alternative, _ := alternatives[0].(map[string]any)
			return exampleValue(root, alternative, resolving)
		}
	}

	kind, _ := value["type"].(string)
	if kind == "" && value["properties"] != nil {
		kind = "object"
	}
	switch kind {
	case "object", "":
		result := map[string]any{}
		properties, _ := value["properties"].(map[string]any)
		for _, name := range requiredFieldsInOrder(value) {
			property, ok := properties[name].(map[string]any)
			if !ok {
				return nil, fmt.Errorf("required property %q has no schema", name)
			}
			example, err := exampleValue(root, property, resolving)
			if err != nil {
				return nil, fmt.Errorf("property %s: %w", name, err)
			}
			result[name] = example
		}
		return result, nil
	case "array":
		return []any{}, nil
	case "string":
		return "example", nil
	case "integer":
		if minimum, ok := value["minimum"].(float64); ok {
			return int(minimum), nil
		}
		return 0, nil
	case "number":
		if minimum, ok := value["minimum"].(float64); ok {
			return minimum, nil
		}
		return 0, nil
	case "boolean":
		return false, nil
	case "null":
		return nil, nil
	default:
		return nil, fmt.Errorf("unsupported schema type %q", kind)
	}
}

func requiredFieldsInOrder(value map[string]any) []string {
	required := requiredFields(value)
	names := make([]string, 0, len(required))
	for name := range required {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func writeFields(out *strings.Builder, value schema) {
	properties, _ := value["properties"].(map[string]any)
	required := requiredFields(value)
	out.WriteString("| Field | Type | Required | Rules |\n| --- | --- | --- | --- |\n")
	for _, name := range sortedKeys(properties) {
		field, _ := properties[name].(map[string]any)
		rules := schemaRules(field)
		out.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n", name, schemaType(field), yesNo(required[name]), rules))
	}
}

func stringValue(raw any, keys ...string) string {
	value := raw
	for _, key := range keys {
		object, ok := value.(map[string]any)
		if !ok {
			return ""
		}
		value = object[key]
	}
	result, _ := value.(string)
	return result
}

func requiredFields(value schema) map[string]bool {
	result := map[string]bool{}
	fields, _ := value["required"].([]any)
	for _, field := range fields {
		if name, ok := field.(string); ok {
			result[name] = true
		}
	}
	return result
}
func sortedKeys(values map[string]any) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
func yesNo(value bool) string {
	if value {
		return "Yes"
	}
	return "No"
}
func humanize(value string) string {
	var out strings.Builder
	for index, runeValue := range value {
		if index > 0 && runeValue >= 'A' && runeValue <= 'Z' {
			out.WriteByte(' ')
		}
		out.WriteRune(runeValue)
	}
	return strings.ReplaceAll(out.String(), "-", " ")
}

func schemaType(value map[string]any) string {
	if constant, ok := value["const"]; ok {
		return "`" + fmt.Sprint(constant) + "`"
	}
	if ref, ok := value["$ref"].(string); ok {
		return "`" + strings.TrimPrefix(strings.TrimPrefix(ref, "#/$defs/"), "%23") + "`"
	}
	if kind, ok := value["type"].(string); ok {
		if kind == "array" {
			if items, ok := value["items"].(map[string]any); ok {
				return "array of " + schemaType(items)
			}
		}
		return kind
	}
	return "object"
}

func schemaRules(value map[string]any) string {
	parts := []string{}
	if enum, ok := value["enum"].([]any); ok {
		values := make([]string, 0, len(enum))
		for _, item := range enum {
			values = append(values, "`"+fmt.Sprint(item)+"`")
		}
		parts = append(parts, "one of "+strings.Join(values, ", "))
	}
	if pattern, ok := value["pattern"].(string); ok {
		parts = append(parts, "pattern `"+pattern+"`")
	}
	if value["additionalProperties"] == false {
		parts = append(parts, "no additional fields")
	}
	return strings.Join(parts, "; ")
}
