// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: serving_state.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeFlag = `-- name: ActiveFlag :one
SELECT EXISTS (
    SELECT 1 FROM delivery.delivery_active_pointer p
    JOIN delivery.delivery_generation g ON g.generation_id = p.generation_id
    WHERE p.generation_id = $1::uuid
)
`

func (q *Queries) ActiveFlag(ctx context.Context, dollar_1 pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, activeFlag, dollar_1)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const assetVersions = `-- name: AssetVersions :many
SELECT g.generation_id::text, t.project_id, t.environment,
       CASE WHEN ap.generation_id IS NULL THEN 'validated' ELSE 'active' END,
       g.serving_artifact_digest, p.actor_id, g.created_at,
       a.snapshot_id, a.source_file, a.payload_json::text, a.content_hash,
       COALESCE(p.committed_at, g.created_at)
FROM serving_state.asset a
JOIN delivery.delivery_generation g ON g.generation_id = a.generation_id
JOIN delivery.delivery_target t ON t.target_id = g.target_id
JOIN delivery.delivery_publication p
  ON p.generation_id = g.generation_id AND p.state = 'committed'
LEFT JOIN delivery.delivery_active_pointer ap ON ap.generation_id = g.generation_id
WHERE t.project_id = $1 AND t.environment = $2
  AND a.logical_asset_id = $3
ORDER BY g.created_at DESC, g.generation_id DESC
`

type AssetVersionsParams struct {
	ProjectID      string `json:"project_id"`
	Environment    string `json:"environment"`
	LogicalAssetID string `json:"logical_asset_id"`
}

type AssetVersionsRow struct {
	GGenerationID         string             `json:"g_generation_id"`
	ProjectID             string             `json:"project_id"`
	Environment           string             `json:"environment"`
	Column4               string             `json:"column_4"`
	ServingArtifactDigest string             `json:"serving_artifact_digest"`
	ActorID               string             `json:"actor_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	SnapshotID            string             `json:"snapshot_id"`
	SourceFile            string             `json:"source_file"`
	APayloadJson          string             `json:"a_payload_json"`
	ContentHash           string             `json:"content_hash"`
	CommittedAt           pgtype.Timestamptz `json:"committed_at"`
}

func (q *Queries) AssetVersions(ctx context.Context, arg AssetVersionsParams) ([]AssetVersionsRow, error) {
	rows, err := q.db.Query(ctx, assetVersions, arg.ProjectID, arg.Environment, arg.LogicalAssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetVersionsRow{}
	for rows.Next() {
		var i AssetVersionsRow
		if err := rows.Scan(
			&i.GGenerationID,
			&i.ProjectID,
			&i.Environment,
			&i.Column4,
			&i.ServingArtifactDigest,
			&i.ActorID,
			&i.CreatedAt,
			&i.SnapshotID,
			&i.SourceFile,
			&i.APayloadJson,
			&i.ContentHash,
			&i.CommittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createReaderLease = `-- name: CreateReaderLease :execrows
INSERT INTO serving_state.reader_lease (
    lease_id, generation_id, ducklake_snapshot_id, owner_id, expires_at
) SELECT $1, $2::uuid, $3, $4,
         COALESCE($5::timestamptz, clock_timestamp() + interval '5 minutes')
WHERE EXISTS (
    SELECT 1 FROM delivery.delivery_generation g
    JOIN delivery.delivery_snapshot_seal s ON s.seal_id = g.snapshot_seal_id
    JOIN delivery.delivery_retention_root r
      ON r.generation_id = g.generation_id AND r.snapshot_seal_id = s.seal_id
    WHERE g.generation_id = $2::uuid AND s.ducklake_snapshot_id = $3
      AND r.root_kind = 'generation' AND r.state = 'live'
      AND (r.expires_at IS NULL OR r.expires_at > clock_timestamp())
)
  AND COALESCE($5::timestamptz, clock_timestamp() + interval '5 minutes') > clock_timestamp()
  AND COALESCE($5::timestamptz, clock_timestamp() + interval '5 minutes') <= clock_timestamp() + interval '24 hours'
`

type CreateReaderLeaseParams struct {
	LeaseID            string             `json:"lease_id"`
	Column2            pgtype.UUID        `json:"column_2"`
	DucklakeSnapshotID int64              `json:"ducklake_snapshot_id"`
	OwnerID            string             `json:"owner_id"`
	Column5            pgtype.Timestamptz `json:"column_5"`
}

func (q *Queries) CreateReaderLease(ctx context.Context, arg CreateReaderLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, createReaderLease,
		arg.LeaseID,
		arg.Column2,
		arg.DucklakeSnapshotID,
		arg.OwnerID,
		arg.Column5,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendReaderLease = `-- name: ExtendReaderLease :execrows
WITH live_retention AS (
    SELECT 1
    FROM serving_state.reader_lease l
    JOIN delivery.delivery_generation g ON g.generation_id = l.generation_id
    JOIN delivery.delivery_snapshot_seal s ON s.seal_id = g.snapshot_seal_id
    JOIN delivery.delivery_retention_root r
      ON r.generation_id = g.generation_id AND r.snapshot_seal_id = s.seal_id
    WHERE l.lease_id = $1 AND l.released_at IS NULL
      AND l.expires_at > clock_timestamp()
      AND s.ducklake_snapshot_id = l.ducklake_snapshot_id
      AND r.root_kind = 'generation' AND r.state = 'live'
      AND (r.expires_at IS NULL OR r.expires_at > clock_timestamp())
)
UPDATE serving_state.reader_lease l
SET expires_at = $2
FROM delivery.delivery_generation g
JOIN delivery.delivery_snapshot_seal s ON s.seal_id = g.snapshot_seal_id
JOIN delivery.delivery_retention_root r
  ON r.generation_id = g.generation_id AND r.snapshot_seal_id = s.seal_id
WHERE l.lease_id = $1 AND l.generation_id = g.generation_id
  AND l.ducklake_snapshot_id = s.ducklake_snapshot_id
  AND r.root_kind = 'generation' AND r.state = 'live'
  AND (r.expires_at IS NULL OR r.expires_at > clock_timestamp())
  AND EXISTS (SELECT 1 FROM live_retention)
  AND l.released_at IS NULL
  AND l.expires_at > clock_timestamp()
  AND $2 > l.expires_at
  AND $2 <= clock_timestamp() + interval '24 hours'
`

type ExtendReaderLeaseParams struct {
	LeaseID   string             `json:"lease_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ExtendReaderLease(ctx context.Context, arg ExtendReaderLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendReaderLease, arg.LeaseID, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const foreignSnapshots = `-- name: ForeignSnapshots :many
SELECT DISTINCT s.ducklake_snapshot_id
FROM delivery.delivery_generation g
JOIN delivery.delivery_snapshot_seal s ON s.seal_id = g.snapshot_seal_id
JOIN delivery.delivery_target t ON t.target_id = g.target_id
WHERE t.environment <> $1 AND s.ducklake_snapshot_id > 0
ORDER BY s.ducklake_snapshot_id
`

func (q *Queries) ForeignSnapshots(ctx context.Context, environment string) ([]int64, error) {
	rows, err := q.db.Query(ctx, foreignSnapshots, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var ducklake_snapshot_id int64
		if err := rows.Scan(&ducklake_snapshot_id); err != nil {
			return nil, err
		}
		items = append(items, ducklake_snapshot_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const generationEvidence = `-- name: GenerationEvidence :one
SELECT t.project_id, t.environment,
       g.serving_artifact_digest, g.compiled_graph_digest
FROM delivery.delivery_generation g
JOIN delivery.delivery_target t ON t.target_id = g.target_id
WHERE g.generation_id = $1::uuid
`

type GenerationEvidenceRow struct {
	ProjectID             string `json:"project_id"`
	Environment           string `json:"environment"`
	ServingArtifactDigest string `json:"serving_artifact_digest"`
	CompiledGraphDigest   string `json:"compiled_graph_digest"`
}

func (q *Queries) GenerationEvidence(ctx context.Context, dollar_1 pgtype.UUID) (GenerationEvidenceRow, error) {
	row := q.db.QueryRow(ctx, generationEvidence, dollar_1)
	var i GenerationEvidenceRow
	err := row.Scan(
		&i.ProjectID,
		&i.Environment,
		&i.ServingArtifactDigest,
		&i.CompiledGraphDigest,
	)
	return i, err
}

const getActiveBundle = `-- name: GetActiveBundle :one
SELECT b.generation_id::text, b.project_id, b.environment, b.artifact_id,
       b.artifact_digest, b.compiled_graph_digest, b.artifact_format,
       b.artifact_locator, b.manifest_json::text, b.project_digest,
       b.access_policy_json::text, b.dashboard_publications_json::text,
       b.dashboard_appearances_json::text, b.size_bytes, b.created_by,
       b.created_at, s.ducklake_snapshot_id
FROM delivery.delivery_active_pointer ap
JOIN delivery.delivery_target t ON t.target_id = ap.target_id
JOIN delivery.delivery_generation g ON g.generation_id = ap.generation_id
JOIN delivery.delivery_snapshot_seal s ON s.seal_id = g.snapshot_seal_id
JOIN serving_state.bundle b ON b.generation_id = g.generation_id
WHERE t.project_id = $1 AND t.environment = $2
`

type GetActiveBundleParams struct {
	ProjectID   string `json:"project_id"`
	Environment string `json:"environment"`
}

type GetActiveBundleRow struct {
	BGenerationID              string             `json:"b_generation_id"`
	ProjectID                  string             `json:"project_id"`
	Environment                string             `json:"environment"`
	ArtifactID                 string             `json:"artifact_id"`
	ArtifactDigest             string             `json:"artifact_digest"`
	CompiledGraphDigest        string             `json:"compiled_graph_digest"`
	ArtifactFormat             string             `json:"artifact_format"`
	ArtifactLocator            string             `json:"artifact_locator"`
	BManifestJson              string             `json:"b_manifest_json"`
	ProjectDigest              string             `json:"project_digest"`
	BAccessPolicyJson          string             `json:"b_access_policy_json"`
	BDashboardPublicationsJson string             `json:"b_dashboard_publications_json"`
	BDashboardAppearancesJson  string             `json:"b_dashboard_appearances_json"`
	SizeBytes                  int64              `json:"size_bytes"`
	CreatedBy                  string             `json:"created_by"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	DucklakeSnapshotID         int64              `json:"ducklake_snapshot_id"`
}

func (q *Queries) GetActiveBundle(ctx context.Context, arg GetActiveBundleParams) (GetActiveBundleRow, error) {
	row := q.db.QueryRow(ctx, getActiveBundle, arg.ProjectID, arg.Environment)
	var i GetActiveBundleRow
	err := row.Scan(
		&i.BGenerationID,
		&i.ProjectID,
		&i.Environment,
		&i.ArtifactID,
		&i.ArtifactDigest,
		&i.CompiledGraphDigest,
		&i.ArtifactFormat,
		&i.ArtifactLocator,
		&i.BManifestJson,
		&i.ProjectDigest,
		&i.BAccessPolicyJson,
		&i.BDashboardPublicationsJson,
		&i.BDashboardAppearancesJson,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DucklakeSnapshotID,
	)
	return i, err
}

const getBundle = `-- name: GetBundle :one

SELECT b.generation_id::text, b.project_id, b.environment, b.artifact_id,
       b.artifact_digest, b.compiled_graph_digest, b.artifact_format,
       b.artifact_locator, b.manifest_json::text, b.project_digest,
       b.access_policy_json::text, b.dashboard_publications_json::text,
       b.dashboard_appearances_json::text, b.size_bytes, b.created_by,
       b.created_at, s.ducklake_snapshot_id
FROM serving_state.bundle b
JOIN delivery.delivery_generation g ON g.generation_id = b.generation_id
JOIN delivery.delivery_snapshot_seal s ON s.seal_id = g.snapshot_seal_id
WHERE b.generation_id = $1::uuid
`

type GetBundleRow struct {
	BGenerationID              string             `json:"b_generation_id"`
	ProjectID                  string             `json:"project_id"`
	Environment                string             `json:"environment"`
	ArtifactID                 string             `json:"artifact_id"`
	ArtifactDigest             string             `json:"artifact_digest"`
	CompiledGraphDigest        string             `json:"compiled_graph_digest"`
	ArtifactFormat             string             `json:"artifact_format"`
	ArtifactLocator            string             `json:"artifact_locator"`
	BManifestJson              string             `json:"b_manifest_json"`
	ProjectDigest              string             `json:"project_digest"`
	BAccessPolicyJson          string             `json:"b_access_policy_json"`
	BDashboardPublicationsJson string             `json:"b_dashboard_publications_json"`
	BDashboardAppearancesJson  string             `json:"b_dashboard_appearances_json"`
	SizeBytes                  int64              `json:"size_bytes"`
	CreatedBy                  string             `json:"created_by"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	DucklakeSnapshotID         int64              `json:"ducklake_snapshot_id"`
}

// Named PostgreSQL queries for immutable serving-generation evidence.
// Delivery remains the lifecycle/active-selection authority; these statements
// only insert/read bundle projections and maintain reader leases.
func (q *Queries) GetBundle(ctx context.Context, dollar_1 pgtype.UUID) (GetBundleRow, error) {
	row := q.db.QueryRow(ctx, getBundle, dollar_1)
	var i GetBundleRow
	err := row.Scan(
		&i.BGenerationID,
		&i.ProjectID,
		&i.Environment,
		&i.ArtifactID,
		&i.ArtifactDigest,
		&i.CompiledGraphDigest,
		&i.ArtifactFormat,
		&i.ArtifactLocator,
		&i.BManifestJson,
		&i.ProjectDigest,
		&i.BAccessPolicyJson,
		&i.BDashboardPublicationsJson,
		&i.BDashboardAppearancesJson,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DucklakeSnapshotID,
	)
	return i, err
}

const guardReaderSnapshotRetention = `-- name: GuardReaderSnapshotRetention :one
SELECT serving_state.guard_reader_snapshot_retention($1::uuid, $2)
`

type GuardReaderSnapshotRetentionParams struct {
	Column1   pgtype.UUID `json:"column_1"`
	PSnapshot int64       `json:"p_snapshot"`
}

func (q *Queries) GuardReaderSnapshotRetention(ctx context.Context, arg GuardReaderSnapshotRetentionParams) (bool, error) {
	row := q.db.QueryRow(ctx, guardReaderSnapshotRetention, arg.Column1, arg.PSnapshot)
	var guard_reader_snapshot_retention bool
	err := row.Scan(&guard_reader_snapshot_retention)
	return guard_reader_snapshot_retention, err
}

const insertAsset = `-- name: InsertAsset :execrows
INSERT INTO serving_state.asset (
    generation_id, snapshot_id, logical_asset_id, asset_type, asset_key,
    title, description, source_file, payload_schema, payload_json, content_hash
) VALUES ($1::uuid, $2, $3, $4, $5, $6, $7, $8, $9, $10::jsonb, $11)
ON CONFLICT (generation_id, logical_asset_id) DO NOTHING
`

type InsertAssetParams struct {
	Column1        pgtype.UUID `json:"column_1"`
	SnapshotID     string      `json:"snapshot_id"`
	LogicalAssetID string      `json:"logical_asset_id"`
	AssetType      string      `json:"asset_type"`
	AssetKey       string      `json:"asset_key"`
	Title          string      `json:"title"`
	Description    string      `json:"description"`
	SourceFile     string      `json:"source_file"`
	PayloadSchema  string      `json:"payload_schema"`
	Column10       []byte      `json:"column_10"`
	ContentHash    string      `json:"content_hash"`
}

func (q *Queries) InsertAsset(ctx context.Context, arg InsertAssetParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAsset,
		arg.Column1,
		arg.SnapshotID,
		arg.LogicalAssetID,
		arg.AssetType,
		arg.AssetKey,
		arg.Title,
		arg.Description,
		arg.SourceFile,
		arg.PayloadSchema,
		arg.Column10,
		arg.ContentHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAssetEdge = `-- name: InsertAssetEdge :execrows
INSERT INTO serving_state.asset_edge (
    generation_id, id, from_logical_asset_id, to_logical_asset_id, edge_type
) VALUES ($1::uuid, $2, $3, $4, $5)
ON CONFLICT (generation_id, id) DO NOTHING
`

type InsertAssetEdgeParams struct {
	Column1            pgtype.UUID `json:"column_1"`
	ID                 string      `json:"id"`
	FromLogicalAssetID string      `json:"from_logical_asset_id"`
	ToLogicalAssetID   string      `json:"to_logical_asset_id"`
	EdgeType           string      `json:"edge_type"`
}

func (q *Queries) InsertAssetEdge(ctx context.Context, arg InsertAssetEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAssetEdge,
		arg.Column1,
		arg.ID,
		arg.FromLogicalAssetID,
		arg.ToLogicalAssetID,
		arg.EdgeType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertBundle = `-- name: InsertBundle :execrows
INSERT INTO serving_state.bundle (
    generation_id, project_id, environment, artifact_id, artifact_digest,
    compiled_graph_digest, artifact_format, artifact_locator, manifest_json,
    project_digest, access_policy_json, dashboard_publications_json,
    dashboard_appearances_json, size_bytes, created_by
) VALUES ($1::uuid, $2, $3, $4, $5, $6, $7, $8, $9::jsonb, $10,
          $11::jsonb, $12::jsonb, $13::jsonb, $14, $15)
ON CONFLICT (generation_id) DO NOTHING
`

type InsertBundleParams struct {
	Column1             pgtype.UUID `json:"column_1"`
	ProjectID           string      `json:"project_id"`
	Environment         string      `json:"environment"`
	ArtifactID          string      `json:"artifact_id"`
	ArtifactDigest      string      `json:"artifact_digest"`
	CompiledGraphDigest string      `json:"compiled_graph_digest"`
	ArtifactFormat      string      `json:"artifact_format"`
	ArtifactLocator     string      `json:"artifact_locator"`
	Column9             []byte      `json:"column_9"`
	ProjectDigest       string      `json:"project_digest"`
	Column11            []byte      `json:"column_11"`
	Column12            []byte      `json:"column_12"`
	Column13            []byte      `json:"column_13"`
	SizeBytes           int64       `json:"size_bytes"`
	CreatedBy           string      `json:"created_by"`
}

func (q *Queries) InsertBundle(ctx context.Context, arg InsertBundleParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBundle,
		arg.Column1,
		arg.ProjectID,
		arg.Environment,
		arg.ArtifactID,
		arg.ArtifactDigest,
		arg.CompiledGraphDigest,
		arg.ArtifactFormat,
		arg.ArtifactLocator,
		arg.Column9,
		arg.ProjectDigest,
		arg.Column11,
		arg.Column12,
		arg.Column13,
		arg.SizeBytes,
		arg.CreatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const leasedSnapshots = `-- name: LeasedSnapshots :many
SELECT DISTINCT l.ducklake_snapshot_id
FROM serving_state.reader_lease l
JOIN delivery.delivery_generation g ON g.generation_id = l.generation_id
JOIN delivery.delivery_target t ON t.target_id = g.target_id
WHERE t.environment = $1 AND l.released_at IS NULL
  AND l.expires_at > clock_timestamp()
ORDER BY l.ducklake_snapshot_id
`

func (q *Queries) LeasedSnapshots(ctx context.Context, environment string) ([]int64, error) {
	rows, err := q.db.Query(ctx, leasedSnapshots, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var ducklake_snapshot_id int64
		if err := rows.Scan(&ducklake_snapshot_id); err != nil {
			return nil, err
		}
		items = append(items, ducklake_snapshot_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveScopes = `-- name: ListActiveScopes :many
SELECT t.project_id, t.environment
FROM delivery.delivery_active_pointer ap
JOIN delivery.delivery_target t ON t.target_id = ap.target_id
ORDER BY t.project_id, t.environment
`

type ListActiveScopesRow struct {
	ProjectID   string `json:"project_id"`
	Environment string `json:"environment"`
}

func (q *Queries) ListActiveScopes(ctx context.Context) ([]ListActiveScopesRow, error) {
	rows, err := q.db.Query(ctx, listActiveScopes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveScopesRow{}
	for rows.Next() {
		var i ListActiveScopesRow
		if err := rows.Scan(&i.ProjectID, &i.Environment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetEdges = `-- name: ListAssetEdges :many
SELECT id, from_logical_asset_id, to_logical_asset_id, edge_type
FROM serving_state.asset_edge
WHERE generation_id = $1::uuid
ORDER BY edge_type, from_logical_asset_id, to_logical_asset_id
`

type ListAssetEdgesRow struct {
	ID                 string `json:"id"`
	FromLogicalAssetID string `json:"from_logical_asset_id"`
	ToLogicalAssetID   string `json:"to_logical_asset_id"`
	EdgeType           string `json:"edge_type"`
}

func (q *Queries) ListAssetEdges(ctx context.Context, dollar_1 pgtype.UUID) ([]ListAssetEdgesRow, error) {
	rows, err := q.db.Query(ctx, listAssetEdges, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetEdgesRow{}
	for rows.Next() {
		var i ListAssetEdgesRow
		if err := rows.Scan(
			&i.ID,
			&i.FromLogicalAssetID,
			&i.ToLogicalAssetID,
			&i.EdgeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssets = `-- name: ListAssets :many
SELECT snapshot_id, logical_asset_id, asset_type, asset_key,
       parent_logical_asset_id, title, description, source_file,
       payload_schema, payload_json::text, content_hash
FROM serving_state.asset
WHERE generation_id = $1::uuid
ORDER BY asset_type, asset_key
`

type ListAssetsRow struct {
	SnapshotID           string `json:"snapshot_id"`
	LogicalAssetID       string `json:"logical_asset_id"`
	AssetType            string `json:"asset_type"`
	AssetKey             string `json:"asset_key"`
	ParentLogicalAssetID string `json:"parent_logical_asset_id"`
	Title                string `json:"title"`
	Description          string `json:"description"`
	SourceFile           string `json:"source_file"`
	PayloadSchema        string `json:"payload_schema"`
	PayloadJson          string `json:"payload_json"`
	ContentHash          string `json:"content_hash"`
}

func (q *Queries) ListAssets(ctx context.Context, dollar_1 pgtype.UUID) ([]ListAssetsRow, error) {
	rows, err := q.db.Query(ctx, listAssets, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetsRow{}
	for rows.Next() {
		var i ListAssetsRow
		if err := rows.Scan(
			&i.SnapshotID,
			&i.LogicalAssetID,
			&i.AssetType,
			&i.AssetKey,
			&i.ParentLogicalAssetID,
			&i.Title,
			&i.Description,
			&i.SourceFile,
			&i.PayloadSchema,
			&i.PayloadJson,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readerLease = `-- name: ReaderLease :one
SELECT generation_id::text, ducklake_snapshot_id
FROM serving_state.reader_lease
WHERE lease_id = $1 AND released_at IS NULL AND expires_at > clock_timestamp()
`

type ReaderLeaseRow struct {
	GenerationID       string `json:"generation_id"`
	DucklakeSnapshotID int64  `json:"ducklake_snapshot_id"`
}

func (q *Queries) ReaderLease(ctx context.Context, leaseID string) (ReaderLeaseRow, error) {
	row := q.db.QueryRow(ctx, readerLease, leaseID)
	var i ReaderLeaseRow
	err := row.Scan(&i.GenerationID, &i.DucklakeSnapshotID)
	return i, err
}

const referencedSnapshots = `-- name: ReferencedSnapshots :many
SELECT DISTINCT s.ducklake_snapshot_id
FROM delivery.delivery_generation g
JOIN delivery.delivery_snapshot_seal s ON s.seal_id = g.snapshot_seal_id
JOIN delivery.delivery_active_pointer ap ON ap.generation_id = g.generation_id
JOIN delivery.delivery_target t ON t.target_id = g.target_id
WHERE t.environment = $1 AND s.ducklake_snapshot_id > 0
ORDER BY s.ducklake_snapshot_id
`

func (q *Queries) ReferencedSnapshots(ctx context.Context, environment string) ([]int64, error) {
	rows, err := q.db.Query(ctx, referencedSnapshots, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var ducklake_snapshot_id int64
		if err := rows.Scan(&ducklake_snapshot_id); err != nil {
			return nil, err
		}
		items = append(items, ducklake_snapshot_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseExpiredLeases = `-- name: ReleaseExpiredLeases :execrows
UPDATE serving_state.reader_lease l
SET released_at = clock_timestamp()
FROM delivery.delivery_generation g
JOIN delivery.delivery_target t ON t.target_id = g.target_id
WHERE g.generation_id = l.generation_id AND t.environment = $1
  AND l.released_at IS NULL AND l.expires_at <= clock_timestamp()
`

func (q *Queries) ReleaseExpiredLeases(ctx context.Context, environment string) (int64, error) {
	result, err := q.db.Exec(ctx, releaseExpiredLeases, environment)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseReaderLease = `-- name: ReleaseReaderLease :execrows
UPDATE serving_state.reader_lease
SET released_at = clock_timestamp()
WHERE lease_id = $1 AND released_at IS NULL
`

func (q *Queries) ReleaseReaderLease(ctx context.Context, leaseID string) (int64, error) {
	result, err := q.db.Exec(ctx, releaseReaderLease, leaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
