package main

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestSourceCategorySeparatesAuthoredProductionAndTestFiles(t *testing.T) {
	tests := map[string]string{
		"internal/app/server.go":                   "go-production",
		"internal/app/server_test.go":              "go-test",
		"web/components/app/app-shell.ts":          "typescript-production",
		"web/components/app/app-shell.dom.test.ts": "typescript-test",
		"scripts/browser.spec.mjs":                 "typescript-test",
		"web/generated/signals.ts":                 "",
		"pkg/apigen/typespec/dist/on-emit.js":      "",
		"desktop/vendor/compatibility.cjs":         "",
		"web/contracts.d.ts":                       "",
	}
	for path, want := range tests {
		t.Run(path, func(t *testing.T) {
			if got := sourceCategory(path); got != want {
				t.Fatalf("sourceCategory(%q) = %q, want %q", path, got, want)
			}
		})
	}
}

func TestAnalyzeMeasuresHotspotAndSuppressionDebt(t *testing.T) {
	root := t.TempDir()
	files := map[string]string{
		"internal/example/service.go": strings.Join([]string{
			"package example", "func first() {}", "func second() {}", "/" + "/nolint:funlen", "",
		}, "\n"),
		"internal/example/service_test.go": "package example\n// " + "#" + "nosec test fixture\n",
		"web/example.ts":                   "// " + "@" + "ts-ignore reviewed fixture\nexport const value = 1\n",
		"web/generated/contracts.ts":       "// " + "@" + "ts-ignore generated\nexport const generated = true\n",
		"internal/example/generated.go":    "// Code generated by fixture. DO NOT EDIT.\npackage example\n/" + "/nolint\n",
	}
	paths := make([]string, 0, len(files))
	for path, body := range files {
		absolute := filepath.Join(root, filepath.FromSlash(path))
		if err := os.MkdirAll(filepath.Dir(absolute), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(absolute, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
		paths = append(paths, path)
	}
	policy := testBudget()
	result, err := analyze(root, paths, policy)
	if err != nil {
		t.Fatal(err)
	}
	production := result.Categories["go-production"]
	if production.Files != 1 || production.FilesOverLimit != 1 || production.ExcessLines != 1 || production.LargestFile != 4 {
		t.Fatalf("go production measurement = %#v", production)
	}
	if got := result.Suppressions; !reflect.DeepEqual(got, map[string]int{"nolint": 1, "nosec": 1, "ts-ignore": 1}) {
		t.Fatalf("suppressions = %#v", got)
	}
}

func TestAnalyzeIgnoresTrackedFilesDeletedFromTheWorkingTree(t *testing.T) {
	result, err := analyze(t.TempDir(), []string{"internal/example/deleted.go"}, testBudget())
	if err != nil {
		t.Fatal(err)
	}
	if got := result.Categories["go-production"].Files; got != 0 {
		t.Fatalf("deleted production files = %d, want 0", got)
	}
}

func TestEvaluateRejectsEveryBudgetDimension(t *testing.T) {
	policy := testBudget()
	policy.Categories["go-production"] = categoryBudget{
		LineLimit: 3, MaxFilesOverLimit: 1, MaxExcessLines: 2, MaxLargestFile: 5,
	}
	policy.Suppressions["nolint"] = suppressionBudget{Marker: "//nolint", MaxOccurrences: 1}
	result := report{
		Categories: map[string]categoryResult{
			"go-production": {FilesOverLimit: 2, ExcessLines: 3, LargestFile: 6},
		},
		Suppressions: map[string]int{"nolint": 2},
	}
	problems := strings.Join(evaluate(policy, result), "\n")
	for _, want := range []string{"files over", "excess lines", "largest file", "nolint occurrences"} {
		if !strings.Contains(problems, want) {
			t.Fatalf("problems %q do not contain %q", problems, want)
		}
	}
}

func TestRatchetTightensButRequiresExplicitIncrease(t *testing.T) {
	policy := testBudget()
	policy.Categories["go-production"] = categoryBudget{
		LineLimit: 100, MaxFilesOverLimit: 4, MaxExcessLines: 80, MaxLargestFile: 240,
	}
	policy.Suppressions["nolint"] = suppressionBudget{Marker: "//nolint", MaxOccurrences: 3}
	result := report{
		Categories: map[string]categoryResult{
			"go-production": {FilesOverLimit: 3, ExcessLines: 60, LargestFile: 220},
		},
		Suppressions: map[string]int{"nolint": 2},
	}
	updated, increases := ratchet(policy, result, false)
	if len(increases) != 0 {
		t.Fatalf("unexpected increases: %v", increases)
	}
	if got := updated.Categories["go-production"]; got.MaxFilesOverLimit != 3 || got.MaxExcessLines != 60 || got.MaxLargestFile != 220 {
		t.Fatalf("tightened category = %#v", got)
	}
	if updated.Suppressions["nolint"].MaxOccurrences != 2 {
		t.Fatalf("tightened suppression = %#v", updated.Suppressions["nolint"])
	}

	result.Categories["go-production"] = categoryResult{FilesOverLimit: 5, ExcessLines: 100, LargestFile: 260}
	result.Suppressions["nolint"] = 4
	unchanged, increases := ratchet(policy, result, false)
	if !reflect.DeepEqual(increases, []string{"go-production", "nolint"}) {
		t.Fatalf("increases = %v", increases)
	}
	if !reflect.DeepEqual(unchanged, policy) {
		t.Fatalf("policy changed without approval: %#v", unchanged)
	}
}

func TestLineCountHandlesEmptyAndUnterminatedFiles(t *testing.T) {
	for body, want := range map[string]int{"": 0, "one": 1, "one\n": 1, "one\ntwo": 2} {
		if got := lineCount([]byte(body)); got != want {
			t.Fatalf("lineCount(%q) = %d, want %d", body, got, want)
		}
	}
}

func testBudget() budget {
	return budget{
		Version: currentVersion,
		Categories: map[string]categoryBudget{
			"go-production":         {LineLimit: 3},
			"go-test":               {LineLimit: 3},
			"typescript-production": {LineLimit: 3},
			"typescript-test":       {LineLimit: 3},
		},
		Suppressions: map[string]suppressionBudget{
			"nolint":    {Marker: "/" + "/nolint"},
			"nosec":     {Marker: "#" + "nosec"},
			"ts-ignore": {Marker: "@" + "ts-ignore"},
		},
	}
}
func TestGeneratedSourceRequiresAHeaderComment(t *testing.T) {
	generatedNotice := "Code " + "generated by fixture. DO " + "NOT EDIT."
	if !generatedSource("internal/example/generated.go", []byte("// "+generatedNotice+"\npackage example\n")) {
		t.Fatal("leading generated notice was not detected")
	}
	authoredFixture := []byte("package example\nconst notice = `" + generatedNotice + "`\n")
	if generatedSource("internal/example/service_test.go", authoredFixture) {
		t.Fatal("generated notice inside an authored string excluded the whole file")
	}
}

func TestCommentMarkerCountIgnoresStringLiterals(t *testing.T) {
	marker := "/" + "/nolint"
	body := []byte(strings.Join([]string{
		"package example",
		"const documented = `" + marker + "`",
		"func example() {} " + marker + ":funlen",
		"/* reviewed " + marker + ":gocyclo */",
	}, "\n"))
	if got := commentMarkerCount(body, marker); got != 2 {
		t.Fatalf("comment marker count = %d, want 2", got)
	}
}
