// Package failurets emits operation-owned TypeScript failure unions from APIGen IR.
package failurets

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/Yacobolo/toolbelt/apigen/ir"
)

// Emit renders transport-neutral TypeScript failure contracts for commands.
func Emit(doc ir.Document) ([]byte, error) {
	if err := ir.Validate(doc); err != nil {
		return nil, fmt.Errorf("validate ir document: %w", err)
	}
	normalized := doc
	if err := ir.Normalize(&normalized); err != nil {
		return nil, fmt.Errorf("normalize ir document: %w", err)
	}
	endpoints := append([]ir.Endpoint(nil), normalized.Endpoints...)
	sort.Slice(endpoints, func(left, right int) bool { return endpoints[left].OperationID < endpoints[right].OperationID })

	var b strings.Builder
	b.WriteString("// Code generated by apigen TypeScript failure emitter. DO NOT EDIT.\n\n")
	b.WriteString("export interface APIGenProblemFieldError { field: string; code: string; detail: string }\n\n")
	b.WriteString("export interface APIGenProblemDetails {\n")
	b.WriteString("  type: string; title: string; status: number; detail: string; instance: string;\n")
	b.WriteString("  code: string; requestId: string; errors: APIGenProblemFieldError[];\n")
	b.WriteString("}\n\n")

	for _, endpoint := range endpoints {
		if endpoint.Command == nil {
			continue
		}
		emitOperation(&b, endpoint)
	}
	return []byte(b.String()), nil
}

func emitOperation(b *strings.Builder, endpoint ir.Endpoint) {
	name := exportedName(endpoint.OperationID)
	typeName := name + "Failure"
	if len(endpoint.Command.Failures) == 0 {
		b.WriteString("export type " + typeName + " = never;\n\n")
		return
	}
	b.WriteString("export type " + typeName + " =\n")
	for index, failure := range endpoint.Command.Failures {
		prefix := "  | "
		if index == 0 {
			prefix = "  "
		}
		b.WriteString(prefix + "{ kind: " + strconv.Quote(failure.Kind) + "; code: " + strconv.Quote(failure.Code) + "; status: " + strconv.Itoa(failure.StatusCode) + "; problem: APIGenProblemDetails }\n")
	}
	b.WriteString(";\n\n")
	b.WriteString("export function match" + typeName + "<T>(failure: " + typeName + ", handlers: {\n")
	for _, failure := range endpoint.Command.Failures {
		b.WriteString("  " + strconv.Quote(failure.Kind) + ": (problem: APIGenProblemDetails) => T;\n")
	}
	b.WriteString("}): T {\n")
	b.WriteString("  switch (failure.kind) {\n")
	for _, failure := range endpoint.Command.Failures {
		b.WriteString("    case " + strconv.Quote(failure.Kind) + ": return handlers[" + strconv.Quote(failure.Kind) + "](failure.problem);\n")
	}
	b.WriteString("  }\n")
	b.WriteString("}\n\n")
}

func exportedName(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool { return r == '-' || r == '_' || r == '.' || r == ' ' })
	if len(parts) == 0 {
		return "Operation"
	}
	for index, part := range parts {
		if part == "" {
			continue
		}
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		parts[index] = string(runes)
	}
	return strings.Join(parts, "")
}
