-- Static PostgreSQL queries for the DuckLake control capability.
-- Generated by sqlc; keep lifecycle decisions in repository.go/upgrade.go.

-- name: DatabaseClock :one
SELECT clock_timestamp()::timestamptz AS now;

-- name: AssertAttemptAdmissionFence :exec
SELECT ducklake.assert_attempt_admission_fence(sqlc.arg(physical_pool_id),sqlc.arg(catalog_id));

-- name: ReadDatabaseIdentity :one
SELECT current_database()::text AS database_name, current_user::text AS user_name, session_user::text AS session_user_name;

-- name: GetMetadataSchemaOwner :one
SELECT current_user::text AS current_user, r.rolname AS owner
FROM pg_namespace n JOIN pg_roles r ON r.oid=n.nspowner
WHERE n.nspname=sqlc.arg(metadata_schema);

-- name: InsertCatalogIdentity :exec
INSERT INTO ducklake.catalog_identity
(physical_pool_id,catalog_database,catalog_id,catalog_uuid,metadata_schema)
VALUES (sqlc.arg(physical_pool_id),sqlc.arg(catalog_database),sqlc.arg(catalog_id),sqlc.arg(catalog_uuid),sqlc.arg(metadata_schema)) ON CONFLICT (physical_pool_id) DO NOTHING;

-- name: GetCatalogIdentity :one
SELECT physical_pool_id,catalog_database,catalog_id,catalog_uuid,metadata_schema,created_at
FROM ducklake.catalog_identity WHERE physical_pool_id=$1;

-- name: AdmitSnapshotRetentionFromSeal :one
SELECT (r).physical_pool_id::text AS physical_pool_id,
       (r).catalog_id::text AS catalog_id,
       (r).snapshot_id::bigint AS snapshot_id,
       (r).retention_state::text AS retention_state
FROM ducklake.admit_snapshot_retention_from_seal(sqlc.arg(seal_id)::uuid) AS r;

-- name: GetSnapshotRetentionSealIdentity :one
SELECT physical_pool_id,catalog_id,ducklake_snapshot_id
FROM delivery.delivery_snapshot_seal
WHERE seal_id=sqlc.arg(seal_id)::uuid;

-- name: LockSnapshotRetentionCleanup :one
SELECT state,cleanup_owner_id,cleanup_fencing_epoch,cleanup_lease_expires_at
FROM ducklake.snapshot_retention WHERE physical_pool_id=sqlc.arg(physical_pool_id) AND catalog_id=sqlc.arg(catalog_id) AND snapshot_id=sqlc.arg(snapshot_id) FOR UPDATE;

-- name: LockSnapshotRetentionQuarantine :one
SELECT state,cleanup_owner_id,cleanup_fencing_epoch,cleanup_lease_expires_at,quarantine_evidence
FROM ducklake.snapshot_retention WHERE physical_pool_id=sqlc.arg(physical_pool_id) AND catalog_id=sqlc.arg(catalog_id) AND snapshot_id=sqlc.arg(snapshot_id) FOR UPDATE;

-- name: LockSnapshotRetentionComplete :one
SELECT state,cleanup_owner_id,cleanup_fencing_epoch,cleanup_lease_expires_at,cleanup_evidence
FROM ducklake.snapshot_retention WHERE physical_pool_id=sqlc.arg(physical_pool_id) AND catalog_id=sqlc.arg(catalog_id) AND snapshot_id=sqlc.arg(snapshot_id) FOR UPDATE;

-- name: InsertSourceObservationCapture :exec
INSERT INTO ducklake.source_observation_capture
 (attempt_id,commit_marker,observation_envelope,content_digest,captured_at)
 VALUES (sqlc.arg(attempt_id),sqlc.arg(commit_marker)::jsonb,sqlc.arg(observation_envelope)::jsonb,sqlc.arg(content_digest),sqlc.arg(captured_at))
 ON CONFLICT (attempt_id) DO NOTHING;

-- name: GetSourceObservationCapture :one
SELECT attempt_id::text,commit_marker,observation_envelope,content_digest,captured_at,created_at
FROM ducklake.source_observation_capture WHERE attempt_id=sqlc.arg(attempt_id);

-- name: LockDeliveryAttemptForObservation :one
SELECT attempt_id::text,request_digest,plan_digest,physical_pool_id,catalog_id,fencing_epoch,state
FROM delivery.delivery_build_attempt
WHERE attempt_id=sqlc.arg(attempt_id)::uuid
FOR UPDATE;

-- name: GetDeliveryAttemptForObservation :one
SELECT attempt_id::text,request_digest,plan_digest,physical_pool_id,catalog_id,fencing_epoch,state
FROM delivery.delivery_build_attempt
WHERE attempt_id=sqlc.arg(attempt_id)::uuid;

-- name: InsertMarkerQuarantine :exec
INSERT INTO ducklake.marker_quarantine
 (physical_pool_id,catalog_id,attempt_id,request_digest,plan_digest,reason,evidence,observed_marker_digest,observed_snapshot_ids)
 VALUES (sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(attempt_id),sqlc.arg(request_digest),sqlc.arg(plan_digest),sqlc.arg(reason)::ducklake.marker_quarantine_reason,sqlc.arg(evidence)::jsonb,sqlc.arg(observed_marker_digest),sqlc.arg(observed_snapshot_ids)::bigint[])
 ON CONFLICT (physical_pool_id,catalog_id,attempt_id) DO NOTHING;

-- name: GetMarkerQuarantine :one
SELECT physical_pool_id,catalog_id,attempt_id::text,request_digest,plan_digest,reason::text,evidence,observed_marker_digest,observed_snapshot_ids,created_at
FROM ducklake.marker_quarantine
WHERE physical_pool_id=sqlc.arg(physical_pool_id) AND catalog_id=sqlc.arg(catalog_id) AND attempt_id=sqlc.arg(attempt_id);

-- name: HasMarkerQuarantineForPool :one
SELECT EXISTS (SELECT 1 FROM ducklake.marker_quarantine WHERE physical_pool_id=sqlc.arg(physical_pool_id));

-- name: AcquireMarkerQuarantineScopeLock :exec
SELECT pg_advisory_xact_lock(
  hashtextextended('leapview:ducklake:marker-quarantine:' || sqlc.arg(physical_pool_id)::text, 0)
);

-- name: ExpireSnapshotUnderMaintenanceFence :execresult
SELECT ducklake.expire_snapshot_under_maintenance_fence(sqlc.arg(expired_at),sqlc.arg(evidence)::jsonb,sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(snapshot_id),sqlc.arg(maintenance_id),sqlc.arg(maintenance_owner_id),sqlc.arg(maintenance_fencing_epoch));

-- name: ClaimSnapshotCleanupUnderMaintenanceFence :one
SELECT ducklake.claim_snapshot_cleanup_under_maintenance_fence(sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(snapshot_id),sqlc.arg(cleanup_owner_id),sqlc.arg(cleanup_lease_expires_at),sqlc.arg(maintenance_id),sqlc.arg(maintenance_owner_id),sqlc.arg(maintenance_fencing_epoch));

-- name: QuarantineSnapshotUnderMaintenanceFence :execresult
SELECT ducklake.quarantine_snapshot_under_maintenance_fence(sqlc.arg(quarantine_evidence)::jsonb,sqlc.arg(quarantined_at),sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(snapshot_id),sqlc.arg(cleanup_owner_id),sqlc.arg(cleanup_fencing_epoch),sqlc.arg(maintenance_id),sqlc.arg(maintenance_owner_id),sqlc.arg(maintenance_fencing_epoch));

-- name: CompleteSnapshotCleanupUnderMaintenanceFence :execresult
SELECT ducklake.complete_snapshot_cleanup_under_maintenance_fence(sqlc.arg(cleanup_evidence)::jsonb,sqlc.arg(cleanup_completed_at),sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(snapshot_id),sqlc.arg(cleanup_owner_id),sqlc.arg(cleanup_fencing_epoch),sqlc.arg(maintenance_id),sqlc.arg(maintenance_owner_id),sqlc.arg(maintenance_fencing_epoch));

-- name: ExpireSnapshotsUnderMaintenanceFence :exec
SELECT ducklake.expire_snapshots_under_maintenance_fence(sqlc.arg(snapshot_ids)::bigint[],sqlc.arg(expired_at),sqlc.arg(items)::jsonb,sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(maintenance_id),sqlc.arg(maintenance_owner_id),sqlc.arg(maintenance_fencing_epoch));

-- name: ReconcileRetentionMaintenanceSnapshots :exec
SELECT ducklake.reconcile_retention_maintenance_snapshots(sqlc.arg(items)::jsonb,sqlc.arg(maintenance_id),sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(owner_id),sqlc.arg(fencing_epoch));

-- name: QuarantineSnapshotsUnderMaintenanceFence :exec
SELECT ducklake.quarantine_snapshots_under_maintenance_fence(sqlc.arg(snapshot_ids)::bigint[],sqlc.arg(items)::jsonb,sqlc.arg(cleanup_lease_expires_at),sqlc.arg(quarantined_at),sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(maintenance_id),sqlc.arg(maintenance_owner_id),sqlc.arg(maintenance_fencing_epoch));

-- name: CompleteSnapshotsCleanupUnderMaintenanceFence :exec
SELECT ducklake.complete_snapshots_cleanup_under_maintenance_fence(sqlc.arg(snapshot_ids)::bigint[],sqlc.arg(items)::jsonb,sqlc.arg(cleanup_lease_expires_at),sqlc.arg(cleanup_completed_at),sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(maintenance_id),sqlc.arg(maintenance_owner_id),sqlc.arg(maintenance_fencing_epoch));

-- name: ListSnapshotOrphanCleanupEligible :many
SELECT orphan_id::text,physical_pool_id,catalog_id,snapshot_id,state,cleanup_owner_id,cleanup_fencing_epoch,cleanup_lease_expires_at,evidence,discovered_at,cleanup_not_before,resolved_at
FROM ducklake.snapshot_orphan
WHERE physical_pool_id=sqlc.arg(physical_pool_id)
  AND catalog_id=sqlc.arg(catalog_id)
  AND state='quarantined'
  AND cleanup_not_before <= clock_timestamp()
  AND snapshot_id > sqlc.arg(cursor_snapshot_id)
ORDER BY snapshot_id
LIMIT sqlc.arg(page_limit);

-- name: BeginSnapshotOrphanScan :exec
SELECT ducklake.begin_snapshot_orphan_scan(sqlc.arg(scan_id),sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(owner_id),sqlc.arg(fencing_epoch),sqlc.arg(page_size),sqlc.arg(grace_micros),sqlc.arg(request_evidence)::jsonb);

-- name: RecordSnapshotOrphanScanPage :one
SELECT (r).next_cursor::bigint AS next_cursor, (r).orphan_count::integer AS orphan_count
FROM ducklake.record_snapshot_orphan_scan_page(sqlc.arg(scan_id),sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(owner_id),sqlc.arg(fencing_epoch),sqlc.arg(page_number),sqlc.arg(cursor_before),sqlc.arg(cursor_after),sqlc.arg(snapshot_ids)::bigint[],sqlc.arg(page_digest),sqlc.arg(evidence)::jsonb,sqlc.arg(terminal)) AS r;

-- name: ComputeSnapshotOrphanScanPageDigest :one
SELECT ('sha256:' || pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(sqlc.arg(evidence)::jsonb::text, 'UTF8')), 'hex'))::text;

-- name: CompleteSnapshotOrphanScan :exec
SELECT ducklake.complete_snapshot_orphan_scan(sqlc.arg(scan_id),sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(owner_id),sqlc.arg(fencing_epoch),sqlc.arg(completion_evidence)::jsonb);

-- name: PruneSnapshotOrphanScanPages :one
SELECT ducklake.prune_snapshot_orphan_scan_pages(sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(owner_id),sqlc.arg(fencing_epoch),sqlc.arg(min_age_micros),sqlc.arg(max_scans));

-- name: GetSnapshotOrphanScan :one
SELECT scan_id::text,physical_pool_id,catalog_id,owner_id,fencing_epoch,page_size,grace_micros,cursor_snapshot_id,pages_scanned,snapshots_scanned,orphans_recorded,state,request_evidence,completion_evidence,cleanup_not_before,pruned_at,pruned_page_count,pruned_page_digest,started_at,updated_at,completed_at
FROM ducklake.snapshot_orphan_scan WHERE scan_id=sqlc.arg(scan_id);

-- name: ClaimSnapshotOrphanCleanupUnderPoolFence :one
SELECT ducklake.claim_snapshot_orphan_cleanup_under_pool_fence(sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(snapshot_id),sqlc.arg(owner_id),sqlc.arg(cleanup_lease_expires_at),sqlc.arg(fence_owner_id),sqlc.arg(fencing_epoch));

-- name: CompleteSnapshotOrphanCleanupUnderPoolFence :exec
SELECT ducklake.complete_snapshot_orphan_cleanup_under_pool_fence(sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(snapshot_id),sqlc.arg(owner_id),sqlc.arg(fencing_epoch),sqlc.arg(evidence)::jsonb,sqlc.arg(fence_owner_id),sqlc.arg(pool_fencing_epoch));

-- name: GetSnapshotRetention :one
SELECT physical_pool_id,catalog_id,snapshot_id,state,protected_until,retired_at,expired_at,cleanup_owner_id,cleanup_fencing_epoch,cleanup_lease_expires_at,quarantined_at,cleanup_completed_at,quarantine_evidence,cleanup_evidence,evidence,created_at
FROM ducklake.snapshot_retention WHERE physical_pool_id=$1 AND catalog_id=$2 AND snapshot_id=$3;

-- name: ListRetainedSnapshotIDs :many
SELECT snapshot_id FROM ducklake.snapshot_retention WHERE physical_pool_id=$1 AND catalog_id=$2 AND state IN ('live','retiring') ORDER BY snapshot_id;

-- name: ListRetentionDryRunSnapshots :many
-- Dry-run uses the same canonical reachability set as the fenced claim path,
-- but does not mutate retention rows.  Delivery roots are mapped through
-- their immutable snapshot seals; roots without a seal are intentionally not
-- assigned a physical identity here.
SELECT r.snapshot_id,r.state
FROM ducklake.snapshot_retention r
WHERE r.physical_pool_id=sqlc.arg(physical_pool_id)
  AND r.catalog_id=sqlc.arg(catalog_id)
  AND r.state IN ('retiring','expired')
  AND r.retention_claim_id IS NULL
  AND NOT EXISTS (
      SELECT 1
        FROM delivery.delivery_retention_root root
        JOIN delivery.delivery_snapshot_seal seal ON seal.seal_id = root.snapshot_seal_id
       WHERE seal.physical_pool_id=r.physical_pool_id
         AND seal.catalog_id=r.catalog_id
         AND seal.ducklake_snapshot_id=r.snapshot_id
         AND root.state IN ('live','retiring'))
  AND NOT EXISTS (
      SELECT 1
        FROM serving_state.reader_lease lease
        JOIN delivery.delivery_generation g ON g.generation_id = lease.generation_id
        JOIN delivery.delivery_snapshot_seal seal ON seal.seal_id = g.snapshot_seal_id
       WHERE seal.physical_pool_id=r.physical_pool_id
         AND seal.catalog_id=r.catalog_id
         AND seal.ducklake_snapshot_id=r.snapshot_id
         AND lease.released_at IS NULL)
ORDER BY r.snapshot_id
LIMIT sqlc.arg(claim_limit)
FOR UPDATE OF r;

-- Freeze the exact expiry set under the active maintenance fence. A claimed
-- row transitions to expiring and therefore cannot acquire new roots/leases.
-- This statement is used in the same transaction that records operation
-- children and their set digest.
-- name: ClaimRetentionSnapshots :many
SELECT snapshot_id::bigint AS snapshot_id
FROM unnest(ducklake.claim_retention_snapshots(sqlc.arg(maintenance_id),sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(owner_id),sqlc.arg(fencing_epoch),sqlc.arg(claim_limit))) AS snapshot_id;

-- name: AcquirePoolMaintenanceFence :one
SELECT (f).physical_pool_id::text AS physical_pool_id,(f).catalog_id::text AS catalog_id,(f).owner_id::text AS owner_id,(f).fencing_epoch::bigint AS fencing_epoch,(f).lease_expires_at::timestamptz AS lease_expires_at
FROM ducklake.acquire_pool_maintenance_fence(sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(owner_id),sqlc.arg(lease_expires_at)) AS f;

-- name: ReleasePoolMaintenanceFence :exec
SELECT ducklake.release_pool_maintenance_fence(sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(owner_id),sqlc.arg(fencing_epoch));

-- name: RenewPoolMaintenanceFence :exec
SELECT ducklake.renew_pool_maintenance_fence(sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(owner_id),sqlc.arg(fencing_epoch),sqlc.arg(lease_expires_at));

-- name: GetPoolMaintenanceFence :one
SELECT owner_id,fencing_epoch,lease_expires_at
FROM ducklake.pool_maintenance_fence
WHERE physical_pool_id=sqlc.arg(physical_pool_id) AND catalog_id=sqlc.arg(catalog_id);

-- name: InsertRetentionMaintenance :exec
SELECT ducklake.begin_retention_maintenance(sqlc.arg(maintenance_id),sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(owner_id),sqlc.arg(fencing_epoch),sqlc.arg(dry_run),sqlc.arg(file_grace_micros),sqlc.arg(snapshot_set_digest),sqlc.arg(phase_evidence)::jsonb);

-- name: GetRetentionMaintenance :one
SELECT maintenance_id::text,physical_pool_id,catalog_id,owner_id,fencing_epoch,state,phase,dry_run,file_grace_micros,snapshot_set_digest,phase_evidence,started_at,updated_at,completed_at
FROM ducklake.retention_maintenance WHERE maintenance_id=sqlc.arg(maintenance_id);

-- name: UpdateRetentionMaintenance :execresult
SELECT ducklake.update_retention_maintenance(sqlc.arg(maintenance_id),sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(owner_id),sqlc.arg(fencing_epoch),sqlc.arg(state),sqlc.arg(phase),sqlc.arg(dry_run),sqlc.arg(file_grace_micros),sqlc.arg(snapshot_set_digest),sqlc.arg(phase_evidence)::jsonb,sqlc.arg(completed_at));

-- name: InsertRetentionMaintenanceSnapshot :exec
SELECT ducklake.insert_retention_maintenance_snapshot(sqlc.arg(maintenance_id),sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(snapshot_id),sqlc.arg(owner_id),sqlc.arg(fencing_epoch));

-- name: InsertRetentionMaintenanceSnapshots :exec
SELECT ducklake.insert_retention_maintenance_snapshots(sqlc.arg(maintenance_id),sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(snapshot_ids)::bigint[],sqlc.arg(owner_id),sqlc.arg(fencing_epoch));

-- name: GetRetentionMaintenanceSnapshot :one
SELECT maintenance_id::text,physical_pool_id,catalog_id,snapshot_id,phase,expiry_evidence,quarantine_evidence,cleanup_evidence,created_at,updated_at
FROM ducklake.retention_maintenance_snapshot
WHERE maintenance_id=sqlc.arg(maintenance_id) AND physical_pool_id=sqlc.arg(physical_pool_id) AND catalog_id=sqlc.arg(catalog_id) AND snapshot_id=sqlc.arg(snapshot_id);

-- name: UpdateRetentionMaintenanceSnapshot :execresult
SELECT ducklake.update_retention_maintenance_snapshot(sqlc.arg(maintenance_id),sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(snapshot_id),sqlc.arg(owner_id),sqlc.arg(fencing_epoch),sqlc.arg(phase),sqlc.arg(expiry_evidence)::jsonb,sqlc.arg(quarantine_evidence)::jsonb,sqlc.arg(cleanup_evidence)::jsonb);

-- name: ListRetentionMaintenanceSnapshots :many
SELECT maintenance_id::text,physical_pool_id,catalog_id,snapshot_id,phase,expiry_evidence,quarantine_evidence,cleanup_evidence,created_at,updated_at
FROM ducklake.retention_maintenance_snapshot
WHERE maintenance_id=sqlc.arg(maintenance_id)
ORDER BY physical_pool_id,catalog_id,snapshot_id;

-- name: AcquireMigrationFence :one
SELECT (f).scope::text AS scope,(f).physical_pool_id::text AS physical_pool_id,(f).owner_id::text AS owner_id,(f).fencing_epoch::bigint AS fencing_epoch,(f).lease_expires_at::timestamptz AS lease_expires_at
FROM ducklake.acquire_migration_fence(sqlc.arg(scope),sqlc.arg(physical_pool_id),sqlc.arg(owner_id),sqlc.arg(lease_expires_at)) AS f;

-- name: ReleaseMigrationFence :exec
SELECT ducklake.release_migration_fence(sqlc.arg(scope),sqlc.arg(physical_pool_id),sqlc.arg(owner_id),sqlc.arg(fencing_epoch));

-- name: RenewMigrationFence :exec
SELECT ducklake.renew_migration_fence(sqlc.arg(scope),sqlc.arg(physical_pool_id),sqlc.arg(owner_id),sqlc.arg(fencing_epoch),sqlc.arg(lease_expires_at));

-- name: GetPoolMigrationFence :one
SELECT owner_id,fencing_epoch,lease_expires_at FROM ducklake.migration_fence WHERE scope='pool' AND physical_pool_id=sqlc.arg(physical_pool_id);

-- name: GetGlobalMigrationFence :one
SELECT owner_id,fencing_epoch,lease_expires_at FROM ducklake.migration_fence WHERE scope='global' AND physical_pool_id='';

-- name: RegisterCatalogRuntimeCompatibility :exec
SELECT ducklake.register_catalog_runtime_compatibility(sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(duckdb_runtime),sqlc.arg(ducklake_extension),sqlc.arg(catalog_format),sqlc.arg(compatibility_digest),sqlc.arg(catalog_schema_version),sqlc.arg(owner_id),sqlc.arg(pool_fencing_epoch),sqlc.arg(global_fencing_epoch));

-- name: InsertInitialCatalogRuntimeCompatibility :exec
INSERT INTO ducklake.catalog_runtime_compatibility
(physical_pool_id,catalog_id,duckdb_runtime,ducklake_extension,catalog_format,compatibility_digest,catalog_schema_version)
VALUES (sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(duckdb_runtime),sqlc.arg(ducklake_extension),sqlc.arg(catalog_format),sqlc.arg(compatibility_digest),sqlc.arg(catalog_schema_version))
ON CONFLICT (physical_pool_id) DO NOTHING;

-- name: GetCatalogRuntimeCompatibility :one
SELECT physical_pool_id,catalog_id,duckdb_runtime,ducklake_extension,catalog_format,compatibility_digest,catalog_schema_version,CAST(COALESCE(current_migration_id::text,'') AS text) AS current_migration_id,updated_at
FROM ducklake.catalog_runtime_compatibility WHERE physical_pool_id=sqlc.arg(physical_pool_id);

-- name: BeginCatalogMigration :exec
SELECT ducklake.begin_catalog_migration(sqlc.arg(migration_id),sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(owner_id),sqlc.arg(pool_fencing_epoch),sqlc.arg(global_fencing_epoch),sqlc.arg(current_duckdb_runtime),sqlc.arg(current_ducklake_extension),sqlc.arg(current_catalog_format),sqlc.arg(current_compatibility_digest),sqlc.arg(current_catalog_schema_version),sqlc.arg(target_duckdb_runtime),sqlc.arg(target_ducklake_extension),sqlc.arg(target_catalog_format),sqlc.arg(target_compatibility_digest),sqlc.arg(target_catalog_schema_version),sqlc.arg(begin_evidence)::jsonb);

-- name: CompleteCatalogMigration :exec
SELECT ducklake.complete_catalog_migration(sqlc.arg(migration_id),sqlc.arg(owner_id),sqlc.arg(pool_fencing_epoch),sqlc.arg(global_fencing_epoch),sqlc.arg(evidence)::jsonb);

-- name: FailCatalogMigration :exec
SELECT ducklake.fail_catalog_migration(sqlc.arg(migration_id),sqlc.arg(owner_id),sqlc.arg(pool_fencing_epoch),sqlc.arg(global_fencing_epoch),sqlc.arg(failure_evidence)::jsonb,sqlc.arg(recovery_decision),sqlc.arg(decision_evidence)::jsonb);

-- name: GetCatalogMigration :one
SELECT migration_id::text,physical_pool_id,catalog_id,owner_id,fencing_epoch,global_fencing_epoch,current_duckdb_runtime,current_ducklake_extension,current_catalog_format,current_compatibility_digest,current_catalog_schema_version,target_duckdb_runtime,target_ducklake_extension,target_catalog_format,target_compatibility_digest,target_catalog_schema_version,state,started_at,terminal_at,begin_evidence,completion_evidence,failure_evidence,recovery_decision,decision_evidence
FROM ducklake.catalog_migration WHERE migration_id=sqlc.arg(migration_id);

-- name: LockCatalogMigration :one
SELECT migration_id::text FROM ducklake.catalog_migration WHERE migration_id=sqlc.arg(migration_id);

-- name: RecordSnapshotRequalification :exec
SELECT ducklake.record_snapshot_requalification(sqlc.arg(qualification_id),sqlc.arg(physical_pool_id),sqlc.arg(catalog_id),sqlc.arg(snapshot_id),sqlc.arg(migration_id),sqlc.arg(duckdb_runtime),sqlc.arg(ducklake_extension),sqlc.arg(catalog_format),sqlc.arg(compatibility_digest),sqlc.arg(catalog_schema_version),sqlc.arg(status),sqlc.arg(evidence)::jsonb,sqlc.arg(qualified_at),sqlc.arg(owner_id),sqlc.arg(pool_fencing_epoch),sqlc.arg(global_fencing_epoch));

-- name: GetSnapshotRequalification :one
SELECT qualification_id::text,physical_pool_id,catalog_id,snapshot_id,migration_id::text,duckdb_runtime,ducklake_extension,catalog_format,compatibility_digest,catalog_schema_version,status,evidence,qualified_at
FROM ducklake.snapshot_requalification WHERE qualification_id=sqlc.arg(qualification_id);

-- name: CountRunningMigrations :one
SELECT count(*) FROM ducklake.catalog_migration WHERE physical_pool_id=sqlc.arg(physical_pool_id) AND catalog_id=sqlc.arg(catalog_id) AND state='running';

-- name: CountActiveMigrationFences :one
SELECT count(*) FROM ducklake.migration_fence WHERE (scope='global' OR (scope='pool' AND physical_pool_id=sqlc.arg(physical_pool_id))) AND owner_id IS NOT NULL AND lease_expires_at > sqlc.arg(lease_expires_at);

-- name: CountMissingSnapshotQualifications :one
-- Snapshots admitted after the exact completed epoch carry native
-- qualification evidence and do not incur requalification debt.
SELECT count(*) FROM ducklake.snapshot_retention r
WHERE r.physical_pool_id=sqlc.arg(physical_pool_id) AND r.catalog_id=sqlc.arg(catalog_id) AND r.state IN ('live','retiring')
AND NOT EXISTS (
 SELECT 1
 FROM ducklake.catalog_migration m
 WHERE m.migration_id=sqlc.arg(migration_id)
   AND m.physical_pool_id=r.physical_pool_id AND m.catalog_id=r.catalog_id
   AND m.state='completed' AND m.terminal_at IS NOT NULL
   AND m.target_compatibility_digest=sqlc.arg(compatibility_digest) AND m.target_catalog_schema_version=sqlc.arg(catalog_schema_version) AND m.target_duckdb_runtime=sqlc.arg(duckdb_runtime)
   AND m.target_ducklake_extension=sqlc.arg(ducklake_extension) AND m.target_catalog_format=sqlc.arg(catalog_format)
   AND (
      r.created_at > m.terminal_at
      OR EXISTS (
         SELECT 1 FROM ducklake.snapshot_requalification q
         WHERE q.physical_pool_id=r.physical_pool_id AND q.catalog_id=r.catalog_id AND q.snapshot_id=r.snapshot_id
           AND q.migration_id=m.migration_id AND q.status='qualified' AND q.compatibility_digest=sqlc.arg(compatibility_digest) AND q.catalog_schema_version=sqlc.arg(catalog_schema_version)
           AND q.duckdb_runtime=sqlc.arg(duckdb_runtime) AND q.ducklake_extension=sqlc.arg(ducklake_extension) AND q.catalog_format=sqlc.arg(catalog_format)
      )
   )
);
