package main

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

func writeFixture(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for name, body := range files {
		path := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func TestAuditRequiresAccountingForRawSQL(t *testing.T) {
	root := writeFixture(t, map[string]string{
		"internal/example/postgres/repository.go": `package postgres
import "context"
func f(tx interface{ QueryRow(context.Context, string, ...any) any }) {
	tx.QueryRow(
		context.Background(),
		"SELECT 1",
	)
}
`,
	})
	result := audit(root)
	if len(result.Errors) == 0 || !strings.Contains(result.Errors[0].Error(), "unclassified PostgreSQL QueryRow") {
		t.Fatalf("expected unclassified call, got %#v", result.Errors)
	}
}

func TestAuditAcceptsAdjacentMarkerAndExcludesTestsAndGenerated(t *testing.T) {
	root := writeFixture(t, map[string]string{
		"internal/example/postgres/repository.go": `package postgres
import "context"
func f(tx interface{ Exec(context.Context, string, ...any) any }) {
	// sqlc-exception: analyzer-incompatible. protocol control
	tx.Exec(context.Background(), ` + "`SET LOCAL ROLE owner`" + `)
}
`,
		"internal/example/postgres/internal/db/generated.go": `// Code generated by sqlc. DO NOT EDIT.
package db
`,
		"internal/example/postgres/repository_test.go": `package postgres
func test() {}
`,
	})
	result := audit(root)
	if len(result.Errors) != 0 {
		t.Fatalf("expected clean audit, got %#v", result.Errors)
	}
	if len(result.Findings) != 1 || result.Findings[0].Source != "marker" {
		t.Fatalf("unexpected findings: %#v", result.Findings)
	}
}

func TestAuditRejectsForgedGeneratedHeaderOutsideOutputPackage(t *testing.T) {
	root := writeFixture(t, map[string]string{
		"internal/example/postgres/repository.go": `// Code generated by sqlc. DO NOT EDIT.
package postgres
import "context"
func f(tx interface{ Exec(context.Context, string, ...any) any }) {
	tx.Exec(context.Background(), "SELECT 1")
}
`,
	})
	result := audit(root)
	if len(result.Errors) == 0 {
		t.Fatal("forged generated header unexpectedly bypassed the raw-SQL audit")
	}
}

func TestAuditRejectsBuriedGeneratedHeaderInsideOutputPackage(t *testing.T) {
	root := writeFixture(t, map[string]string{
		"internal/example/postgres/internal/db/handwritten.go": `package db
// Code generated by sqlc. DO NOT EDIT.
import "context"
func f(tx interface{ Exec(context.Context, string, ...any) any }) {
	tx.Exec(context.Background(), "SELECT 1")
}
`,
	})
	result := audit(root)
	if len(result.Errors) == 0 {
		t.Fatal("buried generated header unexpectedly bypassed the raw-SQL audit")
	}
}

func TestAuditExceptionInventoryLineIsExact(t *testing.T) {
	body := `package postgres
import "context"
func ApplySchema(tx interface{ Exec(context.Context, string, ...any) any }, query string) {
	tx.Exec(context.Background(), query)
}
`
	root := writeFixture(t, map[string]string{
		"internal/example/postgres/repository.go": body,
	})
	result := audit(root)
	if len(result.Findings) != 1 {
		t.Fatalf("expected one finding, got %#v", result.Findings)
	}
	finding := result.Findings[0]
	inventory := "entries:\n  - file: internal/example/postgres/repository.go\n    line: " + strconv.Itoa(finding.Line+1) + "\n    function: ApplySchema\n    method: Exec\n    fingerprint: " + finding.Fingerprint + "\n    class: schema-ddl\n    rationale: Test DDL boundary.\n    verification: Test coverage.\n"
	if err := os.WriteFile(filepath.Join(root, "internal/example/postgres/sqlc_exceptions.yaml"), []byte(inventory), 0o644); err != nil {
		t.Fatal(err)
	}
	result = audit(root)
	if len(result.Errors) < 2 {
		t.Fatalf("expected wrong-line inventory to be unclassified and stale, got %#v", result.Errors)
	}
}

func TestAuditAcceptsExactExceptionInventoryLine(t *testing.T) {
	body := `package postgres
import "context"
func ApplySchema(tx interface{ Exec(context.Context, string, ...any) any }, query string) {
	tx.Exec(context.Background(), query)
}
`
	root := writeFixture(t, map[string]string{
		"internal/example/postgres/repository.go": body,
	})
	result := audit(root)
	if len(result.Findings) != 1 {
		t.Fatalf("expected one finding, got %#v", result.Findings)
	}
	finding := result.Findings[0]
	inventory := "entries:\n  - file: internal/example/postgres/repository.go\n    line: " + strconv.Itoa(finding.Line) + "\n    function: ApplySchema\n    method: Exec\n    fingerprint: " + finding.Fingerprint + "\n    class: schema-ddl\n    rationale: Test DDL boundary.\n    verification: Test coverage.\n"
	if err := os.WriteFile(filepath.Join(root, "internal/example/postgres/sqlc_exceptions.yaml"), []byte(inventory), 0o644); err != nil {
		t.Fatal(err)
	}
	result = audit(root)
	if len(result.Errors) != 0 {
		t.Fatalf("exact inventory was not accepted: %#v", result.Errors)
	}
	if len(result.Findings) != 1 || result.Findings[0].Source != "inventory" {
		t.Fatalf("unexpected findings: %#v", result.Findings)
	}
}

func TestAuditDoesNotSkipIdentifierSQLExpressions(t *testing.T) {
	root := writeFixture(t, map[string]string{
		"internal/example/postgres/repository.go": `package postgres
import "context"
func f(tx interface{ Exec(context.Context, string, ...any) any }, query string) {
	tx.Exec(context.Background(), query)
}
`,
	})
	result := audit(root)
	if len(result.Errors) == 0 || !strings.Contains(result.Errors[0].Error(), "unclassified dynamic PostgreSQL Exec") {
		t.Fatalf("expected dynamic call error, got %#v", result.Errors)
	}
}

func TestAuditMarkerMustBeAdjacent(t *testing.T) {
	root := writeFixture(t, map[string]string{
		"internal/example/postgres/repository.go": `package postgres
import "context"
func f(tx interface{ Exec(context.Context, string, ...any) any }) {
	// sqlc-exception: analyzer-incompatible




	tx.Exec(context.Background(), "SELECT 1")
}
`,
	})
	result := audit(root)
	unclassified := false
	for _, err := range result.Errors {
		unclassified = unclassified || strings.Contains(err.Error(), "unclassified PostgreSQL Exec")
	}
	if !unclassified {
		t.Fatalf("expected distant marker rejection, got %#v", result.Errors)
	}
}

func TestAuditMarkerRejectsDistantCommentContinuation(t *testing.T) {
	root := writeFixture(t, map[string]string{
		"internal/example/postgres/repository.go": `package postgres
import "context"
func f(tx interface{ Exec(context.Context, string, ...any) any }) {
	// sqlc-exception: analyzer-incompatible
	// still documenting the statement
	// still documenting the statement
	// still documenting the statement
	// still documenting the statement
	tx.Exec(context.Background(), "SELECT 1")
}
`,
	})
	result := audit(root)
	unclassified := false
	for _, err := range result.Errors {
		unclassified = unclassified || strings.Contains(err.Error(), "unclassified PostgreSQL Exec")
	}
	if !unclassified {
		t.Fatalf("expected comment continuation beyond three lines to be rejected, got %#v", result.Errors)
	}
}

func TestAuditFingerprintsResolvedConstants(t *testing.T) {
	body := `package postgres
import "context"
const (
	base = "SELECT "
	statement = base + "1"
)
func f(tx interface{ Exec(context.Context, string, ...any) any }) {
	tx.Exec(context.Background(), statement)
}
`
	root := writeFixture(t, map[string]string{
		"internal/example/postgres/repository.go": body,
	})
	result := audit(root)
	if len(result.Findings) != 1 || !result.Findings[0].Static {
		t.Fatalf("expected resolved constant to be static, got findings=%#v errors=%#v", result.Findings, result.Errors)
	}
	if len(result.Errors) == 0 || !strings.Contains(result.Errors[0].Error(), "unclassified PostgreSQL Exec") {
		t.Fatalf("expected resolved constant SQL to remain rejected, got %#v", result.Errors)
	}
	changed := strings.Replace(body, `statement = base + "1"`, `statement = base + "2"`, 1)
	if err := os.WriteFile(filepath.Join(root, "internal/example/postgres/repository.go"), []byte(changed), 0o644); err != nil {
		t.Fatal(err)
	}
	result = audit(root)
	if len(result.Errors) == 0 || !strings.Contains(result.Errors[0].Error(), "unclassified PostgreSQL Exec") {
		t.Fatalf("expected changed constant to remain rejected, got %#v", result.Errors)
	}
}

func TestAuditRejectsUnknownMarkerClass(t *testing.T) {
	root := writeFixture(t, map[string]string{
		"internal/example/postgres/repository.go": `package postgres
import "context"
func f(tx interface{ Exec(context.Context, string, ...any) any }) {
	// sqlc-exception: made-up
	tx.Exec(context.Background(), "SELECT 1")
}
`,
	})
	result := audit(root)
	unknown := false
	for _, err := range result.Errors {
		unknown = unknown || strings.Contains(err.Error(), "unknown sqlc exception class")
	}
	if !unknown {
		t.Fatalf("expected unknown class error, got %#v", result.Errors)
	}
}

func TestAuditRejectsStaticDynamicShapeException(t *testing.T) {
	root := writeFixture(t, map[string]string{
		"internal/example/postgres/repository.go": `package postgres
import "context"
func f(tx interface{ QueryRow(context.Context, string, ...any) any }) {
	// sqlc-exception: dynamic-result-shape
	tx.QueryRow(context.Background(), "SELECT 1")
}
`,
	})
	result := audit(root)
	found := false
	for _, err := range result.Errors {
		found = found || strings.Contains(err.Error(), "cannot classify a resolved static SQL expression")
	}
	if !found {
		t.Fatalf("expected static dynamic-shape rejection, got %#v", result.Errors)
	}
}

func TestAuditRequiresSchemaDDLExec(t *testing.T) {
	root := writeFixture(t, map[string]string{
		"internal/example/postgres/repository.go": `package postgres
import "context"
func f(tx interface{ Query(context.Context, string, ...any) any }) {
	// sqlc-exception: schema-ddl
	tx.Query(context.Background(), "SELECT 1")
}
`,
	})
	result := audit(root)
	found := false
	for _, err := range result.Errors {
		found = found || strings.Contains(err.Error(), "requires an Exec call")
	}
	if !found {
		t.Fatalf("expected schema DDL method rejection, got %#v", result.Errors)
	}
}

func TestAuditRejectsSchemaDDLMarkerOnStaticSelect(t *testing.T) {
	root := writeFixture(t, map[string]string{
		"internal/example/postgres/repository.go": `package postgres
import "context"
func f(tx interface{ Exec(context.Context, string, ...any) any }) {
	// sqlc-exception: schema-ddl
	tx.Exec(context.Background(), "SELECT 1")
}
`,
	})
	result := audit(root)
	found := false
	for _, err := range result.Errors {
		found = found || strings.Contains(err.Error(), "cannot classify a static non-DDL statement")
	}
	if !found {
		t.Fatalf("expected static SELECT schema-DDL rejection, got %#v", result.Errors)
	}
}
