// Code generated by apigen data-contract Go emitter. DO NOT EDIT.
package desktopdiscovery

type DesktopAuthenticationMode string

const (
	DesktopAuthenticationModeBrowserSession    DesktopAuthenticationMode = "browser-session"
	DesktopAuthenticationModeSystemBrowserPkce DesktopAuthenticationMode = "system-browser-pkce"
)

type DesktopCapability string

const (
	DesktopCapabilityRemoteWeb DesktopCapability = "remote-web"
)

type DesktopDiscoveryDocument struct {
	SchemaVersion       int32                       `json:"schemaVersion" yaml:"schemaVersion"`
	CanonicalOrigin     string                      `json:"canonicalOrigin" yaml:"canonicalOrigin"`
	InstanceID          string                      `json:"instanceId" yaml:"instanceId"`
	DisplayName         string                      `json:"displayName" yaml:"displayName"`
	ServerVersion       string                      `json:"serverVersion" yaml:"serverVersion"`
	DesktopProtocolMin  int32                       `json:"desktopProtocolMin" yaml:"desktopProtocolMin"`
	DesktopProtocolMax  int32                       `json:"desktopProtocolMax" yaml:"desktopProtocolMax"`
	AuthenticationModes []DesktopAuthenticationMode `json:"authenticationModes" yaml:"authenticationModes"`
	Capabilities        []DesktopCapability         `json:"capabilities" yaml:"capabilities"`
}

type DesktopDiscoveryFailure struct {
	SchemaVersion int32                       `json:"schemaVersion" yaml:"schemaVersion"`
	Kind          DesktopDiscoveryFailureKind `json:"kind" yaml:"kind"`
}

type DesktopDiscoveryFailureKind string

const (
	DesktopDiscoveryFailureKindInvalidOrigin              DesktopDiscoveryFailureKind = "invalid_origin"
	DesktopDiscoveryFailureKindTls                        DesktopDiscoveryFailureKind = "tls"
	DesktopDiscoveryFailureKindProxy                      DesktopDiscoveryFailureKind = "proxy"
	DesktopDiscoveryFailureKindDns                        DesktopDiscoveryFailureKind = "dns"
	DesktopDiscoveryFailureKindNetwork                    DesktopDiscoveryFailureKind = "network"
	DesktopDiscoveryFailureKindTimeout                    DesktopDiscoveryFailureKind = "timeout"
	DesktopDiscoveryFailureKindRedirect                   DesktopDiscoveryFailureKind = "redirect"
	DesktopDiscoveryFailureKindHttp                       DesktopDiscoveryFailureKind = "http"
	DesktopDiscoveryFailureKindMalformedResponse          DesktopDiscoveryFailureKind = "malformed_response"
	DesktopDiscoveryFailureKindCanonicalOriginMismatch    DesktopDiscoveryFailureKind = "canonical_origin_mismatch"
	DesktopDiscoveryFailureKindInstanceIdentityMismatch   DesktopDiscoveryFailureKind = "instance_identity_mismatch"
	DesktopDiscoveryFailureKindSchemaIncompatible         DesktopDiscoveryFailureKind = "schema_incompatible"
	DesktopDiscoveryFailureKindProtocolIncompatible       DesktopDiscoveryFailureKind = "protocol_incompatible"
	DesktopDiscoveryFailureKindAuthenticationIncompatible DesktopDiscoveryFailureKind = "authentication_incompatible"
	DesktopDiscoveryFailureKindCapabilityIncompatible     DesktopDiscoveryFailureKind = "capability_incompatible"
)
