package resultidentity

import "fmt"

// PublicationIdentity is the primitive-only projection of an immutable
// contract publication. It intentionally does not retain project graph or
// contract-publication types so the analytics identity contract cannot become
// coupled to Project's publication authority.
//
// The fields are copied from the exact publication selected by the Project
// adapter. Digest is the publication's canonical-content digest; it is not a
// digest generated by this package.
type PublicationIdentity struct {
	InstanceID        string `json:"instanceId"`
	AuthoredID        string `json:"authoredId"`
	ResourceKind      string `json:"resourceKind"`
	Version           string `json:"version"`
	VersionBaseline   string `json:"versionBaseline"`
	ProjectionProfile string `json:"projectionProfile"`
	Digest            string `json:"digest"`
}

// SemanticPublicationIdentity is the descriptive name used by protected
// semantic consumers. It is an alias, not a second identity authority.
type SemanticPublicationIdentity = PublicationIdentity

// PolicyIdentity is the primitive-only summary of the policy evidence bound
// to one candidate publication. Classification values are strings here on
// purpose: contractversion owns their meaning and classification algorithm.
// The Project adapter validates the complete typed evidence before mapping it.
type PolicyIdentity struct {
	BaselineKind             string              `json:"baselineKind"`
	Baseline                 PublicationIdentity `json:"baseline"`
	Class                    string              `json:"class"`
	Compatibility            string              `json:"compatibility"`
	StructuralCompatibility  string              `json:"structuralCompatibility"`
	SemanticCompatibility    string              `json:"semanticCompatibility"`
	SecurityImpact           string              `json:"securityImpact"`
	RequiresMajor            bool                `json:"requiresMajor"`
	RequiresSecurityApproval bool                `json:"requiresSecurityApproval"`
	PolicyEvidenceDigest     string              `json:"policyEvidenceDigest"`
	ApprovalEvidenceDigest   string              `json:"approvalEvidenceDigest,omitempty"`
}

// SemanticPolicyIdentity is the descriptive name used by protected semantic
// consumers. It is an alias, not a second identity authority.
type SemanticPolicyIdentity = PolicyIdentity

// PublicationPolicyIdentity is the complete publication/policy binding for a
// protected result dependency. Candidate is deliberately retained exactly
// once here; Policy.Baseline is empty for genesis and exact for updates.
type PublicationPolicyIdentity struct {
	Candidate PublicationIdentity `json:"candidate"`
	Policy    PolicyIdentity      `json:"policy"`
}

// Validate checks the closed set of scalar publication and policy identity
// values. It does not classify contracts; that remains exclusively owned by
// contractversion and is checked by the Project adapter before construction.
func (identity PublicationIdentity) Validate() error {
	for _, field := range []struct {
		name  string
		value string
	}{
		{name: "instance ID", value: identity.InstanceID},
		{name: "authored ID", value: identity.AuthoredID},
		{name: "resource kind", value: identity.ResourceKind},
		{name: "version", value: identity.Version},
		{name: "version baseline", value: identity.VersionBaseline},
		{name: "projection profile", value: identity.ProjectionProfile},
	} {
		if err := validateOpaqueText(field.value); err != nil {
			return fmt.Errorf("%w: publication %s: %v", ErrInvalidDependency, field.name, err)
		}
	}
	switch identity.ResourceKind {
	case "source", "model", "semantic_model":
	default:
		return fmt.Errorf("%w: publication resource kind %q is unsupported", ErrInvalidDependency, identity.ResourceKind)
	}
	return validateDigest("publication digest", identity.Digest)
}

// Validate checks the policy summary without importing contractversion. The
// adapter has already checked aggregate consistency against exact canonical
// bytes; these scalar checks prevent a detached identity from carrying an
// indeterminate or impossible approval state.
func (identity PolicyIdentity) Validate() error {
	if identity.BaselineKind != "genesis" && identity.BaselineKind != "existing" {
		return fmt.Errorf("%w: policy baseline kind is required", ErrInvalidDependency)
	}
	if identity.BaselineKind == "genesis" {
		if identity.Baseline != (PublicationIdentity{}) {
			return fmt.Errorf("%w: genesis policy baseline must be empty", ErrInvalidDependency)
		}
	} else if err := identity.Baseline.Validate(); err != nil {
		return err
	}
	for _, field := range []struct {
		name  string
		value string
	}{
		{name: "classification", value: identity.Class},
		{name: "compatibility", value: identity.Compatibility},
		{name: "structural compatibility", value: identity.StructuralCompatibility},
		{name: "semantic compatibility", value: identity.SemanticCompatibility},
	} {
		switch field.name {
		case "classification":
			switch field.value {
			case "compatible", "warning", "breaking", "security-sensitive":
			default:
				return fmt.Errorf("%w: policy classification is indeterminate or unsupported", ErrInvalidDependency)
			}
		case "compatibility", "structural compatibility", "semantic compatibility":
			switch field.value {
			case "additive", "behavioral", "breaking":
			default:
				return fmt.Errorf("%w: policy %s is indeterminate or unsupported", ErrInvalidDependency, field.name)
			}
		default:
			return fmt.Errorf("%w: policy classification field is unsupported", ErrInvalidDependency)
		}
	}
	switch identity.SecurityImpact {
	case "none", "tightening", "widening":
	default:
		return fmt.Errorf("%w: policy security impact is indeterminate or unsupported", ErrInvalidDependency)
	}
	if identity.RequiresSecurityApproval != (identity.SecurityImpact == "widening") {
		return fmt.Errorf("%w: policy approval requirement is not bound to security widening", ErrInvalidDependency)
	}
	if err := validateDigest("policy evidence digest", identity.PolicyEvidenceDigest); err != nil {
		return err
	}
	if identity.ApprovalEvidenceDigest != "" {
		if !identity.RequiresSecurityApproval {
			return fmt.Errorf("%w: approval evidence is unexpected for a non-widening policy", ErrInvalidDependency)
		}
		if err := validateDigest("approval evidence digest", identity.ApprovalEvidenceDigest); err != nil {
			return err
		}
	} else if identity.RequiresSecurityApproval {
		return fmt.Errorf("%w: widening policy requires approval evidence", ErrInvalidDependency)
	}
	return nil
}

// Validate checks both halves of a protected publication/policy binding and
// rejects a policy candidate that is not exactly the selected publication.
func (identity PublicationPolicyIdentity) Validate() error {
	if err := identity.Candidate.Validate(); err != nil {
		return err
	}
	if err := identity.Policy.Validate(); err != nil {
		return err
	}
	if identity.Policy.BaselineKind == "existing" &&
		(identity.Policy.Baseline.InstanceID != identity.Candidate.InstanceID ||
			identity.Policy.Baseline.AuthoredID != identity.Candidate.AuthoredID ||
			identity.Policy.Baseline.ResourceKind != identity.Candidate.ResourceKind) {
		return fmt.Errorf("%w: policy baseline scope differs from candidate", ErrInvalidDependency)
	}
	return nil
}
