// Code generated by apigen data-contract Go emitter. DO NOT EDIT.
package signals

import (
	"bytes"
	"encoding/json"
	"fmt"
	visualizationir "github.com/flidai/leapview/internal/dashboard/visualization/ir"
)

type AgentContextSignal struct {
	Surface        string                         `json:"surface"`
	DashboardID    string                         `json:"dashboardId"`
	DashboardTitle string                         `json:"dashboardTitle"`
	PageID         string                         `json:"pageId"`
	PageTitle      string                         `json:"pageTitle"`
	ModelID        string                         `json:"modelId"`
	DatasetID      *string                        `json:"datasetId,omitempty"`
	Exploration    *DataExploreAgentContextSignal `json:"exploration,omitempty"`
	Generation     int64                          `json:"generation"`
	Filters        DashboardFilterState           `json:"filters"`
	ReferenceLimit int32                          `json:"referenceLimit"`
	References     []AgentReferenceSignal         `json:"references"`
}

type AgentReferenceKeySignal struct {
	Kind string `json:"kind"`
	ID   string `json:"id"`
}

type AgentReferenceLocationSignal struct {
	DashboardID   *string `json:"dashboardId,omitempty"`
	DashboardName *string `json:"dashboardName,omitempty"`
	PageID        *string `json:"pageId,omitempty"`
	PageName      *string `json:"pageName,omitempty"`
	Href          string  `json:"href"`
}

type AgentReferenceSearchSignal struct {
	Query     string                 `json:"query"`
	RequestID int64                  `json:"requestId"`
	Results   []AgentReferenceSignal `json:"results"`
}

type AgentReferenceSignal struct {
	Reference   AgentReferenceKeySignal        `json:"reference"`
	Name        string                         `json:"name"`
	Description *string                        `json:"description,omitempty"`
	VisualType  *string                        `json:"visualType,omitempty"`
	Hierarchy   []string                       `json:"hierarchy"`
	Href        string                         `json:"href"`
	Locations   []AgentReferenceLocationSignal `json:"locations"`
	Context     []string                       `json:"context"`
}

type AssetLineageEdgeSignal struct {
	ID     string  `json:"id"`
	Kind   string  `json:"kind"`
	Label  *string `json:"label,omitempty"`
	Source string  `json:"source"`
	Target string  `json:"target"`
}

type AssetLineageGraphSignal struct {
	Edges []AssetLineageEdgeSignal `json:"edges"`
	Nodes []AssetLineageNodeSignal `json:"nodes"`
}

type AssetLineageNodeSignal struct {
	ContainedCount         *int64  `json:"containedCount,omitempty"`
	ContainedSummary       *string `json:"containedSummary,omitempty"`
	Href                   *string `json:"href,omitempty"`
	ID                     string  `json:"id"`
	Kind                   string  `json:"kind"`
	Label                  string  `json:"label"`
	Meta                   *string `json:"meta,omitempty"`
	Rank                   int64   `json:"rank"`
	Selected               *bool   `json:"selected,omitempty"`
	Side                   string  `json:"side"`
	UsedByCount            *int64  `json:"usedByCount,omitempty"`
	UsesCount              *int64  `json:"usesCount,omitempty"`
	VisibleDownstreamCount *int64  `json:"visibleDownstreamCount,omitempty"`
	VisibleUpstreamCount   *int64  `json:"visibleUpstreamCount,omitempty"`
}

type CatalogDashboardSignal struct {
	AppearanceColor string           `json:"appearanceColor"`
	AppearanceIcon  string           `json:"appearanceIcon"`
	Description     *string          `json:"description,omitempty"`
	DashboardID     string           `json:"dashboardId"`
	Href            string           `json:"href"`
	ID              string           `json:"id"`
	LastRefreshedAt *string          `json:"lastRefreshedAt,omitempty"`
	PageCount       int64            `json:"pageCount"`
	Popularity      *PopularityLevel `json:"popularity,omitempty"`
	SemanticModel   *string          `json:"semanticModel,omitempty"`
	Tags            *[]string        `json:"tags,omitempty"`
	Title           string           `json:"title"`
}

type CatalogPageEnvelope struct {
	Chrome  ChromeSignal       `json:"chrome"`
	Page    CatalogPageSignal  `json:"page"`
	Runtime RouteRuntimeSignal `json:"runtime"`
	Status  DashboardStatus    `json:"status"`
}

type CatalogPageSignal struct {
	Dashboards  []CatalogDashboardSignal `json:"dashboards"`
	Description string                   `json:"description"`
	Kind        RouteKind                `json:"kind"`
	ListFilter  *string                  `json:"listFilter,omitempty"`
	ListQuery   *string                  `json:"listQuery,omitempty"`
	Title       string                   `json:"title"`
}

type ChatArtifactSignal struct {
	ID      string  `json:"id"`
	Type    string  `json:"type"`
	Summary *string `json:"summary,omitempty"`
}

type ChatConversationSummary struct {
	ArchivedAt      *string `json:"archivedAt,omitempty"`
	CreatedAt       string  `json:"createdAt"`
	ID              string  `json:"id"`
	LastMessageText *string `json:"lastMessageText,omitempty"`
	MessageCount    int64   `json:"messageCount"`
	PrincipalID     string  `json:"principalId"`
	Status          string  `json:"status"`
	Title           string  `json:"title"`
	TitlePending    *bool   `json:"titlePending,omitempty"`
	UpdatedAt       string  `json:"updatedAt"`
}

type ChatSignal struct {
	ActiveConversationID string                     `json:"activeConversationId"`
	Composer             ComposerSignal             `json:"composer"`
	Conversations        []ChatConversationSummary  `json:"conversations"`
	Status               ChatStatus                 `json:"status"`
	Transcript           []ChatTranscriptItemSignal `json:"transcript"`
}

type ChatStatus struct {
	Enabled bool    `json:"enabled"`
	Error   *string `json:"error,omitempty"`
	Running bool    `json:"running"`
}

type ChatTranscriptItemSignal struct {
	ArgumentsJSON  *string                 `json:"argumentsJson,omitempty"`
	Artifact       *ChatArtifactSignal     `json:"artifact,omitempty"`
	ConversationID *string                 `json:"conversationId,omitempty"`
	CreatedAt      *string                 `json:"createdAt,omitempty"`
	Error          *string                 `json:"error,omitempty"`
	ID             string                  `json:"id"`
	InputFormat    *string                 `json:"inputFormat,omitempty"`
	InputJSON      *string                 `json:"inputJson,omitempty"`
	Kind           string                  `json:"kind"`
	Markdown       *string                 `json:"markdown,omitempty"`
	Name           *string                 `json:"name,omitempty"`
	References     *[]AgentReferenceSignal `json:"references,omitempty"`
	ResultFormat   *string                 `json:"resultFormat,omitempty"`
	ResultJSON     *string                 `json:"resultJson,omitempty"`
	ResultSummary  *string                 `json:"resultSummary,omitempty"`
	RunID          *string                 `json:"runId,omitempty"`
	Status         *string                 `json:"status,omitempty"`
	Summary        *string                 `json:"summary,omitempty"`
	Text           *string                 `json:"text,omitempty"`
	Title          *string                 `json:"title,omitempty"`
	ToolCallID     *string                 `json:"toolCallId,omitempty"`
}

type ChromeSignal struct {
	Sidebar SidebarSignal `json:"sidebar"`
}

type ComposerSignal struct {
	Disabled    bool   `json:"disabled"`
	Placeholder string `json:"placeholder"`
	Value       string `json:"value"`
}

type ConnectionAdministrationCommandSignal struct {
	Action                string `json:"action"`
	AssetID               string `json:"assetId"`
	AuthenticationMode    string `json:"authenticationMode"`
	ConfirmationToken     string `json:"confirmationToken"`
	ConnectorKind         string `json:"connectorKind"`
	CredentialEnvironment string `json:"credentialEnvironment"`
	CredentialProjectID   string `json:"credentialProjectId"`
	Database              string `json:"database"`
	ExpectedRevision      int64  `json:"expectedRevision"`
	Host                  string `json:"host"`
	LogicalConnection     string `json:"logicalConnection"`
	ObjectScope           string `json:"objectScope"`
	Options               string `json:"options"`
	Port                  string `json:"port"`
	SecretKey             string `json:"secretKey"`
	SecretPath            string `json:"secretPath"`
	SourceIdentity        string `json:"sourceIdentity"`
	Surface               string `json:"surface"`
	TLSMode               string `json:"tlsMode"`
}

type ConnectionAdministrationSignal struct {
	Command ConnectionAdministrationCommandSignal `json:"command"`
	Status  ConnectionAdministrationStatusSignal  `json:"status"`
}

type ConnectionAdministrationStatusSignal struct {
	Error   string `json:"error"`
	Loading bool   `json:"loading"`
	Message string `json:"message"`
}

type ConnectionLifecycleActionSignal struct {
	Destructive bool   `json:"destructive"`
	ID          string `json:"id"`
	Label       string `json:"label"`
	Primary     bool   `json:"primary"`
}

type ConnectionLifecycleSignal struct {
	Actions               []ConnectionLifecycleActionSignal `json:"actions"`
	AssetID               string                            `json:"assetId"`
	AuthenticationMode    string                            `json:"authenticationMode"`
	BindingID             string                            `json:"bindingId"`
	CanManage             bool                              `json:"canManage"`
	CanTest               bool                              `json:"canTest"`
	ConnectorKind         string                            `json:"connectorKind"`
	CredentialEnvironment string                            `json:"credentialEnvironment"`
	CredentialProjectID   string                            `json:"credentialProjectId"`
	Database              string                            `json:"database"`
	DiagnosticCode        string                            `json:"diagnosticCode"`
	Enabled               bool                              `json:"enabled"`
	Exists                bool                              `json:"exists"`
	Health                string                            `json:"health"`
	Host                  string                            `json:"host"`
	LastValidatedAt       string                            `json:"lastValidatedAt"`
	LogicalConnection     string                            `json:"logicalConnection"`
	ObjectScope           string                            `json:"objectScope"`
	Options               string                            `json:"options"`
	Port                  string                            `json:"port"`
	Revision              int64                             `json:"revision"`
	SecretKey             string                            `json:"secretKey"`
	SecretPath            string                            `json:"secretPath"`
	SourceIdentity        string                            `json:"sourceIdentity"`
	State                 string                            `json:"state"`
	StatusLabel           string                            `json:"statusLabel"`
	TLSMode               string                            `json:"tlsMode"`
	Tone                  string                            `json:"tone"`
	ValidatedVersion      string                            `json:"validatedVersion"`
}

type ConnectionSummarySignal struct {
	CredentialStatus string                    `json:"credentialStatus"`
	Description      *string                   `json:"description,omitempty"`
	DetailHref       string                    `json:"detailHref"`
	ID               string                    `json:"id"`
	Kind             string                    `json:"kind"`
	Lifecycle        ConnectionLifecycleSignal `json:"lifecycle"`
	Scope            string                    `json:"scope"`
	SourceCount      int64                     `json:"sourceCount"`
	Title            string                    `json:"title"`
}

type ConnectionsPageEnvelope struct {
	Chrome          ChromeSignal                   `json:"chrome"`
	ConnectionAdmin ConnectionAdministrationSignal `json:"connectionAdmin"`
	Page            ConnectionsPageSignal          `json:"page"`
	Runtime         RouteRuntimeSignal             `json:"runtime"`
	Status          DashboardStatus                `json:"status"`
}

type ConnectionsPageSignal struct {
	Connections []ConnectionSummarySignal `json:"connections"`
	Description *string                   `json:"description,omitempty"`
	Environment *string                   `json:"environment,omitempty"`
	Kind        RouteKind                 `json:"kind"`
	Query       *string                   `json:"query,omitempty"`
	Title       string                    `json:"title"`
}

type DashboardAppliedFilterState struct {
	Expression         DashboardFilterExpression `json:"expression"`
	ResolvedExpression DashboardFilterExpression `json:"resolvedExpression"`
	EvaluatedAt        *string                   `json:"evaluatedAt,omitempty"`
}

type DashboardBooleanFilterValue struct {
	DashboardFilterValueBase
	Kind  string `json:"kind"`
	Value bool   `json:"value"`
}

type DashboardComparisonExpression struct {
	DashboardFilterExpressionBase
	Kind     string               `json:"kind"`
	Operator string               `json:"operator"`
	Value    DashboardFilterValue `json:"value"`
}

type DashboardDateFilterValue struct {
	DashboardFilterValueBase
	Kind  string `json:"kind"`
	Value string `json:"value"`
}

type DashboardDecimalFilterValue struct {
	DashboardFilterValueBase
	Kind  string `json:"kind"`
	Value string `json:"value"`
}

type DashboardFilterBound struct {
	Value     DashboardFilterValue `json:"value"`
	Inclusive bool                 `json:"inclusive"`
}

type DashboardFilterExpressionVariant interface {
	isDashboardFilterExpressionVariant()
}

type DashboardFilterExpression struct {
	Value DashboardFilterExpressionVariant
}

func (*DashboardComparisonExpression) isDashboardFilterExpressionVariant()     {}
func (*DashboardNullCheckExpression) isDashboardFilterExpressionVariant()      {}
func (*DashboardRangeExpression) isDashboardFilterExpressionVariant()          {}
func (*DashboardRelativePeriodExpression) isDashboardFilterExpressionVariant() {}
func (*DashboardSetExpression) isDashboardFilterExpressionVariant()            {}
func (*DashboardUnfilteredExpression) isDashboardFilterExpressionVariant()     {}

func (value DashboardFilterExpression) MarshalJSON() ([]byte, error) {
	switch variant := value.Value.(type) {
	case *DashboardComparisonExpression:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return json.Marshal(variant)
	case *DashboardNullCheckExpression:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return json.Marshal(variant)
	case *DashboardRangeExpression:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return json.Marshal(variant)
	case *DashboardRelativePeriodExpression:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return json.Marshal(variant)
	case *DashboardSetExpression:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return json.Marshal(variant)
	case *DashboardUnfilteredExpression:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return json.Marshal(variant)
	case nil:
		return nil, fmt.Errorf("DashboardFilterExpression variant is required")
	default:
		return nil, fmt.Errorf("unsupported DashboardFilterExpression variant %T", variant)
	}
}

func (value *DashboardFilterExpression) UnmarshalJSON(data []byte) error {
	if value == nil {
		return fmt.Errorf("cannot unmarshal DashboardFilterExpression into nil receiver")
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return fmt.Errorf("decode DashboardFilterExpression object: %w", err)
	}
	var tag struct {
		Value string `json:"kind"`
	}
	if err := json.Unmarshal(data, &tag); err != nil {
		return fmt.Errorf("decode DashboardFilterExpression discriminator: %w", err)
	}
	if tag.Value == "" {
		return fmt.Errorf("DashboardFilterExpression discriminator kind is required")
	}
	decode := func(dest any) error {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		return decoder.Decode(dest)
	}
	switch tag.Value {
	case "comparison":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: required property kind is missing", tag.Value)
		}
		if _, ok := fields["operator"]; !ok {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: required property operator is missing", tag.Value)
		}
		if _, ok := fields["value"]; !ok {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: required property value is missing", tag.Value)
		}
		var variant DashboardComparisonExpression
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "null_check":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: required property kind is missing", tag.Value)
		}
		if _, ok := fields["operator"]; !ok {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: required property operator is missing", tag.Value)
		}
		var variant DashboardNullCheckExpression
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "range":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: required property kind is missing", tag.Value)
		}
		var variant DashboardRangeExpression
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "relative_period":
		if _, ok := fields["anchor"]; !ok {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: required property anchor is missing", tag.Value)
		}
		if _, ok := fields["count"]; !ok {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: required property count is missing", tag.Value)
		}
		if _, ok := fields["direction"]; !ok {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: required property direction is missing", tag.Value)
		}
		if _, ok := fields["includeCurrent"]; !ok {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: required property includeCurrent is missing", tag.Value)
		}
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: required property kind is missing", tag.Value)
		}
		if _, ok := fields["unit"]; !ok {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: required property unit is missing", tag.Value)
		}
		var variant DashboardRelativePeriodExpression
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "set":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: required property kind is missing", tag.Value)
		}
		if _, ok := fields["operator"]; !ok {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: required property operator is missing", tag.Value)
		}
		if _, ok := fields["values"]; !ok {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: required property values is missing", tag.Value)
		}
		var variant DashboardSetExpression
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "unfiltered":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: required property kind is missing", tag.Value)
		}
		var variant DashboardUnfilteredExpression
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode DashboardFilterExpression variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	default:
		return fmt.Errorf("unknown DashboardFilterExpression discriminator %q", tag.Value)
	}
	return nil
}

type DashboardFilterExpressionVisitor interface {
	VisitDashboardComparisonExpression(*DashboardComparisonExpression) error
	VisitDashboardNullCheckExpression(*DashboardNullCheckExpression) error
	VisitDashboardRangeExpression(*DashboardRangeExpression) error
	VisitDashboardRelativePeriodExpression(*DashboardRelativePeriodExpression) error
	VisitDashboardSetExpression(*DashboardSetExpression) error
	VisitDashboardUnfilteredExpression(*DashboardUnfilteredExpression) error
}

func (value *DashboardFilterExpression) Visit(visitor DashboardFilterExpressionVisitor) error {
	if value == nil {
		return fmt.Errorf("cannot visit nil DashboardFilterExpression")
	}
	if visitor == nil {
		return fmt.Errorf("DashboardFilterExpression visitor is required")
	}
	switch variant := value.Value.(type) {
	case *DashboardComparisonExpression:
		if variant == nil {
			return fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return visitor.VisitDashboardComparisonExpression(variant)
	case *DashboardNullCheckExpression:
		if variant == nil {
			return fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return visitor.VisitDashboardNullCheckExpression(variant)
	case *DashboardRangeExpression:
		if variant == nil {
			return fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return visitor.VisitDashboardRangeExpression(variant)
	case *DashboardRelativePeriodExpression:
		if variant == nil {
			return fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return visitor.VisitDashboardRelativePeriodExpression(variant)
	case *DashboardSetExpression:
		if variant == nil {
			return fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return visitor.VisitDashboardSetExpression(variant)
	case *DashboardUnfilteredExpression:
		if variant == nil {
			return fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return visitor.VisitDashboardUnfilteredExpression(variant)
	case nil:
		return fmt.Errorf("DashboardFilterExpression variant is required")
	default:
		return fmt.Errorf("unsupported DashboardFilterExpression variant %T", variant)
	}
}

func (value *DashboardFilterExpression) Kind() (string, error) {
	if value == nil {
		return "", fmt.Errorf("cannot inspect nil DashboardFilterExpression")
	}
	switch variant := value.Value.(type) {
	case *DashboardComparisonExpression:
		if variant == nil {
			return "", fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return "comparison", nil
	case *DashboardNullCheckExpression:
		if variant == nil {
			return "", fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return "null_check", nil
	case *DashboardRangeExpression:
		if variant == nil {
			return "", fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return "range", nil
	case *DashboardRelativePeriodExpression:
		if variant == nil {
			return "", fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return "relative_period", nil
	case *DashboardSetExpression:
		if variant == nil {
			return "", fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return "set", nil
	case *DashboardUnfilteredExpression:
		if variant == nil {
			return "", fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return "unfiltered", nil
	case nil:
		return "", fmt.Errorf("DashboardFilterExpression variant is required")
	default:
		return "", fmt.Errorf("unsupported DashboardFilterExpression variant %T", variant)
	}
}

func (value *DashboardFilterExpression) Base() (*DashboardFilterExpressionBase, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot inspect nil DashboardFilterExpression")
	}
	switch variant := value.Value.(type) {
	case *DashboardComparisonExpression:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return &variant.DashboardFilterExpressionBase, nil
	case *DashboardNullCheckExpression:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return &variant.DashboardFilterExpressionBase, nil
	case *DashboardRangeExpression:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return &variant.DashboardFilterExpressionBase, nil
	case *DashboardRelativePeriodExpression:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return &variant.DashboardFilterExpressionBase, nil
	case *DashboardSetExpression:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return &variant.DashboardFilterExpressionBase, nil
	case *DashboardUnfilteredExpression:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterExpression variant is nil")
		}
		return &variant.DashboardFilterExpressionBase, nil
	case nil:
		return nil, fmt.Errorf("DashboardFilterExpression variant is required")
	default:
		return nil, fmt.Errorf("unsupported DashboardFilterExpression variant %T", variant)
	}
}

type DashboardFilterExpressionBase struct {
	Kind string `json:"kind"`
}

type DashboardFilterState struct {
	Revision         int64                                  `json:"revision"`
	AppliedControls  map[string]DashboardAppliedFilterState `json:"appliedControls"`
	DraftControls    map[string]DashboardFilterExpression   `json:"draftControls"`
	DirtyBindings    []string                               `json:"dirtyBindings"`
	DefaultsRevision string                                 `json:"defaultsRevision"`
}

type DashboardFilterValueVariant interface {
	isDashboardFilterValueVariant()
}

type DashboardFilterValue struct {
	Value DashboardFilterValueVariant
}

func (*DashboardBooleanFilterValue) isDashboardFilterValueVariant()   {}
func (*DashboardDateFilterValue) isDashboardFilterValueVariant()      {}
func (*DashboardDecimalFilterValue) isDashboardFilterValueVariant()   {}
func (*DashboardIntegerFilterValue) isDashboardFilterValueVariant()   {}
func (*DashboardStringFilterValue) isDashboardFilterValueVariant()    {}
func (*DashboardTimestampFilterValue) isDashboardFilterValueVariant() {}

func (value DashboardFilterValue) MarshalJSON() ([]byte, error) {
	switch variant := value.Value.(type) {
	case *DashboardBooleanFilterValue:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return json.Marshal(variant)
	case *DashboardDateFilterValue:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return json.Marshal(variant)
	case *DashboardDecimalFilterValue:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return json.Marshal(variant)
	case *DashboardIntegerFilterValue:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return json.Marshal(variant)
	case *DashboardStringFilterValue:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return json.Marshal(variant)
	case *DashboardTimestampFilterValue:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return json.Marshal(variant)
	case nil:
		return nil, fmt.Errorf("DashboardFilterValue variant is required")
	default:
		return nil, fmt.Errorf("unsupported DashboardFilterValue variant %T", variant)
	}
}

func (value *DashboardFilterValue) UnmarshalJSON(data []byte) error {
	if value == nil {
		return fmt.Errorf("cannot unmarshal DashboardFilterValue into nil receiver")
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return fmt.Errorf("decode DashboardFilterValue object: %w", err)
	}
	var tag struct {
		Value string `json:"kind"`
	}
	if err := json.Unmarshal(data, &tag); err != nil {
		return fmt.Errorf("decode DashboardFilterValue discriminator: %w", err)
	}
	if tag.Value == "" {
		return fmt.Errorf("DashboardFilterValue discriminator kind is required")
	}
	decode := func(dest any) error {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		return decoder.Decode(dest)
	}
	switch tag.Value {
	case "boolean":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode DashboardFilterValue variant %q: required property kind is missing", tag.Value)
		}
		if _, ok := fields["value"]; !ok {
			return fmt.Errorf("decode DashboardFilterValue variant %q: required property value is missing", tag.Value)
		}
		var variant DashboardBooleanFilterValue
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode DashboardFilterValue variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "date":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode DashboardFilterValue variant %q: required property kind is missing", tag.Value)
		}
		if _, ok := fields["value"]; !ok {
			return fmt.Errorf("decode DashboardFilterValue variant %q: required property value is missing", tag.Value)
		}
		var variant DashboardDateFilterValue
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode DashboardFilterValue variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "decimal":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode DashboardFilterValue variant %q: required property kind is missing", tag.Value)
		}
		if _, ok := fields["value"]; !ok {
			return fmt.Errorf("decode DashboardFilterValue variant %q: required property value is missing", tag.Value)
		}
		var variant DashboardDecimalFilterValue
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode DashboardFilterValue variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "integer":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode DashboardFilterValue variant %q: required property kind is missing", tag.Value)
		}
		if _, ok := fields["value"]; !ok {
			return fmt.Errorf("decode DashboardFilterValue variant %q: required property value is missing", tag.Value)
		}
		var variant DashboardIntegerFilterValue
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode DashboardFilterValue variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "string":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode DashboardFilterValue variant %q: required property kind is missing", tag.Value)
		}
		if _, ok := fields["value"]; !ok {
			return fmt.Errorf("decode DashboardFilterValue variant %q: required property value is missing", tag.Value)
		}
		var variant DashboardStringFilterValue
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode DashboardFilterValue variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "timestamp":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode DashboardFilterValue variant %q: required property kind is missing", tag.Value)
		}
		if _, ok := fields["value"]; !ok {
			return fmt.Errorf("decode DashboardFilterValue variant %q: required property value is missing", tag.Value)
		}
		var variant DashboardTimestampFilterValue
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode DashboardFilterValue variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	default:
		return fmt.Errorf("unknown DashboardFilterValue discriminator %q", tag.Value)
	}
	return nil
}

type DashboardFilterValueVisitor interface {
	VisitDashboardBooleanFilterValue(*DashboardBooleanFilterValue) error
	VisitDashboardDateFilterValue(*DashboardDateFilterValue) error
	VisitDashboardDecimalFilterValue(*DashboardDecimalFilterValue) error
	VisitDashboardIntegerFilterValue(*DashboardIntegerFilterValue) error
	VisitDashboardStringFilterValue(*DashboardStringFilterValue) error
	VisitDashboardTimestampFilterValue(*DashboardTimestampFilterValue) error
}

func (value *DashboardFilterValue) Visit(visitor DashboardFilterValueVisitor) error {
	if value == nil {
		return fmt.Errorf("cannot visit nil DashboardFilterValue")
	}
	if visitor == nil {
		return fmt.Errorf("DashboardFilterValue visitor is required")
	}
	switch variant := value.Value.(type) {
	case *DashboardBooleanFilterValue:
		if variant == nil {
			return fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return visitor.VisitDashboardBooleanFilterValue(variant)
	case *DashboardDateFilterValue:
		if variant == nil {
			return fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return visitor.VisitDashboardDateFilterValue(variant)
	case *DashboardDecimalFilterValue:
		if variant == nil {
			return fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return visitor.VisitDashboardDecimalFilterValue(variant)
	case *DashboardIntegerFilterValue:
		if variant == nil {
			return fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return visitor.VisitDashboardIntegerFilterValue(variant)
	case *DashboardStringFilterValue:
		if variant == nil {
			return fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return visitor.VisitDashboardStringFilterValue(variant)
	case *DashboardTimestampFilterValue:
		if variant == nil {
			return fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return visitor.VisitDashboardTimestampFilterValue(variant)
	case nil:
		return fmt.Errorf("DashboardFilterValue variant is required")
	default:
		return fmt.Errorf("unsupported DashboardFilterValue variant %T", variant)
	}
}

func (value *DashboardFilterValue) Kind() (string, error) {
	if value == nil {
		return "", fmt.Errorf("cannot inspect nil DashboardFilterValue")
	}
	switch variant := value.Value.(type) {
	case *DashboardBooleanFilterValue:
		if variant == nil {
			return "", fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return "boolean", nil
	case *DashboardDateFilterValue:
		if variant == nil {
			return "", fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return "date", nil
	case *DashboardDecimalFilterValue:
		if variant == nil {
			return "", fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return "decimal", nil
	case *DashboardIntegerFilterValue:
		if variant == nil {
			return "", fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return "integer", nil
	case *DashboardStringFilterValue:
		if variant == nil {
			return "", fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return "string", nil
	case *DashboardTimestampFilterValue:
		if variant == nil {
			return "", fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return "timestamp", nil
	case nil:
		return "", fmt.Errorf("DashboardFilterValue variant is required")
	default:
		return "", fmt.Errorf("unsupported DashboardFilterValue variant %T", variant)
	}
}

func (value *DashboardFilterValue) Base() (*DashboardFilterValueBase, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot inspect nil DashboardFilterValue")
	}
	switch variant := value.Value.(type) {
	case *DashboardBooleanFilterValue:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return &variant.DashboardFilterValueBase, nil
	case *DashboardDateFilterValue:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return &variant.DashboardFilterValueBase, nil
	case *DashboardDecimalFilterValue:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return &variant.DashboardFilterValueBase, nil
	case *DashboardIntegerFilterValue:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return &variant.DashboardFilterValueBase, nil
	case *DashboardStringFilterValue:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return &variant.DashboardFilterValueBase, nil
	case *DashboardTimestampFilterValue:
		if variant == nil {
			return nil, fmt.Errorf("DashboardFilterValue variant is nil")
		}
		return &variant.DashboardFilterValueBase, nil
	case nil:
		return nil, fmt.Errorf("DashboardFilterValue variant is required")
	default:
		return nil, fmt.Errorf("unsupported DashboardFilterValue variant %T", variant)
	}
}

type DashboardFilterValueBase struct {
	Kind string `json:"kind"`
}

type DashboardIntegerFilterValue struct {
	DashboardFilterValueBase
	Kind  string `json:"kind"`
	Value string `json:"value"`
}

type DashboardNullCheckExpression struct {
	DashboardFilterExpressionBase
	Kind     string `json:"kind"`
	Operator string `json:"operator"`
}

type DashboardRangeExpression struct {
	DashboardFilterExpressionBase
	Kind  string                `json:"kind"`
	Lower *DashboardFilterBound `json:"lower,omitempty"`
	Upper *DashboardFilterBound `json:"upper,omitempty"`
}

type DashboardRelativePeriodExpression struct {
	DashboardFilterExpressionBase
	Kind           string                `json:"kind"`
	Direction      string                `json:"direction"`
	Count          int32                 `json:"count"`
	Unit           string                `json:"unit"`
	IncludeCurrent bool                  `json:"includeCurrent"`
	Anchor         string                `json:"anchor"`
	AnchorValue    *DashboardFilterValue `json:"anchorValue,omitempty"`
}

type DashboardSetExpression struct {
	DashboardFilterExpressionBase
	Kind     string                 `json:"kind"`
	Operator string                 `json:"operator"`
	Values   []DashboardFilterValue `json:"values"`
}

type DashboardStatus struct {
	Error           string  `json:"error"`
	Generation      int64   `json:"generation"`
	LastUpdated     string  `json:"lastUpdated"`
	Loading         bool    `json:"loading"`
	ProgressPercent float64 `json:"progressPercent"`
	RefreshID       string  `json:"refreshId"`
	SetupRequired   bool    `json:"setupRequired"`
}

type DashboardStringFilterValue struct {
	DashboardFilterValueBase
	Kind  string `json:"kind"`
	Value string `json:"value"`
}

type DashboardTimestampFilterValue struct {
	DashboardFilterValueBase
	Kind  string `json:"kind"`
	Value string `json:"value"`
}

type DashboardUnfilteredExpression struct {
	DashboardFilterExpressionBase
	Kind string `json:"kind"`
}

type DataExploreAgentContextSignal struct {
	Dimensions []string                  `json:"dimensions"`
	Filters    []DataExploreFilterSignal `json:"filters"`
	Limit      int64                     `json:"limit"`
	Metrics    []string                  `json:"metrics"`
	Sort       []DataExploreSortSignal   `json:"sort"`
	Time       *DataExploreTimeSignal    `json:"time,omitempty"`
}

type DataExploreCommand struct {
	ColumnWidths *map[string]float64       `json:"columnWidths,omitempty"`
	DatasetID    *string                   `json:"datasetId,omitempty"`
	Dimensions   []string                  `json:"dimensions"`
	Filters      []DataExploreFilterSignal `json:"filters"`
	Limit        int64                     `json:"limit"`
	Metrics      []string                  `json:"metrics"`
	ModelID      *string                   `json:"modelId,omitempty"`
	RequestSeq   int64                     `json:"requestSeq"`
	ResetVersion int64                     `json:"resetVersion"`
	Sort         []DataExploreSortSignal   `json:"sort"`
	Time         *DataExploreTimeSignal    `json:"time,omitempty"`
}

type DataExploreDatasetSignal struct {
	Description *string `json:"description,omitempty"`
	FieldCount  int64   `json:"fieldCount"`
	Grain       *string `json:"grain,omitempty"`
	ID          string  `json:"id"`
	Title       string  `json:"title"`
}

type DataExploreFieldSignal struct {
	Compatible          bool      `json:"compatible"`
	CompatibilityReason *string   `json:"compatibilityReason,omitempty"`
	Description         *string   `json:"description,omitempty"`
	Dataset             *string   `json:"dataset,omitempty"`
	ID                  string    `json:"id"`
	Kind                string    `json:"kind"`
	Label               string    `json:"label"`
	ModelTable          string    `json:"modelTable"`
	RebaseDatasetID     *string   `json:"rebaseDatasetId,omitempty"`
	RelationshipPath    *[]string `json:"relationshipPath,omitempty"`
	Selected            bool      `json:"selected"`
	Type                *string   `json:"type,omitempty"`
}

type DataExploreFilterSignal struct {
	Dataset  *string  `json:"dataset,omitempty"`
	Field    string   `json:"field"`
	Operator string   `json:"operator"`
	Values   []string `json:"values"`
}

type DataExploreModelSignal struct {
	Datasets    []DataExploreDatasetSignal `json:"datasets"`
	Description *string                    `json:"description,omitempty"`
	ID          string                     `json:"id"`
	Title       string                     `json:"title"`
}

type DataExploreResultSignal struct {
	Columns      []DataPreviewColumnSignal `json:"columns"`
	DurationMS   int64                     `json:"durationMs"`
	Error        *string                   `json:"error,omitempty"`
	Plan         *string                   `json:"plan,omitempty"`
	RequestSeq   int64                     `json:"requestSeq"`
	Rows         []map[string]any          `json:"rows"`
	RowsReturned int64                     `json:"rowsReturned"`
	SQL          *string                   `json:"sql,omitempty"`
	Truncated    bool                      `json:"truncated"`
	Warnings     []string                  `json:"warnings"`
}

type DataExploreSignal struct {
	Command         DataExploreCommand         `json:"command"`
	Datasets        []DataExploreDatasetSignal `json:"datasets"`
	Fields          []DataExploreFieldSignal   `json:"fields"`
	Models          []DataExploreModelSignal   `json:"models"`
	Result          DataExploreResultSignal    `json:"result"`
	SelectedDataset *DataExploreDatasetSignal  `json:"selectedDataset,omitempty"`
	SelectedModel   *DataExploreModelSignal    `json:"selectedModel,omitempty"`
}

type DataExploreSortSignal struct {
	Direction string `json:"direction"`
	Field     string `json:"field"`
}

type DataExploreTimeSignal struct {
	Alias *string `json:"alias,omitempty"`
	Field string  `json:"field"`
	Grain string  `json:"grain"`
}

type DataExplorerCommand struct {
	Explore        *DataExploreCommand   `json:"explore,omitempty"`
	Mode           *string               `json:"mode,omitempty"`
	Block          *string               `json:"block,omitempty"`
	ColumnWidths   *map[string]float64   `json:"columnWidths,omitempty"`
	Count          int64                 `json:"count"`
	Limit          int64                 `json:"limit"`
	ObjectKey      *string               `json:"objectKey,omitempty"`
	Offset         int64                 `json:"offset"`
	RequestSeq     int64                 `json:"requestSeq"`
	ResetVersion   int64                 `json:"resetVersion"`
	Sort           DataPreviewSortSignal `json:"sort"`
	Start          int64                 `json:"start"`
	VisibleColumns *[]string             `json:"visibleColumns,omitempty"`
}

type DataExplorerContextSignal struct {
	Active       bool    `json:"active"`
	Environment  string  `json:"environment"`
	GenerationID string  `json:"generationId"`
	ObjectCount  int64   `json:"objectCount"`
	ProjectID    string  `json:"projectId"`
	ProjectTitle *string `json:"projectTitle,omitempty"`
}

type DataExplorerObjectSignal struct {
	AssetID       *string                    `json:"assetId,omitempty"`
	ColumnCount   int64                      `json:"columnCount"`
	Columns       *[]DataPreviewColumnSignal `json:"columns,omitempty"`
	Description   *string                    `json:"description,omitempty"`
	DetailHref    *string                    `json:"detailHref,omitempty"`
	Grain         *string                    `json:"grain,omitempty"`
	Key           string                     `json:"key"`
	Layer         string                     `json:"layer"`
	ModelID       *string                    `json:"modelId,omitempty"`
	RowCountLabel *string                    `json:"rowCountLabel,omitempty"`
	Source        *string                    `json:"source,omitempty"`
	Table         *string                    `json:"table,omitempty"`
	Title         string                     `json:"title"`
	ResourceID    string                     `json:"resourceId"`
}

type DataExplorerPageEnvelope struct {
	Agent                ChatSignal                                       `json:"agent"`
	AgentContext         AgentContextSignal                               `json:"agentContext"`
	AgentReferenceSearch AgentReferenceSearchSignal                       `json:"agentReferenceSearch"`
	AgentVisuals         map[string]visualizationir.VisualizationEnvelope `json:"agentVisuals"`
	Chrome               ChromeSignal                                     `json:"chrome"`
	DataExplorer         DataExplorerSignal                               `json:"dataExplorer"`
	Page                 DataExplorerPageSignal                           `json:"page"`
	Runtime              RouteRuntimeSignal                               `json:"runtime"`
	Status               DashboardStatus                                  `json:"status"`
}

type DataExplorerPageSignal struct {
	Description    *string                   `json:"description,omitempty"`
	Kind           RouteKind                 `json:"kind"`
	SelectedObject *string                   `json:"selectedObject,omitempty"`
	Tabs           []ResourceTabSignal       `json:"tabs"`
	Title          string                    `json:"title"`
	Context        DataExplorerContextSignal `json:"context"`
}

type DataExplorerSignal struct {
	Command        DataExplorerCommand        `json:"command"`
	Explore        DataExploreSignal          `json:"explore"`
	Objects        []DataExplorerObjectSignal `json:"objects"`
	Preview        DataPreviewSignal          `json:"preview"`
	SelectedKey    *string                    `json:"selectedKey,omitempty"`
	SelectedObject *DataExplorerObjectSignal  `json:"selectedObject,omitempty"`
	Warnings       *[]string                  `json:"warnings,omitempty"`
}

type DataPreviewBlockSignal struct {
	RequestSeq   int64                 `json:"requestSeq"`
	ResetVersion int64                 `json:"resetVersion"`
	Rows         []map[string]any      `json:"rows"`
	Sort         DataPreviewSortSignal `json:"sort"`
	Start        int64                 `json:"start"`
}

type DataPreviewColumnSignal struct {
	DefaultValue *string `json:"defaultValue,omitempty"`
	Description  *string `json:"description,omitempty"`
	Key          string  `json:"key"`
	Label        string  `json:"label"`
	Nullable     *bool   `json:"nullable,omitempty"`
	PrimaryKey   *bool   `json:"primaryKey,omitempty"`
	Type         *string `json:"type,omitempty"`
}

type DataPreviewSignal struct {
	AvailableRows int64                             `json:"availableRows"`
	Blocks        map[string]DataPreviewBlockSignal `json:"blocks"`
	ChunkSize     int64                             `json:"chunkSize"`
	Columns       []DataPreviewColumnSignal         `json:"columns"`
	Error         *string                           `json:"error,omitempty"`
	LoadingBlock  *string                           `json:"loadingBlock,omitempty"`
	ResetVersion  int64                             `json:"resetVersion"`
	RowHeight     int64                             `json:"rowHeight"`
	Sort          DataPreviewSortSignal             `json:"sort"`
	SQL           *string                           `json:"sql,omitempty"`
	TotalRowLabel *string                           `json:"totalRowLabel,omitempty"`
	TotalRows     int64                             `json:"totalRows"`
}

type DataPreviewSortSignal struct {
	Column    *string `json:"column,omitempty"`
	Direction *string `json:"direction,omitempty"`
}

type DefinitionFactSignal struct {
	Code  *bool  `json:"code,omitempty"`
	Label string `json:"label"`
	Value string `json:"value"`
	Wide  *bool  `json:"wide,omitempty"`
}

type FilterMenuCommand struct {
	Action   *string   `json:"action,omitempty"`
	MenuID   *string   `json:"menuId,omitempty"`
	Search   *string   `json:"search,omitempty"`
	Selected *[]string `json:"selected,omitempty"`
	Value    *string   `json:"value,omitempty"`
}

type FilterMenuOptionSignal struct {
	CountLabel  *string `json:"countLabel,omitempty"`
	Description *string `json:"description,omitempty"`
	Disabled    bool    `json:"disabled"`
	Icon        *string `json:"icon,omitempty"`
	Label       string  `json:"label"`
	Selected    bool    `json:"selected"`
	Value       string  `json:"value"`
}

type FilterMenuSignal struct {
	EmptyLabel   *string                   `json:"emptyLabel,omitempty"`
	Error        *string                   `json:"error,omitempty"`
	ID           string                    `json:"id"`
	Label        string                    `json:"label"`
	Loading      bool                      `json:"loading"`
	Mode         *string                   `json:"mode,omitempty"`
	Options      *[]FilterMenuOptionSignal `json:"options,omitempty"`
	Placeholder  *string                   `json:"placeholder,omitempty"`
	Search       *string                   `json:"search,omitempty"`
	Selected     *[]string                 `json:"selected,omitempty"`
	SummaryLabel *string                   `json:"summaryLabel,omitempty"`
}

type PipelineCommandSignal struct {
	Action     string `json:"action"`
	AssetID    string `json:"assetId"`
	PipelineID string `json:"pipelineId"`
	RunID      string `json:"runId"`
}

type PipelineCommandStatusSignal struct {
	Error   string `json:"error"`
	Loading bool   `json:"loading"`
	Message string `json:"message"`
}

type PipelineListItemSignal struct {
	AssetID        string  `json:"assetId"`
	CanRun         bool    `json:"canRun"`
	Description    *string `json:"description,omitempty"`
	Duration       *string `json:"duration,omitempty"`
	Href           string  `json:"href"`
	ID             string  `json:"id"`
	LastSuccessful *string `json:"lastSuccessful,omitempty"`
	NextRun        *string `json:"nextRun,omitempty"`
	PipelineID     string  `json:"pipelineId"`
	Running        bool    `json:"running"`
	Schedule       string  `json:"schedule"`
	SemanticModel  string  `json:"semanticModel"`
	Status         string  `json:"status"`
	Title          string  `json:"title"`
}

type PipelineMetricSignal struct {
	Detail *string `json:"detail,omitempty"`
	Label  string  `json:"label"`
	Tone   *string `json:"tone,omitempty"`
	Value  string  `json:"value"`
}

type PipelinePageEnvelope struct {
	Chrome                ChromeSignal                `json:"chrome"`
	Page                  PipelinePageSignal          `json:"page"`
	PipelineCommand       PipelineCommandSignal       `json:"pipelineCommand"`
	PipelineCommandStatus PipelineCommandStatusSignal `json:"pipelineCommandStatus"`
	Runtime               RouteRuntimeSignal          `json:"runtime"`
	Status                DashboardStatus             `json:"status"`
}

type PipelinePageSignal struct {
	ActiveTab   string                   `json:"activeTab"`
	Description string                   `json:"description"`
	Environment string                   `json:"environment"`
	Kind        RouteKind                `json:"kind"`
	Metrics     []PipelineMetricSignal   `json:"metrics"`
	Pipelines   []PipelineListItemSignal `json:"pipelines"`
	RunsTable   RecordTableSignal        `json:"runsTable"`
	Title       string                   `json:"title"`
}

type PopularityLevel string

const (
	PopularityLevelLow    PopularityLevel = "low"
	PopularityLevelMedium PopularityLevel = "medium"
	PopularityLevelHigh   PopularityLevel = "high"
)

type RecordTableBadgeSignal struct {
	Label string  `json:"label"`
	Tone  *string `json:"tone,omitempty"`
}

type RecordTableColumnSelector struct {
	DefaultColumns *[]string `json:"defaultColumns,omitempty"`
	Enabled        bool      `json:"enabled"`
	Label          *string   `json:"label,omitempty"`
	StorageKey     *string   `json:"storageKey,omitempty"`
}

type RecordTableColumnSignal struct {
	Align      *string `json:"align,omitempty"`
	Header     string  `json:"header"`
	HrefKey    *string `json:"hrefKey,omitempty"`
	ID         string  `json:"id"`
	Kind       *string `json:"kind,omitempty"`
	Toggleable *bool   `json:"toggleable,omitempty"`
	Width      *string `json:"width,omitempty"`
}

type RecordTableSignal struct {
	ColumnSelector *RecordTableColumnSelector `json:"columnSelector,omitempty"`
	Columns        []RecordTableColumnSignal  `json:"columns"`
	Density        *string                    `json:"density,omitempty"`
	Empty          string                     `json:"empty"`
	MinWidth       *string                    `json:"minWidth,omitempty"`
	RowAction      *string                    `json:"rowAction,omitempty"`
	Rows           []map[string]any           `json:"rows"`
}

type ResourceActionSignal struct {
	Command  *string `json:"command,omitempty"`
	Disabled *bool   `json:"disabled,omitempty"`
	Href     *string `json:"href,omitempty"`
	Icon     *string `json:"icon,omitempty"`
	Label    string  `json:"label"`
}

type ResourceAssetDetailsSignal struct {
	Overview           []DefinitionFactSignal        `json:"overview"`
	Sections           []ResourceDetailSectionSignal `json:"sections"`
	SemanticModelGraph *SemanticModelGraphSignal     `json:"semanticModelGraph,omitempty"`
}

type ResourceAssetLineageSignal struct {
	Count       int64                   `json:"count"`
	Graph       AssetLineageGraphSignal `json:"graph"`
	UsedByTable RecordTableSignal       `json:"usedByTable"`
	UsesTable   RecordTableSignal       `json:"usesTable"`
}

type ResourceAssetListSignal struct {
	ActiveType *string                      `json:"activeType,omitempty"`
	Assets     []ResourceAssetSummarySignal `json:"assets"`
	Empty      string                       `json:"empty"`
	Query      *string                      `json:"query,omitempty"`
	SearchHref string                       `json:"searchHref"`
	Tabs       []ResourceTabSignal          `json:"tabs"`
}

type ResourceAssetPageEnvelope struct {
	Chrome          ChromeSignal                    `json:"chrome"`
	ConnectionAdmin *ConnectionAdministrationSignal `json:"connectionAdmin,omitempty"`
	Page            ResourceAssetPageSignal         `json:"page"`
	Runtime         RouteRuntimeSignal              `json:"runtime"`
	Status          DashboardStatus                 `json:"status"`
}

type ResourceAssetPageSignal struct {
	Actions             *[]ResourceActionSignal      `json:"actions,omitempty"`
	ActiveSection       string                       `json:"activeSection"`
	Asset               ResourceAssetSummarySignal   `json:"asset"`
	AssetID             string                       `json:"assetId"`
	Breadcrumbs         []ResourceBreadcrumbSignal   `json:"breadcrumbs"`
	ConnectionLifecycle *ConnectionLifecycleSignal   `json:"connectionLifecycle,omitempty"`
	Details             *ResourceAssetDetailsSignal  `json:"details,omitempty"`
	DrawerParent        *ResourceAssetPageSignal     `json:"drawerParent,omitempty"`
	Environment         *string                      `json:"environment,omitempty"`
	Kind                RouteKind                    `json:"kind"`
	Lineage             *ResourceAssetLineageSignal  `json:"lineage,omitempty"`
	Refresh             *ResourceAssetRefreshSignal  `json:"refresh,omitempty"`
	Tabs                []ResourceTabSignal          `json:"tabs"`
	Title               string                       `json:"title"`
	Versions            *ResourceAssetVersionsSignal `json:"versions,omitempty"`
}

type ResourceAssetRefreshSignal struct {
	LastSuccessful string             `json:"lastSuccessful"`
	Running        bool               `json:"running"`
	RunsTable      *RecordTableSignal `json:"runsTable,omitempty"`
	Status         string             `json:"status"`
}

type ResourceAssetSummarySignal struct {
	Description *string `json:"description,omitempty"`
	DetailHref  string  `json:"detailHref"`
	ID          string  `json:"id"`
	Key         string  `json:"key"`
	OpenHref    string  `json:"openHref"`
	ParentHref  *string `json:"parentHref,omitempty"`
	ParentTitle *string `json:"parentTitle,omitempty"`
	Title       string  `json:"title"`
	Type        string  `json:"type"`
	TypeLabel   string  `json:"typeLabel"`
}

type ResourceAssetVersionsSignal struct {
	CurrentContentHash string            `json:"currentContentHash"`
	Table              RecordTableSignal `json:"table"`
}

type ResourceBreadcrumbSignal struct {
	Current *bool   `json:"current,omitempty"`
	Href    *string `json:"href,omitempty"`
	Label   string  `json:"label"`
}

type ResourceCatalogItemSignal struct {
	Description string `json:"description"`
	Href        string `json:"href"`
	ID          string `json:"id"`
	Title       string `json:"title"`
}

type ResourceDetailSectionSignal struct {
	Code  *string                 `json:"code,omitempty"`
	Facts *[]DefinitionFactSignal `json:"facts,omitempty"`
	Lang  *string                 `json:"lang,omitempty"`
	Table *RecordTableSignal      `json:"table,omitempty"`
	Title string                  `json:"title"`
}

type ResourcePageEnvelope struct {
	Chrome  ChromeSignal       `json:"chrome"`
	Page    ResourcePageSignal `json:"page"`
	Runtime RouteRuntimeSignal `json:"runtime"`
	Status  DashboardStatus    `json:"status"`
}

type ResourcePageSignal struct {
	AssetList   *ResourceAssetListSignal `json:"assetList,omitempty"`
	Description *string                  `json:"description,omitempty"`
	Environment *string                  `json:"environment,omitempty"`
	Kind        RouteKind                `json:"kind"`
	ListFilter  *string                  `json:"listFilter,omitempty"`
	ListQuery   *string                  `json:"listQuery,omitempty"`
	Title       string                   `json:"title"`
}

type ResourceTabSignal struct {
	Active bool   `json:"active"`
	Count  *int64 `json:"count,omitempty"`
	Href   string `json:"href"`
	ID     string `json:"id"`
	Label  string `json:"label"`
}

type RouteKind string

const (
	RouteKindCatalog          RouteKind = "catalog"
	RouteKindDashboard        RouteKind = "dashboard"
	RouteKindDashboardBuilder RouteKind = "dashboard_builder"
	RouteKindPipelines        RouteKind = "pipelines"
	RouteKindChat             RouteKind = "chat"
	RouteKindConnections      RouteKind = "connections"
	RouteKindConnectionAsset  RouteKind = "connection_asset"
	RouteKindData             RouteKind = "data"
	RouteKindAdmin            RouteKind = "admin"
	RouteKindLogin            RouteKind = "login"
)

type RouteRuntimeSignal struct {
	ClientID         *string   `json:"clientId,omitempty"`
	DashboardID      *string   `json:"dashboardId,omitempty"`
	Kind             RouteKind `json:"kind"`
	ModelID          *string   `json:"modelId,omitempty"`
	PageID           *string   `json:"pageId,omitempty"`
	StreamInstanceID *string   `json:"streamInstanceId,omitempty"`
	ServingStateID   *string   `json:"servingStateId,omitempty"`
	ProjectID        *string   `json:"projectId,omitempty"`
}

type SemanticModelGraphEdgeSignal struct {
	Cardinality string `json:"cardinality"`
	ID          string `json:"id"`
	Label       string `json:"label"`
	Source      string `json:"source"`
	SourceField string `json:"sourceField"`
	Target      string `json:"target"`
	TargetField string `json:"targetField"`
}

type SemanticModelGraphEntitySignal struct {
	Fields []string `json:"fields"`
	Grain  *bool    `json:"grain,omitempty"`
	Name   string   `json:"name"`
	Type   string   `json:"type"`
}

type SemanticModelGraphFieldSignal struct {
	Entities      *[]string `json:"entities,omitempty"`
	Grain         *bool     `json:"grain,omitempty"`
	Join          *bool     `json:"join,omitempty"`
	Label         *string   `json:"label,omitempty"`
	Name          string    `json:"name"`
	Relationships *[]string `json:"relationships,omitempty"`
	Type          *string   `json:"type,omitempty"`
}

type SemanticModelGraphNodeSignal struct {
	Badges      *[]string                         `json:"badges,omitempty"`
	Description *string                           `json:"description,omitempty"`
	Entities    *[]SemanticModelGraphEntitySignal `json:"entities,omitempty"`
	Fields      []SemanticModelGraphFieldSignal   `json:"fields"`
	GrainEntity *string                           `json:"grainEntity,omitempty"`
	ID          string                            `json:"id"`
	Title       string                            `json:"title"`
}

type SemanticModelGraphSignal struct {
	Edges    []SemanticModelGraphEdgeSignal `json:"edges"`
	Datasets *[]string                      `json:"datasets,omitempty"`
	Nodes    []SemanticModelGraphNodeSignal `json:"nodes"`
}

type SidebarActionSignal struct {
	Href  string `json:"href"`
	Icon  string `json:"icon"`
	Label string `json:"label"`
}

type SidebarAreaSignal struct {
	Href  string `json:"href"`
	Icon  string `json:"icon"`
	ID    string `json:"id"`
	Label string `json:"label"`
}

type SidebarGroupSignal struct {
	Items []SidebarItemSignal `json:"items"`
	Label string              `json:"label"`
}

type SidebarHistoryItemSignal struct {
	Active  bool   `json:"active"`
	Href    string `json:"href"`
	ID      string `json:"id"`
	Pending *bool  `json:"pending,omitempty"`
	Title   string `json:"title"`
}

type SidebarHistorySignal struct {
	EmptyText *string                    `json:"emptyText,omitempty"`
	Items     []SidebarHistoryItemSignal `json:"items"`
	Label     string                     `json:"label"`
}

type SidebarItemSignal struct {
	Active *bool   `json:"active,omitempty"`
	Href   string  `json:"href"`
	Icon   string  `json:"icon"`
	ID     string  `json:"id"`
	Label  string  `json:"label"`
	Meta   *string `json:"meta,omitempty"`
}

type SidebarSignal struct {
	Active           string                `json:"active"`
	Admin            *bool                 `json:"admin,omitempty"`
	Area             *string               `json:"area,omitempty"`
	Areas            *[]SidebarAreaSignal  `json:"areas,omitempty"`
	Compact          bool                  `json:"compact"`
	DashboardID      *string               `json:"dashboardId,omitempty"`
	DashboardTitle   string                `json:"dashboardTitle"`
	Groups           []SidebarGroupSignal  `json:"groups"`
	History          *SidebarHistorySignal `json:"history,omitempty"`
	ModelID          *string               `json:"modelId,omitempty"`
	ModelTitle       *string               `json:"modelTitle,omitempty"`
	PageTitle        string                `json:"pageTitle"`
	PrimaryAction    *SidebarActionSignal  `json:"primaryAction,omitempty"`
	ProductLogoURL   *string               `json:"productLogoUrl,omitempty"`
	ProductName      string                `json:"productName"`
	UserAvatarURL    *string               `json:"userAvatarUrl,omitempty"`
	UserName         *string               `json:"userName,omitempty"`
	UserRole         *string               `json:"userRole,omitempty"`
	UserSettingsHref string                `json:"userSettingsHref"`
}

type SubSidebarItemSignal struct {
	Active  bool   `json:"active"`
	Href    string `json:"href"`
	ID      string `json:"id"`
	Pending *bool  `json:"pending,omitempty"`
	Title   string `json:"title"`
}

type SubSidebarSignal struct {
	ActiveID    string                 `json:"activeId"`
	AriaLabel   string                 `json:"ariaLabel"`
	Collapsible bool                   `json:"collapsible"`
	Disabled    *bool                  `json:"disabled,omitempty"`
	EmptyText   *string                `json:"emptyText,omitempty"`
	Items       []SubSidebarItemSignal `json:"items"`
	Label       string                 `json:"label"`
	Numbered    bool                   `json:"numbered"`
	RailLabel   string                 `json:"railLabel"`
	StorageKey  string                 `json:"storageKey"`
}
