// Package siteassets owns the browser assets for the public LeapView site.
package siteassets

import (
	"bytes"
	"embed"
	"html/template"
	"io/fs"
)

// files includes authored CSS and the production JavaScript generated by
// scripts/build_site.ts before the site binary is compiled.
//
//go:embed static
var files embed.FS

// homepage is trusted, authored markup for the public landing page. Keeping it
// alongside the site assets lets the shared Go shell retain its own header and
// footer while the visual sections remain easy to edit as HTML.
//
//go:embed home/home.html
var homepageTemplate string

var homepage = renderHomepage()

// Render the bundled examples once, with HTML escaping, so reading a sample
// never depends on a second network request. The first file is visible in SSR;
// inert templates make every other tab available to progressive enhancement.
func renderHomepage() string {
	type projectSource struct{ Key, Source string }
	sources := make([]projectSource, 0, 6)
	for _, file := range []struct{ key, path string }{
		{"connection", "connections/olist.yaml"},
		{"source", "sources/olist.payments.yaml"},
		{"model", "models/sales_orders.yaml"},
		{"semantics", "semantic-models/sales.yaml"},
		{"pipeline", "pipelines/sales-refresh.yaml"},
		{"dashboard", "dashboards/executive-sales.yaml"},
	} {
		source, err := files.ReadFile("static/home/project-files/" + file.path)
		if err != nil {
			panic(err)
		}
		sources = append(sources, projectSource{file.key, string(source)})
	}
	var rendered bytes.Buffer
	tmpl := template.Must(template.New("homepage").Parse(homepageTemplate))
	if err := tmpl.Execute(&rendered, struct {
		InitialSource  string
		ProjectSources []projectSource
	}{sources[0].Source, sources}); err != nil {
		panic(err)
	}
	return rendered.String()
}

// Homepage returns the landing-page sections with embedded project sources.
func Homepage() string { return homepage }

// Static returns the embedded contents of site/static.
func Static() fs.FS {
	return sub("static")
}

// Shared returns the embedded design-system assets copied into the site build.
func Shared() fs.FS {
	return sub("static/shared")
}

// MapAssets returns the reduced, immutable documentation basemap package.
// Production tile archives remain external; the embedded style is a safe
// fallback that lets the documentation fail closed without third-party URLs.
func MapAssets() fs.FS {
	return sub("static/map-assets")
}

func sub(path string) fs.FS {
	static, err := fs.Sub(files, path)
	if err != nil {
		panic(err)
	}
	return static
}
