// Package siteassets owns the browser assets for the public LeapView site.
package siteassets

import (
	"embed"
	"io/fs"
)

// files includes authored CSS and the production JavaScript generated by
// scripts/build_site.ts before the site binary is compiled.
//
//go:embed static
var files embed.FS

// homepage is trusted, authored markup for the public landing page. Keeping it
// alongside the site assets lets the shared Go shell retain its own header and
// footer while the visual sections remain easy to edit as HTML.
//
//go:embed home/home.html
var homepage string

// Homepage returns the authored landing-page sections.
func Homepage() string { return homepage }

// Static returns the embedded contents of site/static.
func Static() fs.FS {
	return sub("static")
}

// Shared returns the embedded design-system assets copied into the site build.
func Shared() fs.FS {
	return sub("static/shared")
}

// MapAssets returns the reduced, immutable documentation basemap package.
// Production tile archives remain external; the embedded style is a safe
// fallback that lets the documentation fail closed without third-party URLs.
func MapAssets() fs.FS {
	return sub("static/map-assets")
}

func sub(path string) fs.FS {
	static, err := fs.Sub(files, path)
	if err != nil {
		panic(err)
	}
	return static
}
