apiVersion: leapview.dev/v1
kind: RoleBinding
metadata:
  id: role-binding:qualification-author-admin
  name: qualification-author-admin
spec:
  role: admin
  subject:
    kind: principal
    principalId: 0198f2c0-7c7a-7f00-8a11-00000000f649
