// Command generate emits provider-portable, dereferenced JSON Schemas for the
// model-facing contracts owned by the agent capability.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode"
)

const (
	schemaPath = "internal/agent/contracts/gen/agent-tools.schema.json"
	outputPath = "internal/agent/contracts/schemas.gen.go"
)

func main() {
	if err := generate(schemaPath, outputPath); err != nil {
		fmt.Fprintf(os.Stderr, "generate agent contract schemas: %v\n", err)
		os.Exit(1)
	}
}

func generate(inputPath, destinationPath string) error {
	raw, err := os.ReadFile(inputPath)
	if err != nil {
		return err
	}
	var document map[string]any
	if err := json.Unmarshal(raw, &document); err != nil {
		return fmt.Errorf("decode %s: %w", inputPath, err)
	}
	definitions, _ := document["$defs"].(map[string]any)
	contracts, _ := document["x-apigen-contracts"].([]any)
	if len(contracts) == 0 {
		return fmt.Errorf("%s contains no x-apigen-contracts", inputPath)
	}
	type generatedContract struct {
		name   string
		schema []byte
	}
	generated := make([]generatedContract, 0, len(contracts))
	for _, item := range contracts {
		contract, _ := item.(map[string]any)
		name, _ := contract["name"].(string)
		schema, _ := contract["schema"].(map[string]any)
		if name == "" || schema == nil {
			return fmt.Errorf("invalid contract entry %#v", item)
		}
		resolved, err := portableSchema(schema, definitions, map[string]bool{})
		if err != nil {
			return fmt.Errorf("resolve %s: %w", name, err)
		}
		encoded, err := json.Marshal(resolved)
		if err != nil {
			return fmt.Errorf("encode %s: %w", name, err)
		}
		generated = append(generated, generatedContract{name: goIdentifier(name) + "SchemaJSON", schema: encoded})
	}
	sort.Slice(generated, func(i, j int) bool { return generated[i].name < generated[j].name })

	var out bytes.Buffer
	out.WriteString("// Code generated by internal/agent/contracts/generate; DO NOT EDIT.\n\n")
	out.WriteString("package contracts\n\n")
	out.WriteString("const (\n")
	for _, contract := range generated {
		fmt.Fprintf(&out, "\t%s = `%s`\n", contract.name, contract.schema)
	}
	out.WriteString(")\n")
	if err := os.WriteFile(destinationPath, out.Bytes(), 0o644); err != nil {
		return err
	}
	return nil
}

func portableSchema(value any, definitions map[string]any, resolving map[string]bool) (any, error) {
	switch typed := value.(type) {
	case []any:
		out := make([]any, len(typed))
		for index, item := range typed {
			resolved, err := portableSchema(item, definitions, resolving)
			if err != nil {
				return nil, err
			}
			out[index] = resolved
		}
		return out, nil
	case map[string]any:
		if reference, _ := typed["$ref"].(string); reference != "" {
			const prefix = "#/$defs/"
			if !strings.HasPrefix(reference, prefix) {
				return nil, fmt.Errorf("unsupported reference %q", reference)
			}
			name := strings.TrimPrefix(reference, prefix)
			if resolving[name] {
				return nil, fmt.Errorf("recursive reference %q", reference)
			}
			target, ok := definitions[name]
			if !ok {
				return nil, fmt.Errorf("unknown reference %q", reference)
			}
			resolving[name] = true
			resolved, err := portableSchema(target, definitions, resolving)
			delete(resolving, name)
			return resolved, err
		}
		out := make(map[string]any, len(typed))
		for key, item := range typed {
			switch key {
			case "$defs", "$schema", "minItems", "maxItems", "uniqueItems":
				continue
			case "unevaluatedProperties":
				key = "additionalProperties"
			}
			if key == "format" {
				if _, keyword := item.(string); keyword {
					continue
				}
			}
			resolved, err := portableSchema(item, definitions, resolving)
			if err != nil {
				return nil, err
			}
			out[key] = resolved
		}
		return out, nil
	default:
		return value, nil
	}
}

func goIdentifier(value string) string {
	var out strings.Builder
	upper := true
	for _, current := range value {
		if !unicode.IsLetter(current) && !unicode.IsDigit(current) {
			upper = true
			continue
		}
		if upper {
			current = unicode.ToUpper(current)
			upper = false
		}
		out.WriteRune(current)
	}
	return out.String()
}
