// Package requestmodelgo emits APIGen-owned schema aliases from IR roots.
package requestmodelgo

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Yacobolo/toolbelt/apigen/emit/contractimport"
	"github.com/Yacobolo/toolbelt/apigen/emit/gotype"
	"github.com/Yacobolo/toolbelt/apigen/emit/gounion"
	"github.com/Yacobolo/toolbelt/apigen/ir"
)

// Options configures Go schema emission.
type Options struct {
	PackageName     string
	ContractImports map[string]ContractImport
}

type ContractImport = contractimport.Binding

// Emit renders APIGen-owned schema aliases derived from IR roots.
func Emit(doc ir.Document, opts Options) ([]byte, error) {
	return emitAliasModels(doc, opts)
}

// EmitWithResponseRoots renders APIGen-owned request and safe response schema
// aliases using IR-declared response schemas.
func EmitWithResponseRoots(doc ir.Document, opts Options) ([]byte, error) {
	return emitAliasModels(doc, opts)
}

func emitAliasModels(doc ir.Document, opts Options) ([]byte, error) {
	imports := contractimport.Bindings(opts.ContractImports)
	if err := imports.Validate(doc); err != nil {
		return nil, err
	}
	rootNames, err := schemaRoots(doc)
	if err != nil {
		return nil, err
	}
	aliasNames := collectSchemaAliasSet(doc, rootNames)
	concreteNames := localSchemaNames(doc, imports)
	importedNames := importedSchemaDependencies(doc, imports, concreteNames, aliasNames)
	resolveName := func(name string) string {
		if _, binding, ok := imports.Schema(doc, name); ok {
			return binding.GoAlias + "." + exportedName(name)
		}
		return exportedName(name)
	}

	var b strings.Builder
	b.WriteString("// Code generated by apigen schema model emitter. DO NOT EDIT.\n")
	b.WriteString("package ")
	b.WriteString(packageName(opts))
	b.WriteString("\n\n")
	goImports := map[string]string{}
	if documentHasLocalUnion(doc, imports) {
		goImports["bytes"], goImports["encoding/json"], goImports["fmt"] = "", "", ""
	}
	for _, name := range importedNames {
		_, binding, _ := imports.Schema(doc, name)
		if binding.GoPackage == "" {
			return nil, fmt.Errorf("external schema %q requires go_package", name)
		}
		goImports[binding.GoPackage] = binding.GoAlias
	}
	emitImports(&b, goImports)

	for _, rootName := range concreteNames {
		if err := emitCanonicalSchemaType(&b, doc, rootName, resolveName); err != nil {
			return nil, err
		}
	}

	for _, rootName := range aliasNames {
		if emitAPIGenOwnedSchemaType(&b, doc, rootName) {
			continue
		}
		b.WriteString("type ")
		b.WriteString(genSchemaTypeName(rootName))
		b.WriteString(" = ")
		b.WriteString(resolveName(rootName))
		b.WriteString("\n\n")
	}

	return []byte(b.String()), nil
}

func packageName(opts Options) string {
	if strings.TrimSpace(opts.PackageName) == "" {
		return "api"
	}
	return opts.PackageName
}

func emitAPIGenOwnedSchemaType(b *strings.Builder, doc ir.Document, rootName string) bool {
	if rootName == "Record" {
		b.WriteString("type GenSchemaRecord map[string]any\n\n")
		return true
	}

	if !apigenOwnedSchemaNames[rootName] {
		return false
	}

	schema, ok := doc.Schemas[rootName]
	if !ok || schema.Type != "object" {
		return false
	}

	b.WriteString("type ")
	b.WriteString(genSchemaTypeName(rootName))
	b.WriteString(" struct {\n")

	propertyNames := make([]string, 0, len(schema.Properties))
	for name := range schema.Properties {
		propertyNames = append(propertyNames, name)
	}
	sort.Strings(propertyNames)

	required := make(map[string]struct{}, len(schema.Required))
	for _, name := range schema.Required {
		required[name] = struct{}{}
	}

	for _, name := range propertyNames {
		property := schema.Properties[name]
		fieldType := schemaRefGoType(property.Schema)
		if fieldType == "" {
			fieldType = "any"
		}
		if _, ok := required[name]; !ok {
			fieldType = "*" + fieldType
		}
		b.WriteString("\t")
		b.WriteString(exportedName(name))
		b.WriteString(" ")
		b.WriteString(fieldType)
		b.WriteString(" `json:\"")
		b.WriteString(name)
		if _, ok := required[name]; !ok {
			b.WriteString(",omitempty")
		}
		b.WriteString("\"`\n")
	}

	b.WriteString("}\n\n")
	return true
}

func allSchemaNames(doc ir.Document) []string {
	names := make([]string, 0, len(doc.Schemas))
	for name := range doc.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func localSchemaNames(doc ir.Document, imports contractimport.Bindings) []string {
	names := make([]string, 0, len(doc.Schemas))
	for name := range doc.Schemas {
		if _, _, external := imports.Schema(doc, name); !external {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	return names
}

func emitCanonicalSchemaType(b *strings.Builder, doc ir.Document, rootName string, resolveName func(string) string) error {
	if rootName == "Record" {
		b.WriteString("type Record map[string]any\n\n")
		return nil
	}

	schema, ok := doc.Schemas[rootName]
	if !ok {
		return nil
	}

	typeName := exportedName(rootName)
	switch schema.Type {
	case "union":
		if schema.Discriminator == nil {
			b.WriteString("type " + typeName + " = any\n\n")
		} else {
			gounion.Emit(b, doc, rootName, schema, resolveName)
		}
		return nil
	case "object", "":
		b.WriteString("type ")
		b.WriteString(typeName)
		b.WriteString(" struct {\n")
		if schema.Base != nil {
			b.WriteString("\t")
			b.WriteString(gotype.Ref(*schema.Base, resolveName))
			b.WriteString("\n")
		}

		propertyNames := make([]string, 0, len(schema.Properties))
		for name := range schema.Properties {
			propertyNames = append(propertyNames, name)
		}
		sort.Strings(propertyNames)

		required := make(map[string]struct{}, len(schema.Required))
		for _, name := range schema.Required {
			required[name] = struct{}{}
		}

		for _, name := range propertyNames {
			property := schema.Properties[name]
			fieldType := gotype.Ref(property.Schema, resolveName)
			if _, ok := required[name]; !ok {
				fieldType = "*" + fieldType
			}
			b.WriteString("\t")
			b.WriteString(exportedName(name))
			b.WriteString(" ")
			b.WriteString(fieldType)
			b.WriteString(" `json:\"")
			b.WriteString(name)
			if _, ok := required[name]; !ok {
				b.WriteString(",omitempty")
			}
			b.WriteString("\"`\n")
		}
		b.WriteString("}\n\n")
		return nil
	case "array":
		elemType := "any"
		if schema.Items != nil {
			elemType = gotype.Ref(*schema.Items, resolveName)
		}
		b.WriteString("type ")
		b.WriteString(typeName)
		b.WriteString(" []")
		b.WriteString(elemType)
		b.WriteString("\n\n")
		return nil
	default:
		b.WriteString("type ")
		b.WriteString(typeName)
		b.WriteString(" ")
		b.WriteString(gotype.Schema(schema, resolveName))
		b.WriteString("\n\n")
		emitCanonicalEnumConstants(b, typeName, schema)
		return nil
	}
}

func emitCanonicalEnumConstants(b *strings.Builder, typeName string, schema ir.Schema) {
	if len(schema.Enum) == 0 {
		return
	}

	b.WriteString("const (\n")
	for _, value := range schema.Enum {
		constName := typeName + exportedName(value)
		b.WriteString("\t")
		b.WriteString(constName)
		b.WriteString(" ")
		b.WriteString(typeName)
		b.WriteString(" = ")
		b.WriteString(quotedGoString(value))
		b.WriteString("\n")
	}
	b.WriteString(")\n\n")
}

var apigenOwnedSchemaNames = map[string]bool{
	"GenericResponse": true,
	"HealthResponse":  true,
	"QueryResponse":   true,
}

func schemaRefGoType(ref ir.SchemaRef) string {
	return gotype.Ref(ref, genSchemaTypeName)
}

func standaloneSchemaRefGoType(ref ir.SchemaRef) string {
	return gotype.Ref(ref, exportedName)
}

func standaloneSchemaGoType(schema ir.Schema) string {
	return gotype.Schema(schema, exportedName)
}

func quotedGoString(value string) string {
	return `"` + strings.ReplaceAll(value, `"`, `\"`) + `"`
}

func importedSchemaDependencies(doc ir.Document, imports contractimport.Bindings, localNames, aliases []string) []string {
	seen := map[string]struct{}{}
	for _, name := range append(append([]string{}, localNames...), aliases...) {
		if _, _, external := imports.Schema(doc, name); external {
			seen[name] = struct{}{}
			continue
		}
		for _, dependency := range schemaDependencies(doc.Schemas[name]) {
			if _, _, external := imports.Schema(doc, dependency); external {
				seen[dependency] = struct{}{}
			}
		}
	}
	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func emitImports(b *strings.Builder, values map[string]string) {
	if len(values) == 0 {
		return
	}
	paths := make([]string, 0, len(values))
	for path := range values {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	b.WriteString("import (\n")
	for _, path := range paths {
		if alias := values[path]; alias != "" {
			b.WriteString("\t" + alias + " ")
		} else {
			b.WriteString("\t")
		}
		b.WriteString(quotedGoString(path) + "\n")
	}
	b.WriteString(")\n\n")
}

func collectSchemaAliasSet(doc ir.Document, rootNames []string) []string {
	seen := make(map[string]struct{}, len(rootNames))
	queue := append([]string(nil), rootNames...)

	for len(queue) > 0 {
		name := queue[0]
		queue = queue[1:]
		if _, ok := seen[name]; ok {
			continue
		}
		seen[name] = struct{}{}
		schema, ok := doc.Schemas[name]
		if !ok {
			continue
		}
		for _, dep := range schemaDependencies(schema) {
			if _, ok := seen[dep]; !ok {
				queue = append(queue, dep)
			}
		}
	}

	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func schemaDependencies(schema ir.Schema) []string {
	seen := make(map[string]struct{})
	for _, property := range schema.Properties {
		collectSchemaRefDependency(property.Schema, seen)
	}
	if schema.Items != nil {
		collectSchemaRefDependency(*schema.Items, seen)
	}
	if schema.Base != nil {
		collectSchemaRefDependency(*schema.Base, seen)
	}
	for _, variant := range schema.OneOf {
		collectSchemaRefDependency(variant, seen)
	}
	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func documentHasLocalUnion(doc ir.Document, imports contractimport.Bindings) bool {
	for name, schema := range doc.Schemas {
		if _, _, external := imports.Schema(doc, name); !external && schema.Type == "union" && schema.Discriminator != nil {
			return true
		}
	}
	return false
}

func collectSchemaRefDependency(ref ir.SchemaRef, seen map[string]struct{}) {
	name, ok := normalizedSchemaRefName(ref)
	if ok {
		seen[name] = struct{}{}
	}
	if ref.Items != nil {
		collectSchemaRefDependency(*ref.Items, seen)
	}
	if ref.AdditionalProperties != nil && ref.AdditionalProperties.Schema != nil {
		collectSchemaRefDependency(*ref.AdditionalProperties.Schema, seen)
	}
}

func schemaRoots(doc ir.Document) ([]string, error) {
	seen := make(map[string]struct{})
	requestRoots, err := requestSchemaRoots(doc)
	if err != nil {
		return nil, err
	}
	for _, name := range requestRoots {
		seen[name] = struct{}{}
	}

	for _, name := range safeResponseSchemaRoots(doc) {
		seen[name] = struct{}{}
	}
	for _, endpoint := range doc.Endpoints {
		if endpoint.Command == nil || endpoint.Command.Audit.Payload == nil {
			continue
		}
		name, ok := ir.NormalizedSchemaRefName(endpoint.Command.Audit.Payload.Schema)
		if ok {
			seen[name] = struct{}{}
		}
	}

	rootNames := make([]string, 0, len(seen))
	for name := range seen {
		rootNames = append(rootNames, name)
	}
	sort.Strings(rootNames)
	return rootNames, nil
}

func requestSchemaRoots(doc ir.Document) ([]string, error) {
	seen := make(map[string]struct{})
	for _, endpoint := range doc.Endpoints {
		if endpoint.RequestBody == nil {
			continue
		}
		if err := collectRequestSchemaRoots(doc, endpoint, seen); err != nil {
			return nil, err
		}
	}

	rootNames := make([]string, 0, len(seen))
	for name := range seen {
		rootNames = append(rootNames, name)
	}
	sort.Strings(rootNames)
	return rootNames, nil
}

func collectRequestSchemaRoots(doc ir.Document, endpoint ir.Endpoint, seen map[string]struct{}) error {
	content, ok := ir.PrimaryRequestBodyContent(endpoint)
	if !ok {
		return fmt.Errorf("request body generation for %s requires content", endpoint.OperationID)
	}

	switch content.BodyKind {
	case "text", "binary", "file":
		return nil
	case "multipart":
		for _, part := range content.Parts {
			if part.Schema == nil {
				continue
			}
			if schemaName, ok := normalizedSchemaRefName(*part.Schema); ok {
				seen[schemaName] = struct{}{}
				continue
			}
			if strings.EqualFold(part.Schema.Type, "object") {
				return fmt.Errorf("request body generation for %s multipart part %q requires a named IR schema", endpoint.OperationID, part.Name)
			}
		}
		return nil
	default:
		if schemaName, ok := resolveRequestSchemaName(doc, endpoint); ok {
			seen[schemaName] = struct{}{}
			return nil
		}
		if content.Schema != nil && !strings.EqualFold(content.Schema.Type, "object") {
			return nil
		}
		return fmt.Errorf("request body generation for %s requires a named IR schema", endpoint.OperationID)
	}
}

func safeResponseSchemaRoots(doc ir.Document) []string {
	seen := make(map[string]struct{})
	for _, endpoint := range doc.Endpoints {
		for _, response := range endpoint.Responses {
			if shape, ok, err := ir.ResponseShapeMetadata(response); err == nil && ok {
				if shape.BodyType != "" {
					seen[shape.BodyType] = struct{}{}
				}
			}
			content, ok := ir.PrimaryResponseContent(response)
			if !ok || content.Schema == nil {
				continue
			}
			bodyTypeName, ok := normalizedSchemaRefName(*content.Schema)
			if !ok {
				continue
			}
			seen[bodyTypeName] = struct{}{}
		}
	}

	rootNames := make([]string, 0, len(seen))
	for name := range seen {
		rootNames = append(rootNames, name)
	}
	sort.Strings(rootNames)
	return rootNames
}

func normalizedSchemaRefName(schema ir.SchemaRef) (string, bool) {
	return ir.NormalizedSchemaRefName(schema)
}

func resolveRequestSchemaName(doc ir.Document, endpoint ir.Endpoint) (string, bool) {
	return ir.ResolveRequestBodySchemaName(doc, endpoint)
}

func exportedName(operationID string) string {
	parts := splitIdentifier(operationID)
	if len(parts) == 0 {
		return "Operation"
	}
	for i := range parts {
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

func splitIdentifier(value string) []string {
	value = strings.TrimSpace(value)
	if value == "" {
		return nil
	}
	replacer := strings.NewReplacer("-", " ", "_", " ", ".", " ", "/", " ")
	value = replacer.Replace(value)
	chunks := strings.Fields(value)
	if len(chunks) > 0 {
		return chunks
	}
	return []string{value}
}

func genSchemaTypeName(name string) string {
	if strings.HasPrefix(name, "GenSchema") {
		return name
	}
	if strings.TrimSpace(name) == "" {
		return "GenSchemaValue"
	}
	return "GenSchema" + exportedName(name)
}
