apiVersion: libredash.dev/v1
kind: ModelTable
metadata:
  workspace: compatibility
  name: orders
spec:
  primaryKey: order_id
  sources:
    - qualification.orders
  fields:
    order_id:
      label: Order
      type: string
    status:
      label: Status
      type: string
  transform:
    sql: |
      SELECT order_id, order_status AS status
      FROM source."qualification.orders"
