export function queryAuditFixturePage() {
  const queryEvents = [
    {
      id: 'queryevent_1',
      projectId: 'sales',
      principalId: 'analyst',
      surface: 'api',
      operation: 'api_query',
      queryKind: 'semantic_aggregate',
      modelId: 'sales',
      target: 'orders',
      objectType: 'semantic_dataset',
      objectId: 'sales:orders',
      requestId: 'req_1',
      correlationId: 'corr_1',
      status: 'success',
      durationMs: 12,
      rowsReturned: 2,
      error: '',
      sql: 'select status from orders',
      planText: 'orders plan',
      queryJson: '{"projectId":"sales","target":"orders"}',
      createdAt: '2026-07-02T10:00:00Z',
    },
    {
      id: 'queryevent_2',
      projectId: 'operations',
      principalId: 'agent',
      surface: 'agent',
      operation: 'agent_query',
      queryKind: 'semantic_rows',
      modelId: 'operations',
      target: 'customers',
      objectType: 'agent_tool',
      objectId: 'query_semantic_dataset',
      requestId: 'call_1',
      correlationId: '',
      status: 'error',
      durationMs: 4,
      rowsReturned: 0,
      error: 'invalid field',
      sql: '',
      planText: '',
      queryJson: '{"projectId":"operations","target":"customers"}',
      createdAt: '2026-07-02T10:01:00Z',
    },
  ]
  return {
    kind: 'admin',
    title: 'Query History',
    active: 'queries',
    sidebar: {
      label: 'Admin',
      railLabel: 'Admin',
      ariaLabel: 'Admin navigation',
      storageKey: 'leapview-admin-sidebar-collapsed',
      activeId: 'queries',
      collapsible: false,
      numbered: false,
      items: [{ id: 'queries', title: 'Query History', href: '/admin/queries', active: true }],
    },
    headerTitle: 'Query History',
    headerDetail: 'Product query audit.',
    queryHistory: {
      table: queryAuditTableFixture(queryEvents),
      filterMenus: queryAuditFilterMenusFixture(),
      filters: {},
      nextCursor: 'cursor_next',
      loadedCountLabel: '2 queries loaded',
      hasMore: true,
      loading: false,
      error: '',
      limit: 50,
    },
    queryDetail: {
      eventId: 'queryevent_1',
      loading: false,
      error: '',
      status: 'success',
      statusLabel: 'Success',
      projectId: 'sales',
      principalId: 'analyst',
      surface: 'api',
      operation: 'api_query',
      queryKind: 'semantic_aggregate',
      modelId: 'sales',
      target: 'orders',
      objectType: 'semantic_dataset',
      objectId: 'sales:orders',
      requestId: 'req_1',
      correlationId: 'corr_1',
      durationMs: 12,
      rowsReturned: 2,
      queryError: '',
      sql: 'select status from orders',
      planText: 'orders plan',
      queryJson: '{"projectId":"sales","target":"orders"}',
      createdAt: '2026-07-02T10:00:00Z',
    },
  }
}

function queryAuditFilterMenusFixture() {
  return [
    {
      id: 'project',
      label: 'Project',
      summaryLabel: 'Project',
      mode: 'multi',
      search: '',
      selected: [],
      loading: false,
      error: '',
      placeholder: 'Search projects',
      emptyLabel: 'No projects found.',
      options: [
        { value: 'sales', label: 'sales', icon: 'project', countLabel: '1', selected: false, disabled: false },
        { value: 'operations', label: 'operations', icon: 'project', countLabel: '1', selected: false, disabled: false },
      ],
    },
    {
      id: 'principal',
      label: 'User',
      summaryLabel: 'User',
      mode: 'multi',
      search: '',
      selected: [],
      loading: false,
      error: '',
      placeholder: 'Search users',
      emptyLabel: 'No users found.',
      options: [
        { value: 'analyst', label: 'Me (analyst@example.com)', icon: 'user', countLabel: '1', selected: false, disabled: false },
        { value: 'agent', label: 'agent', icon: 'user', countLabel: '1', selected: false, disabled: false },
      ],
    },
    {
      id: 'surface',
      label: 'Source type',
      summaryLabel: 'Source type',
      mode: 'multi',
      search: '',
      selected: [],
      loading: false,
      error: '',
      placeholder: 'Search source types',
      emptyLabel: 'No source types found.',
      options: [
        { value: 'api', label: 'api', icon: 'source', countLabel: '1', selected: false, disabled: false },
        { value: 'agent', label: 'agent', icon: 'source', countLabel: '1', selected: false, disabled: false },
      ],
    },
    {
      id: 'kind',
      label: 'Kind',
      summaryLabel: 'Kind',
      mode: 'multi',
      search: '',
      selected: [],
      loading: false,
      error: '',
      placeholder: 'Search kinds',
      emptyLabel: 'No kinds found.',
      options: [
        { value: 'semantic_aggregate', label: 'semantic_aggregate', icon: 'kind', countLabel: '1', selected: false, disabled: false },
        { value: 'semantic_rows', label: 'semantic_rows', icon: 'kind', countLabel: '1', selected: false, disabled: false },
      ],
    },
    {
      id: 'status',
      label: 'Status',
      summaryLabel: 'Status',
      mode: 'multi',
      search: '',
      selected: [],
      loading: false,
      error: '',
      placeholder: 'Search statuses',
      emptyLabel: 'No statuses found.',
      options: [
        { value: 'success', label: 'success', icon: 'status', countLabel: '1', selected: false, disabled: false },
        { value: 'error', label: 'error', icon: 'status', countLabel: '1', selected: false, disabled: false },
      ],
    },
  ]
}

function queryAuditTableFixture(events: any[]) {
  return {
    columns: [
      { id: 'query', header: 'Query', kind: 'query', width: '560px', toggleable: false },
      { id: 'started_at', header: 'Started', width: '150px' },
      { id: 'duration_ms', header: 'Duration', kind: 'number', align: 'right', width: '105px' },
      { id: 'source', header: 'Source type', width: '120px' },
      { id: 'runtime', header: 'Runtime', kind: 'code', width: '130px' },
      { id: 'principal_id', header: 'User', kind: 'code', width: '150px' },
      { id: 'rows_returned', header: 'Rows', kind: 'number', align: 'right', width: '90px' },
      { id: 'operation', header: 'Operation', kind: 'code', width: '145px' },
      { id: 'kind', header: 'Kind', kind: 'code', width: '170px' },
      { id: 'model', header: 'Model', kind: 'code', width: '130px' },
      { id: 'target', header: 'Target', kind: 'code', width: '150px' },
      { id: 'object', header: 'Object', kind: 'code', width: '220px' },
      { id: 'request_id', header: 'Request ID', kind: 'code', width: '170px' },
      { id: 'correlation_id', header: 'Correlation ID', kind: 'code', width: '170px' },
      { id: 'error', header: 'Error', kind: 'code', width: '220px' },
    ],
    rows: events.map((event) => ({
      id: event.id,
      query: {
        label: event.sql || `${event.operation} · ${event.queryKind} · ${event.modelId}.${event.target}`,
        statusLabel: event.status,
        tone: event.status === 'success' ? 'success' : 'danger',
        icon: event.status === 'success' ? 'check' : 'x',
        expandedContent: event.sql || `${event.operation} · ${event.queryKind}`,
      },
      started_at: event.createdAt,
      duration_ms: { label: `${event.durationMs ?? 0} ms`, value: event.durationMs ?? 0 },
      source: event.surface,
      runtime: event.projectId || '-',
      principal_id: event.principalId,
      rows_returned: event.rowsReturned,
      operation: event.operation,
      kind: event.queryKind,
      model: event.modelId,
      target: event.target,
      object: [event.objectType, event.objectId].filter(Boolean).join(':') || '-',
      request_id: event.requestId,
      correlation_id: event.correlationId,
      error: event.error,
    })),
    empty: 'No query events match these filters.',
    minWidth: '1305px',
    density: 'tight',
    rowAction: 'detail',
    columnSelector: {
      enabled: true,
      label: 'Columns',
      defaultColumns: ['started_at', 'duration_ms', 'source', 'runtime', 'principal_id', 'rows_returned'],
    },
  }
}
