// Code generated by pkg/duckdbsql/internal/cmd/duckdbsqlgen from the pinned DuckDB serializer descriptors; DO NOT EDIT.
// DuckDB v1.5.4; upstream git commit 08e34c447bae34eaee3723cac61f2878b6bdf787.
// Descriptor nodes.json SHA256 47255585249edf3e0dc38dc0c8aecb87696fc1025aaef0618121aa567829cad0.
// Descriptor parsed_expression.json SHA256 0db589a4bc5bea150bae167f0035ce9bac150995ffc281c7d994d494c3ab215d.
// Descriptor query_node.json SHA256 260a0b5d85524fbb24994ee134180ef9b005e95f137bac7a1848a257ef4add35.
// Descriptor result_modifier.json SHA256 679e91d1c4d8420ac91580351954223bcfa6047958e474f6850fc6590e0b5250.
// Descriptor statement.json SHA256 6625d774a91a406457da4730472aab2d82848c165cd0665805651d8d973b08b1.
// Descriptor tableref.json SHA256 15c562d0b5286f6b1459df3b473c87f395d297262aa0a6d57016e8c8351d74c6.
package duckdbsql

var generatedStatementSchemas = map[string]serializedNodeSchema{
	"CTE_NODE":           {Discriminator: "CTE_NODE", AllowedFields: []string{"cte_name", "query", "child", "aliases", "materialized", "type", "modifiers", "cte_map"}, RequiredFields: []string{"type"}},
	"RECURSIVE_CTE_NODE": {Discriminator: "RECURSIVE_CTE_NODE", AllowedFields: []string{"cte_name", "union_all", "left", "right", "aliases", "key_targets", "type", "modifiers", "cte_map"}, RequiredFields: []string{"type"}},
	"SELECT_NODE":        {Discriminator: "SELECT_NODE", AllowedFields: []string{"select_list", "from_table", "where_clause", "group_expressions", "group_sets", "aggregate_handling", "having", "sample", "qualify", "type", "modifiers", "cte_map"}, RequiredFields: []string{"type"}},
	"SET_OPERATION_NODE": {Discriminator: "SET_OPERATION_NODE", AllowedFields: []string{"setop_type", "left", "right", "setop_all", "children", "type", "modifiers", "cte_map"}, RequiredFields: []string{"type"}},
}

var generatedRelationSchemas = map[string]serializedNodeSchema{
	"BASE_TABLE":      {Discriminator: "BASE_TABLE", AllowedFields: []string{"schema_name", "table_name", "column_name_alias", "catalog_name", "at_clause", "type", "alias", "sample", "query_location"}, RequiredFields: []string{"type"}},
	"COLUMN_DATA":     {Discriminator: "COLUMN_DATA", AllowedFields: []string{"expected_names", "collection", "type", "alias", "sample", "query_location"}, RequiredFields: []string{"type"}},
	"EMPTY_FROM":      {Discriminator: "EMPTY_FROM", AllowedFields: []string{"type", "alias", "sample", "query_location"}, RequiredFields: []string{"type"}},
	"EXPRESSION_LIST": {Discriminator: "EXPRESSION_LIST", AllowedFields: []string{"expected_names", "expected_types", "values", "type", "alias", "sample", "query_location"}, RequiredFields: []string{"type"}},
	"JOIN":            {Discriminator: "JOIN", AllowedFields: []string{"left", "right", "condition", "join_type", "ref_type", "using_columns", "delim_flipped", "duplicate_eliminated_columns", "is_implicit", "type", "alias", "sample", "query_location"}, RequiredFields: []string{"type"}},
	"PIVOT":           {Discriminator: "PIVOT", AllowedFields: []string{"source", "aggregates", "unpivot_names", "pivots", "groups", "column_name_alias", "include_nulls", "type", "alias", "sample", "query_location"}, RequiredFields: []string{"type"}},
	"SHOW_REF":        {Discriminator: "SHOW_REF", AllowedFields: []string{"table_name", "query", "show_type", "catalog_name", "schema_name", "type", "alias", "sample", "query_location"}, RequiredFields: []string{"type"}},
	"SUBQUERY":        {Discriminator: "SUBQUERY", AllowedFields: []string{"subquery", "column_name_alias", "type", "alias", "sample", "query_location"}, RequiredFields: []string{"type"}},
	"TABLE_FUNCTION":  {Discriminator: "TABLE_FUNCTION", AllowedFields: []string{"function", "column_name_alias", "with_ordinality", "type", "alias", "sample", "query_location"}, RequiredFields: []string{"type"}},
}

var generatedExpressionSchemas = map[string]serializedNodeSchema{
	"BETWEEN":              {Discriminator: "BETWEEN", AllowedFields: []string{"input", "lower", "upper", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"CASE":                 {Discriminator: "CASE", AllowedFields: []string{"case_checks", "else_expr", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"CAST":                 {Discriminator: "CAST", AllowedFields: []string{"child", "cast_type", "try_cast", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"COLLATE":              {Discriminator: "COLLATE", AllowedFields: []string{"child", "collation", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"COLUMN_REF":           {Discriminator: "COLUMN_REF", AllowedFields: []string{"column_names", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"COMPARISON":           {Discriminator: "COMPARISON", AllowedFields: []string{"left", "right", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"CONJUNCTION":          {Discriminator: "CONJUNCTION", AllowedFields: []string{"children", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"CONSTANT":             {Discriminator: "CONSTANT", AllowedFields: []string{"value", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"DEFAULT":              {Discriminator: "DEFAULT", AllowedFields: []string{"class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"FUNCTION":             {Discriminator: "FUNCTION", AllowedFields: []string{"function_name", "schema", "children", "filter", "order_bys", "distinct", "is_operator", "export_state", "catalog", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"LAMBDA":               {Discriminator: "LAMBDA", AllowedFields: []string{"lhs", "expr", "syntax_type", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"LAMBDA_REF":           {Discriminator: "LAMBDA_REF", AllowedFields: []string{"lambda_idx", "column_name", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"OPERATOR":             {Discriminator: "OPERATOR", AllowedFields: []string{"children", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"PARAMETER":            {Discriminator: "PARAMETER", AllowedFields: []string{"identifier", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"POSITIONAL_REFERENCE": {Discriminator: "POSITIONAL_REFERENCE", AllowedFields: []string{"index", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"STAR":                 {Discriminator: "STAR", AllowedFields: []string{"relation_name", "exclude_list", "replace_list", "columns", "expr", "unpacked", "qualified_exclude_list", "rename_list", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"SUBQUERY":             {Discriminator: "SUBQUERY", AllowedFields: []string{"subquery_type", "subquery", "child", "comparison_type", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"TYPE":                 {Discriminator: "TYPE", AllowedFields: []string{"catalog", "schema", "type_name", "children", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
	"WINDOW":               {Discriminator: "WINDOW", AllowedFields: []string{"function_name", "schema", "catalog", "children", "partitions", "orders", "start", "end", "start_expr", "end_expr", "offset_expr", "default_expr", "ignore_nulls", "filter_expr", "exclude_clause", "distinct", "arg_orders", "class", "type", "alias", "query_location"}, RequiredFields: []string{"type"}},
}

var generatedModifierSchemas = map[string]serializedNodeSchema{
	"DISTINCT_MODIFIER":      {Discriminator: "DISTINCT_MODIFIER", AllowedFields: []string{"distinct_on_targets", "type"}, RequiredFields: []string{"type"}},
	"LIMIT_MODIFIER":         {Discriminator: "LIMIT_MODIFIER", AllowedFields: []string{"limit", "offset", "type"}, RequiredFields: []string{"type"}},
	"LIMIT_PERCENT_MODIFIER": {Discriminator: "LIMIT_PERCENT_MODIFIER", AllowedFields: []string{"limit", "offset", "type"}, RequiredFields: []string{"type"}},
	"ORDER_MODIFIER":         {Discriminator: "ORDER_MODIFIER", AllowedFields: []string{"orders", "type"}, RequiredFields: []string{"type"}},
}

var generatedSupportingSchemas = map[string]serializedNodeSchema{
	"AtClause":                  {Discriminator: "AtClause", AllowedFields: []string{"unit", "expr"}, RequiredFields: nil},
	"BoundCaseCheck":            {Discriminator: "BoundCaseCheck", AllowedFields: []string{"when_expr", "then_expr"}, RequiredFields: nil},
	"BoundOrderByNode":          {Discriminator: "BoundOrderByNode", AllowedFields: []string{"type", "null_order", "expression"}, RequiredFields: nil},
	"CaseCheck":                 {Discriminator: "CaseCheck", AllowedFields: []string{"when_expr", "then_expr"}, RequiredFields: nil},
	"CommonTableExpressionInfo": {Discriminator: "CommonTableExpressionInfo", AllowedFields: []string{"aliases", "query", "materialized", "key_targets"}, RequiredFields: nil},
	"CommonTableExpressionMap":  {Discriminator: "CommonTableExpressionMap", AllowedFields: []string{"map"}, RequiredFields: nil},
	"OrderByNode":               {Discriminator: "OrderByNode", AllowedFields: []string{"type", "null_order", "expression"}, RequiredFields: nil},
	"PivotColumn":               {Discriminator: "PivotColumn", AllowedFields: []string{"pivot_expressions", "unpivot_names", "entries", "pivot_enum"}, RequiredFields: nil},
	"PivotColumnEntry":          {Discriminator: "PivotColumnEntry", AllowedFields: []string{"values", "star_expr", "alias"}, RequiredFields: nil},
	"SampleOptions":             {Discriminator: "SampleOptions", AllowedFields: []string{"sample_size", "is_percentage", "method", "seed"}, RequiredFields: nil},
	"SelectStatement":           {Discriminator: "SelectStatement", AllowedFields: []string{"node", "named_param_map"}, RequiredFields: nil},
}

var generatedStatementVariants = []string{"CTE_NODE", "RECURSIVE_CTE_NODE", "SELECT_NODE", "SET_OPERATION_NODE"}
var generatedRelationVariants = []string{"BASE_TABLE", "COLUMN_DATA", "EMPTY_FROM", "EXPRESSION_LIST", "JOIN", "PIVOT", "SHOW_REF", "SUBQUERY", "TABLE_FUNCTION"}
var generatedExpressionVariants = []string{"BETWEEN", "CASE", "CAST", "COLLATE", "COLUMN_REF", "COMPARISON", "CONJUNCTION", "CONSTANT", "DEFAULT", "FUNCTION", "LAMBDA", "LAMBDA_REF", "OPERATOR", "PARAMETER", "POSITIONAL_REFERENCE", "STAR", "SUBQUERY", "TYPE", "WINDOW"}
var generatedModifierVariants = []string{"DISTINCT_MODIFIER", "LIMIT_MODIFIER", "LIMIT_PERCENT_MODIFIER", "ORDER_MODIFIER"}
var generatedEnumManifest = []DescriptorProvenance{
	{Path: "src/include/duckdb/common/enums/aggregate_handling.hpp", SHA256: "45451dededd4a1b93a3cce2a88cfdf08db291c09e937ed69c3469fda5830c996"},
	{Path: "src/include/duckdb/common/enums/cte_materialize.hpp", SHA256: "e9910e776e52f3db458160530ff9927ca8f54ef0c717f66275ddce014129106d"},
	{Path: "src/include/duckdb/common/enums/expression_type.hpp", SHA256: "664476c6c329d68677598f59065642b7a82a1a017af514204cd5d4dbd5aee524"},
	{Path: "src/include/duckdb/common/enums/order_type.hpp", SHA256: "b229a0e3f50f53cfd3ca3982b2bb0d35f05b99af1b165c23e3fbaf8035c5e9ee"},
	{Path: "src/include/duckdb/common/enums/set_operation_type.hpp", SHA256: "0f4ca5ad2da649f1bb3bb31f1660ad34e869ceb607c3187d51e0dcaa25b5a343"},
	{Path: "src/include/duckdb/common/types.hpp", SHA256: "91dcff90f10a5a5267bcedab51e406308de6448b4f45a8a3d4e3ae9c31670356"},
	{Path: "src/include/duckdb/parser/expression/window_expression.hpp", SHA256: "bca17727d129efb451eae03a3a9c8f2e94a71a288893e6c8dab3c8d8f3a147d5"},
}

var generatedAggregateHandlingValues = []string{"STANDARD_HANDLING", "NO_AGGREGATES_ALLOWED", "FORCE_AGGREGATES"}
var generatedCTEMaterializeValues = []string{"CTE_MATERIALIZE_DEFAULT", "CTE_MATERIALIZE_ALWAYS", "CTE_MATERIALIZE_NEVER"}
var generatedExpressionClassValues = []string{"INVALID", "AGGREGATE", "CASE", "CAST", "COLUMN_REF", "COMPARISON", "CONJUNCTION", "CONSTANT", "DEFAULT", "FUNCTION", "OPERATOR", "STAR", "SUBQUERY", "WINDOW", "PARAMETER", "COLLATE", "LAMBDA", "POSITIONAL_REFERENCE", "BETWEEN", "LAMBDA_REF", "TYPE", "BOUND_AGGREGATE", "BOUND_CASE", "BOUND_CAST", "BOUND_COLUMN_REF", "BOUND_COMPARISON", "BOUND_CONJUNCTION", "BOUND_CONSTANT", "BOUND_DEFAULT", "BOUND_FUNCTION", "BOUND_OPERATOR", "BOUND_PARAMETER", "BOUND_REF", "BOUND_SUBQUERY", "BOUND_WINDOW", "BOUND_BETWEEN", "BOUND_UNNEST", "BOUND_LAMBDA", "BOUND_LAMBDA_REF", "BOUND_EXPRESSION", "BOUND_EXPANDED"}
var generatedExpressionTypeValues = []string{"INVALID", "OPERATOR_CAST", "OPERATOR_NOT", "OPERATOR_IS_NULL", "OPERATOR_IS_NOT_NULL", "OPERATOR_UNPACK", "COMPARE_EQUAL", "COMPARE_BOUNDARY_START", "COMPARE_NOTEQUAL", "COMPARE_LESSTHAN", "COMPARE_GREATERTHAN", "COMPARE_LESSTHANOREQUALTO", "COMPARE_GREATERTHANOREQUALTO", "COMPARE_IN", "COMPARE_NOT_IN", "COMPARE_DISTINCT_FROM", "COMPARE_BETWEEN", "COMPARE_NOT_BETWEEN", "COMPARE_NOT_DISTINCT_FROM", "COMPARE_BOUNDARY_END", "CONJUNCTION_AND", "CONJUNCTION_OR", "VALUE_CONSTANT", "VALUE_PARAMETER", "VALUE_TUPLE", "VALUE_TUPLE_ADDRESS", "VALUE_NULL", "VALUE_VECTOR", "VALUE_SCALAR", "VALUE_DEFAULT", "AGGREGATE", "BOUND_AGGREGATE", "GROUPING_FUNCTION", "WINDOW_AGGREGATE", "WINDOW_RANK", "WINDOW_RANK_DENSE", "WINDOW_NTILE", "WINDOW_PERCENT_RANK", "WINDOW_CUME_DIST", "WINDOW_ROW_NUMBER", "WINDOW_FIRST_VALUE", "WINDOW_LAST_VALUE", "WINDOW_LEAD", "WINDOW_LAG", "WINDOW_NTH_VALUE", "WINDOW_FILL", "FUNCTION", "BOUND_FUNCTION", "CASE_EXPR", "OPERATOR_NULLIF", "OPERATOR_COALESCE", "ARRAY_EXTRACT", "ARRAY_SLICE", "STRUCT_EXTRACT", "ARRAY_CONSTRUCTOR", "ARROW", "OPERATOR_TRY", "SUBQUERY", "STAR", "TABLE_STAR", "PLACEHOLDER", "COLUMN_REF", "FUNCTION_REF", "TABLE_REF", "LAMBDA_REF", "TYPE", "CAST", "BOUND_REF", "BOUND_COLUMN_REF", "BOUND_UNNEST", "COLLATE", "LAMBDA", "POSITIONAL_REFERENCE", "BOUND_LAMBDA_REF", "BOUND_EXPANDED"}
var generatedLogicalTypeIdValues = []string{"INVALID", "SQLNULL", "UNKNOWN", "ANY", "UNBOUND", "TEMPLATE", "TYPE", "BOOLEAN", "TINYINT", "SMALLINT", "INTEGER", "BIGINT", "DATE", "TIME", "TIMESTAMP_SEC", "TIMESTAMP_MS", "TIMESTAMP", "TIMESTAMP_NS", "DECIMAL", "FLOAT", "DOUBLE", "CHAR", "VARCHAR", "BLOB", "INTERVAL", "UTINYINT", "USMALLINT", "UINTEGER", "UBIGINT", "TIMESTAMP_TZ", "TIME_TZ", "TIME_NS", "BIT", "STRING_LITERAL", "INTEGER_LITERAL", "BIGNUM", "UHUGEINT", "HUGEINT", "POINTER", "VALIDITY", "UUID", "GEOMETRY", "STRUCT", "LIST", "MAP", "TABLE", "ENUM", "AGGREGATE_STATE", "LAMBDA", "UNION", "ARRAY", "VARIANT"}
var generatedOrderByNullTypeValues = []string{"INVALID", "ORDER_DEFAULT", "NULLS_FIRST", "NULLS_LAST"}
var generatedOrderTypeValues = []string{"INVALID", "ORDER_DEFAULT", "ASCENDING", "DESCENDING"}
var generatedSetOperationTypeValues = []string{"NONE", "UNION", "EXCEPT", "INTERSECT", "UNION_BY_NAME"}
var generatedWindowBoundaryValues = []string{"INVALID", "UNBOUNDED_PRECEDING", "UNBOUNDED_FOLLOWING", "CURRENT_ROW_RANGE", "CURRENT_ROW_ROWS", "EXPR_PRECEDING_ROWS", "EXPR_FOLLOWING_ROWS", "EXPR_PRECEDING_RANGE", "EXPR_FOLLOWING_RANGE", "CURRENT_ROW_GROUPS", "EXPR_PRECEDING_GROUPS", "EXPR_FOLLOWING_GROUPS"}
var generatedWindowExcludeModeValues = []string{"NO_OTHER", "CURRENT_ROW", "GROUP", "TIES"}

var generatedEnumValues = map[string][]string{
	"AggregateHandling": generatedAggregateHandlingValues,
	"CTEMaterialize":    generatedCTEMaterializeValues,
	"ExpressionClass":   generatedExpressionClassValues,
	"ExpressionType":    generatedExpressionTypeValues,
	"LogicalTypeId":     generatedLogicalTypeIdValues,
	"OrderByNullType":   generatedOrderByNullTypeValues,
	"OrderType":         generatedOrderTypeValues,
	"SetOperationType":  generatedSetOperationTypeValues,
	"WindowBoundary":    generatedWindowBoundaryValues,
	"WindowExcludeMode": generatedWindowExcludeModeValues,
}

func generatedEnumContains(enumName, value string) bool {
	for _, candidate := range generatedEnumValues[enumName] {
		if candidate == value {
			return true
		}
	}
	return false
}
