package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	registryPath = "adr/specifications/standards-conformance-profiles.json"
	matrixPath   = "adr/specifications/standards-conformance-matrix.md"
)

type registry struct {
	Version  int       `json:"version"`
	Profiles []profile `json:"profiles"`
}

type profile struct {
	ID                string   `json:"id"`
	Publisher         string   `json:"publisher"`
	Standard          string   `json:"standard"`
	StandardVersion   string   `json:"standardVersion"`
	UpstreamRevision  string   `json:"upstreamRevision"`
	SchemaPath        string   `json:"schemaPath"`
	Directions        []string `json:"directions"`
	Levels            []string `json:"levels"`
	Extension         string   `json:"extension"`
	Status            string   `json:"status"`
	AdapterPath       string   `json:"adapterPath"`
	SpecificationPath string   `json:"specificationPath"`
	Implementation    string   `json:"implementation"`
	Validation        []string `json:"validation"`
	Boundary          string   `json:"boundary"`
}

func main() {
	check := flag.Bool("check", false, "verify that the generated matrix is current")
	root := flag.String("root", ".", "repository root")
	flag.Parse()

	generated, err := generate(*root)
	if err != nil {
		fatal(err)
	}
	output := filepath.Join(*root, matrixPath)
	if *check {
		current, err := os.ReadFile(output)
		if err != nil {
			fatal(fmt.Errorf("read generated matrix: %w", err))
		}
		if !bytes.Equal(current, generated) {
			fatal(errors.New("ADR-0016 standards conformance matrix is stale; run task adr0016-conformance:generate"))
		}
		return
	}
	if err := os.WriteFile(output, generated, 0o644); err != nil {
		fatal(fmt.Errorf("write generated matrix: %w", err))
	}
}

func generate(root string) ([]byte, error) {
	raw, err := os.ReadFile(filepath.Join(root, registryPath))
	if err != nil {
		return nil, fmt.Errorf("read profile registry: %w", err)
	}
	var value registry
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&value); err != nil {
		return nil, fmt.Errorf("decode profile registry: %w", err)
	}
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		return nil, errors.New("profile registry contains trailing JSON values")
	}
	if value.Version != 1 || len(value.Profiles) == 0 {
		return nil, errors.New("profile registry must use version 1 and contain profiles")
	}

	profiles := append([]profile(nil), value.Profiles...)
	sort.Slice(profiles, func(i, j int) bool {
		if profiles[i].Status != profiles[j].Status {
			return profiles[i].Status == "implemented"
		}
		return profiles[i].ID < profiles[j].ID
	})

	seen := make(map[string]struct{}, len(profiles))
	var table strings.Builder
	table.WriteString("<!-- Code generated by internal/app/tools/adr0016conformance. DO NOT EDIT. -->\n\n")
	table.WriteString("# ADR-0016 standards conformance matrix\n\n")
	table.WriteString("Source registry: [`standards-conformance-profiles.json`](standards-conformance-profiles.json).\n\n")
	table.WriteString("Only entries marked **Implemented** carry a conformance claim. Deferred entries record selected directions without claiming document, round-trip, execution, or emission conformance. Schema digests are SHA-256 over the exact vendored bytes named by each row.\n\n")
	table.WriteString("| Profile | Publisher / standard | Version / upstream | Schema SHA-256 | Direction | Level | Extension | Status | Implementation and validation | Boundary |\n")
	table.WriteString("|---|---|---|---|---|---|---|---|---|---|\n")
	for _, item := range profiles {
		if err := validateProfile(root, item, seen); err != nil {
			return nil, err
		}
		digest := "— (not pinned; deferred)"
		if item.SchemaPath != "" {
			schema, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(item.SchemaPath)))
			if err != nil {
				return nil, fmt.Errorf("read schema for %s: %w", item.ID, err)
			}
			sum := sha256.Sum256(schema)
			digest = "`" + hex.EncodeToString(sum[:]) + "`"
		}
		level := strings.Join(item.Levels, ", ")
		if level == "" {
			level = "—"
		}
		validation := item.Implementation
		if len(item.Validation) > 0 {
			commands := make([]string, len(item.Validation))
			for index, command := range item.Validation {
				commands[index] = "`" + command + "`"
			}
			validation += "; " + strings.Join(commands, "; ")
		}
		status := strings.ToUpper(item.Status[:1]) + item.Status[1:]
		fmt.Fprintf(&table, "| `%s` | %s — %s | %s / `%s` | %s | %s | %s | `%s` | **%s** | %s | %s |\n",
			markdown(item.ID), markdown(item.Publisher), markdown(item.Standard), markdown(item.StandardVersion), markdown(item.UpstreamRevision),
			digest, markdown(strings.Join(item.Directions, ", ")), markdown(level), markdown(item.Extension), status, markdown(validation), markdown(item.Boundary))
	}
	table.WriteString("\n## Qualification boundary\n\n")
	table.WriteString("ODCS import/round-trip, Bitol ODPS, and W3C DCAT remain capability-gated. Their presence in this matrix prevents an accidental public conformance claim; it does not register an adapter or authorize implementation. OpenLineage is qualified at projection/document level only and has no emission or transport claim.\n")
	return []byte(table.String()), nil
}

func validateProfile(root string, item profile, seen map[string]struct{}) error {
	if item.ID == "" || item.Publisher == "" || item.Standard == "" || item.StandardVersion == "" || item.UpstreamRevision == "" ||
		len(item.Directions) == 0 || item.Extension == "" || item.SpecificationPath == "" || item.Implementation == "" || item.Boundary == "" {
		return fmt.Errorf("profile %q is incomplete", item.ID)
	}
	if _, exists := seen[item.ID]; exists {
		return fmt.Errorf("duplicate profile %q", item.ID)
	}
	seen[item.ID] = struct{}{}
	if item.Status != "implemented" && item.Status != "deferred" {
		return fmt.Errorf("profile %s has unsupported status %q", item.ID, item.Status)
	}
	if item.Status == "implemented" && (item.AdapterPath == "" || item.SchemaPath == "" || len(item.Levels) == 0 || len(item.Validation) == 0) {
		return fmt.Errorf("implemented profile %s lacks adapter, schema, level, or validation", item.ID)
	}
	if item.Status == "deferred" && (item.AdapterPath != "" || len(item.Levels) != 0 || len(item.Validation) != 0) {
		return fmt.Errorf("deferred profile %s must not claim an adapter, level, or validation", item.ID)
	}
	for _, path := range []string{item.AdapterPath, item.SchemaPath, item.SpecificationPath} {
		if path == "" {
			continue
		}
		if filepath.IsAbs(path) || strings.Contains(filepath.ToSlash(path), "../") {
			return fmt.Errorf("profile %s uses unsafe path %q", item.ID, path)
		}
		if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(path))); err != nil {
			return fmt.Errorf("profile %s evidence path %q: %w", item.ID, path, err)
		}
	}
	return nil
}

func markdown(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
