// Code generated by apigen data-contract Go emitter. DO NOT EDIT.
package contracts

import (
	"bytes"
	"encoding/json"
	"fmt"
)

type AIContext struct {
	Instructions *string   `json:"instructions,omitempty" yaml:"instructions,omitempty"`
	Synonyms     *[]string `json:"synonyms,omitempty" yaml:"synonyms,omitempty"`
	Examples     *[]string `json:"examples,omitempty" yaml:"examples,omitempty"`
}

type AcceptedValuesModelCheck struct {
	Type     string   `json:"type" yaml:"type"`
	Field    string   `json:"field" yaml:"field"`
	Values   []string `json:"values" yaml:"values"`
	Severity *string  `json:"severity,omitempty" yaml:"severity,omitempty"`
}

type AzureBlobConnection struct {
	ConnectionSpecBase
	Type     string          `json:"type" yaml:"type"`
	Access   *PublicAccess   `json:"access,omitempty" yaml:"access,omitempty"`
	Defaults *ReaderDefaults `json:"defaults,omitempty" yaml:"defaults,omitempty"`
}

type BlobReaderOptions struct {
	Compression *string `json:"compression,omitempty" yaml:"compression,omitempty"`
}

type CSVReaderOptions struct {
	Header     *bool   `json:"header,omitempty" yaml:"header,omitempty"`
	Delimiter  *string `json:"delimiter,omitempty" yaml:"delimiter,omitempty"`
	Quote      *string `json:"quote,omitempty" yaml:"quote,omitempty"`
	Escape     *string `json:"escape,omitempty" yaml:"escape,omitempty"`
	NullString *string `json:"nullString,omitempty" yaml:"nullString,omitempty"`
}

type CompatibleSourceSchema struct {
	Mode   string                       `json:"mode" yaml:"mode"`
	Fields map[string]SourceSchemaField `json:"fields" yaml:"fields"`
}

type Connection struct {
	APIVersion string           `json:"apiVersion" yaml:"apiVersion"`
	Kind       string           `json:"kind" yaml:"kind"`
	Metadata   ResourceMetadata `json:"metadata" yaml:"metadata"`
	Spec       ConnectionSpec   `json:"spec" yaml:"spec"`
}

type ConnectionSpecVariant interface {
	isConnectionSpecVariant()
}

type ConnectionSpec struct {
	Value ConnectionSpecVariant
}

func (*AzureBlobConnection) isConnectionSpecVariant() {}
func (*DuckLakeConnection) isConnectionSpecVariant()  {}
func (*GCSConnection) isConnectionSpecVariant()       {}
func (*HTTPConnection) isConnectionSpecVariant()      {}
func (*ManagedConnection) isConnectionSpecVariant()   {}
func (*MySQLConnection) isConnectionSpecVariant()     {}
func (*PostgresConnection) isConnectionSpecVariant()  {}
func (*QuackConnection) isConnectionSpecVariant()     {}
func (*R2Connection) isConnectionSpecVariant()        {}
func (*S3Connection) isConnectionSpecVariant()        {}
func (*SQLiteConnection) isConnectionSpecVariant()    {}

func (value ConnectionSpec) MarshalJSON() ([]byte, error) {
	switch variant := value.Value.(type) {
	case *AzureBlobConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return json.Marshal(variant)
	case *DuckLakeConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return json.Marshal(variant)
	case *GCSConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return json.Marshal(variant)
	case *HTTPConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return json.Marshal(variant)
	case *ManagedConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return json.Marshal(variant)
	case *MySQLConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return json.Marshal(variant)
	case *PostgresConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return json.Marshal(variant)
	case *QuackConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return json.Marshal(variant)
	case *R2Connection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return json.Marshal(variant)
	case *S3Connection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return json.Marshal(variant)
	case *SQLiteConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return json.Marshal(variant)
	case nil:
		return nil, fmt.Errorf("ConnectionSpec variant is required")
	default:
		return nil, fmt.Errorf("unsupported ConnectionSpec variant %T", variant)
	}
}

func (value *ConnectionSpec) UnmarshalJSON(data []byte) error {
	if value == nil {
		return fmt.Errorf("cannot unmarshal ConnectionSpec into nil receiver")
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return fmt.Errorf("decode ConnectionSpec object: %w", err)
	}
	var tag struct {
		Value string `json:"type"`
	}
	if err := json.Unmarshal(data, &tag); err != nil {
		return fmt.Errorf("decode ConnectionSpec discriminator: %w", err)
	}
	if tag.Value == "" {
		return fmt.Errorf("ConnectionSpec discriminator type is required")
	}
	decode := func(dest any) error {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		return decoder.Decode(dest)
	}
	switch tag.Value {
	case "azure_blob":
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ConnectionSpec variant %q: required property type is missing", tag.Value)
		}
		var variant AzureBlobConnection
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ConnectionSpec variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "ducklake":
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ConnectionSpec variant %q: required property type is missing", tag.Value)
		}
		var variant DuckLakeConnection
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ConnectionSpec variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "gcs":
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ConnectionSpec variant %q: required property type is missing", tag.Value)
		}
		var variant GCSConnection
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ConnectionSpec variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "http":
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ConnectionSpec variant %q: required property type is missing", tag.Value)
		}
		var variant HTTPConnection
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ConnectionSpec variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "managed":
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ConnectionSpec variant %q: required property type is missing", tag.Value)
		}
		var variant ManagedConnection
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ConnectionSpec variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "mysql":
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ConnectionSpec variant %q: required property type is missing", tag.Value)
		}
		var variant MySQLConnection
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ConnectionSpec variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "postgres":
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ConnectionSpec variant %q: required property type is missing", tag.Value)
		}
		var variant PostgresConnection
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ConnectionSpec variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "quack":
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ConnectionSpec variant %q: required property type is missing", tag.Value)
		}
		var variant QuackConnection
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ConnectionSpec variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "r2":
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ConnectionSpec variant %q: required property type is missing", tag.Value)
		}
		var variant R2Connection
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ConnectionSpec variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "s3":
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ConnectionSpec variant %q: required property type is missing", tag.Value)
		}
		var variant S3Connection
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ConnectionSpec variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "sqlite":
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ConnectionSpec variant %q: required property type is missing", tag.Value)
		}
		var variant SQLiteConnection
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ConnectionSpec variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	default:
		return fmt.Errorf("unknown ConnectionSpec discriminator %q", tag.Value)
	}
	return nil
}

type ConnectionSpecVisitor interface {
	VisitAzureBlobConnection(*AzureBlobConnection) error
	VisitDuckLakeConnection(*DuckLakeConnection) error
	VisitGCSConnection(*GCSConnection) error
	VisitHTTPConnection(*HTTPConnection) error
	VisitManagedConnection(*ManagedConnection) error
	VisitMySQLConnection(*MySQLConnection) error
	VisitPostgresConnection(*PostgresConnection) error
	VisitQuackConnection(*QuackConnection) error
	VisitR2Connection(*R2Connection) error
	VisitS3Connection(*S3Connection) error
	VisitSQLiteConnection(*SQLiteConnection) error
}

func (value *ConnectionSpec) Visit(visitor ConnectionSpecVisitor) error {
	if value == nil {
		return fmt.Errorf("cannot visit nil ConnectionSpec")
	}
	if visitor == nil {
		return fmt.Errorf("ConnectionSpec visitor is required")
	}
	switch variant := value.Value.(type) {
	case *AzureBlobConnection:
		if variant == nil {
			return fmt.Errorf("ConnectionSpec variant is nil")
		}
		return visitor.VisitAzureBlobConnection(variant)
	case *DuckLakeConnection:
		if variant == nil {
			return fmt.Errorf("ConnectionSpec variant is nil")
		}
		return visitor.VisitDuckLakeConnection(variant)
	case *GCSConnection:
		if variant == nil {
			return fmt.Errorf("ConnectionSpec variant is nil")
		}
		return visitor.VisitGCSConnection(variant)
	case *HTTPConnection:
		if variant == nil {
			return fmt.Errorf("ConnectionSpec variant is nil")
		}
		return visitor.VisitHTTPConnection(variant)
	case *ManagedConnection:
		if variant == nil {
			return fmt.Errorf("ConnectionSpec variant is nil")
		}
		return visitor.VisitManagedConnection(variant)
	case *MySQLConnection:
		if variant == nil {
			return fmt.Errorf("ConnectionSpec variant is nil")
		}
		return visitor.VisitMySQLConnection(variant)
	case *PostgresConnection:
		if variant == nil {
			return fmt.Errorf("ConnectionSpec variant is nil")
		}
		return visitor.VisitPostgresConnection(variant)
	case *QuackConnection:
		if variant == nil {
			return fmt.Errorf("ConnectionSpec variant is nil")
		}
		return visitor.VisitQuackConnection(variant)
	case *R2Connection:
		if variant == nil {
			return fmt.Errorf("ConnectionSpec variant is nil")
		}
		return visitor.VisitR2Connection(variant)
	case *S3Connection:
		if variant == nil {
			return fmt.Errorf("ConnectionSpec variant is nil")
		}
		return visitor.VisitS3Connection(variant)
	case *SQLiteConnection:
		if variant == nil {
			return fmt.Errorf("ConnectionSpec variant is nil")
		}
		return visitor.VisitSQLiteConnection(variant)
	case nil:
		return fmt.Errorf("ConnectionSpec variant is required")
	default:
		return fmt.Errorf("unsupported ConnectionSpec variant %T", variant)
	}
}

func (value *ConnectionSpec) Type() (string, error) {
	if value == nil {
		return "", fmt.Errorf("cannot inspect nil ConnectionSpec")
	}
	switch variant := value.Value.(type) {
	case *AzureBlobConnection:
		if variant == nil {
			return "", fmt.Errorf("ConnectionSpec variant is nil")
		}
		return "azure_blob", nil
	case *DuckLakeConnection:
		if variant == nil {
			return "", fmt.Errorf("ConnectionSpec variant is nil")
		}
		return "ducklake", nil
	case *GCSConnection:
		if variant == nil {
			return "", fmt.Errorf("ConnectionSpec variant is nil")
		}
		return "gcs", nil
	case *HTTPConnection:
		if variant == nil {
			return "", fmt.Errorf("ConnectionSpec variant is nil")
		}
		return "http", nil
	case *ManagedConnection:
		if variant == nil {
			return "", fmt.Errorf("ConnectionSpec variant is nil")
		}
		return "managed", nil
	case *MySQLConnection:
		if variant == nil {
			return "", fmt.Errorf("ConnectionSpec variant is nil")
		}
		return "mysql", nil
	case *PostgresConnection:
		if variant == nil {
			return "", fmt.Errorf("ConnectionSpec variant is nil")
		}
		return "postgres", nil
	case *QuackConnection:
		if variant == nil {
			return "", fmt.Errorf("ConnectionSpec variant is nil")
		}
		return "quack", nil
	case *R2Connection:
		if variant == nil {
			return "", fmt.Errorf("ConnectionSpec variant is nil")
		}
		return "r2", nil
	case *S3Connection:
		if variant == nil {
			return "", fmt.Errorf("ConnectionSpec variant is nil")
		}
		return "s3", nil
	case *SQLiteConnection:
		if variant == nil {
			return "", fmt.Errorf("ConnectionSpec variant is nil")
		}
		return "sqlite", nil
	case nil:
		return "", fmt.Errorf("ConnectionSpec variant is required")
	default:
		return "", fmt.Errorf("unsupported ConnectionSpec variant %T", variant)
	}
}

func (value *ConnectionSpec) Base() (*ConnectionSpecBase, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot inspect nil ConnectionSpec")
	}
	switch variant := value.Value.(type) {
	case *AzureBlobConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return &variant.ConnectionSpecBase, nil
	case *DuckLakeConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return &variant.ConnectionSpecBase, nil
	case *GCSConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return &variant.ConnectionSpecBase, nil
	case *HTTPConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return &variant.ConnectionSpecBase, nil
	case *ManagedConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return &variant.ConnectionSpecBase, nil
	case *MySQLConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return &variant.ConnectionSpecBase, nil
	case *PostgresConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return &variant.ConnectionSpecBase, nil
	case *QuackConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return &variant.ConnectionSpecBase, nil
	case *R2Connection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return &variant.ConnectionSpecBase, nil
	case *S3Connection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return &variant.ConnectionSpecBase, nil
	case *SQLiteConnection:
		if variant == nil {
			return nil, fmt.Errorf("ConnectionSpec variant is nil")
		}
		return &variant.ConnectionSpecBase, nil
	case nil:
		return nil, fmt.Errorf("ConnectionSpec variant is required")
	default:
		return nil, fmt.Errorf("unsupported ConnectionSpec variant %T", variant)
	}
}

type ConnectionSpecBase struct {
	Type string `json:"type" yaml:"type"`
}

type DeltaReaderOptions struct {
	Version *string `json:"version,omitempty" yaml:"version,omitempty"`
}

type DirectModelDefinition struct {
	ModelDefinitionBase
	Type   string `json:"type" yaml:"type"`
	Source string `json:"source" yaml:"source"`
}

type DuckLakeConnection struct {
	ConnectionSpecBase
	Type string `json:"type" yaml:"type"`
}

type ExcelReaderOptions struct {
	Sheet  *string `json:"sheet,omitempty" yaml:"sheet,omitempty"`
	Header *bool   `json:"header,omitempty" yaml:"header,omitempty"`
}

type FieldFreshness struct {
	Basis        string             `json:"basis" yaml:"basis"`
	Field        string             `json:"field" yaml:"field"`
	WarningAfter *FreshnessDuration `json:"warningAfter,omitempty" yaml:"warningAfter,omitempty"`
	ErrorAfter   *FreshnessDuration `json:"errorAfter,omitempty" yaml:"errorAfter,omitempty"`
}

type FreshnessDuration struct {
	Amount int64  `json:"amount" yaml:"amount"`
	Unit   string `json:"unit" yaml:"unit"`
}

type GCSConnection struct {
	ConnectionSpecBase
	Type     string          `json:"type" yaml:"type"`
	Access   *PublicAccess   `json:"access,omitempty" yaml:"access,omitempty"`
	Defaults *ReaderDefaults `json:"defaults,omitempty" yaml:"defaults,omitempty"`
}

type HTTPConnection struct {
	ConnectionSpecBase
	Type     string          `json:"type" yaml:"type"`
	Access   *PublicAccess   `json:"access,omitempty" yaml:"access,omitempty"`
	Defaults *ReaderDefaults `json:"defaults,omitempty" yaml:"defaults,omitempty"`
}

type IcebergReaderOptions struct {
	Snapshot *string `json:"snapshot,omitempty" yaml:"snapshot,omitempty"`
}

type InferredSourceSchema struct {
	Mode string `json:"mode" yaml:"mode"`
}

type JSONReaderOptions struct {
	Format       *string `json:"format,omitempty" yaml:"format,omitempty"`
	MaximumDepth *int32  `json:"maximumDepth,omitempty" yaml:"maximumDepth,omitempty"`
}

type LanceReaderOptions struct {
	Version *string `json:"version,omitempty" yaml:"version,omitempty"`
}

type ManagedConnection struct {
	ConnectionSpecBase
	Type     string          `json:"type" yaml:"type"`
	Access   *PublicAccess   `json:"access,omitempty" yaml:"access,omitempty"`
	Defaults *ReaderDefaults `json:"defaults,omitempty" yaml:"defaults,omitempty"`
}

type Model struct {
	APIVersion string           `json:"apiVersion" yaml:"apiVersion"`
	Kind       string           `json:"kind" yaml:"kind"`
	Metadata   ResourceMetadata `json:"metadata" yaml:"metadata"`
	AiContext  *AIContext       `json:"aiContext,omitempty" yaml:"aiContext,omitempty"`
	Spec       ModelSpec        `json:"spec" yaml:"spec"`
}

type ModelCheckVariant interface {
	isModelCheckVariant()
}

type ModelCheck struct {
	Value ModelCheckVariant
}

func (*ModelCheckAcceptedValuesVariant) isModelCheckVariant() {}
func (*ModelCheckNonNullVariant) isModelCheckVariant()        {}
func (*ModelCheckRelationshipVariant) isModelCheckVariant()   {}
func (*ModelCheckRowCountVariant) isModelCheckVariant()       {}
func (*ModelCheckUniqueVariant) isModelCheckVariant()         {}

func (value ModelCheck) MarshalJSON() ([]byte, error) {
	switch variant := value.Value.(type) {
	case *ModelCheckAcceptedValuesVariant:
		if variant == nil {
			return nil, fmt.Errorf("ModelCheck variant is nil")
		}
		return json.Marshal(variant)
	case *ModelCheckNonNullVariant:
		if variant == nil {
			return nil, fmt.Errorf("ModelCheck variant is nil")
		}
		return json.Marshal(variant)
	case *ModelCheckRelationshipVariant:
		if variant == nil {
			return nil, fmt.Errorf("ModelCheck variant is nil")
		}
		return json.Marshal(variant)
	case *ModelCheckRowCountVariant:
		if variant == nil {
			return nil, fmt.Errorf("ModelCheck variant is nil")
		}
		return json.Marshal(variant)
	case *ModelCheckUniqueVariant:
		if variant == nil {
			return nil, fmt.Errorf("ModelCheck variant is nil")
		}
		return json.Marshal(variant)
	case nil:
		return nil, fmt.Errorf("ModelCheck variant is required")
	default:
		return nil, fmt.Errorf("unsupported ModelCheck variant %T", variant)
	}
}

func (value *ModelCheck) UnmarshalJSON(data []byte) error {
	if value == nil {
		return fmt.Errorf("cannot unmarshal ModelCheck into nil receiver")
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return fmt.Errorf("decode ModelCheck object: %w", err)
	}
	var tag struct {
		Value string `json:"type"`
	}
	if err := json.Unmarshal(data, &tag); err != nil {
		return fmt.Errorf("decode ModelCheck discriminator: %w", err)
	}
	if tag.Value == "" {
		return fmt.Errorf("ModelCheck discriminator type is required")
	}
	decode := func(dest any) error {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		return decoder.Decode(dest)
	}
	switch tag.Value {
	case "accepted_values":
		if _, ok := fields["field"]; !ok {
			return fmt.Errorf("decode ModelCheck variant %q: required property field is missing", tag.Value)
		}
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ModelCheck variant %q: required property type is missing", tag.Value)
		}
		if _, ok := fields["values"]; !ok {
			return fmt.Errorf("decode ModelCheck variant %q: required property values is missing", tag.Value)
		}
		var variant ModelCheckAcceptedValuesVariant
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ModelCheck variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "non_null":
		if _, ok := fields["field"]; !ok {
			return fmt.Errorf("decode ModelCheck variant %q: required property field is missing", tag.Value)
		}
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ModelCheck variant %q: required property type is missing", tag.Value)
		}
		var variant ModelCheckNonNullVariant
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ModelCheck variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "relationship":
		if _, ok := fields["field"]; !ok {
			return fmt.Errorf("decode ModelCheck variant %q: required property field is missing", tag.Value)
		}
		if _, ok := fields["to"]; !ok {
			return fmt.Errorf("decode ModelCheck variant %q: required property to is missing", tag.Value)
		}
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ModelCheck variant %q: required property type is missing", tag.Value)
		}
		var variant ModelCheckRelationshipVariant
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ModelCheck variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "row_count":
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ModelCheck variant %q: required property type is missing", tag.Value)
		}
		var variant ModelCheckRowCountVariant
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ModelCheck variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "unique":
		if _, ok := fields["fields"]; !ok {
			return fmt.Errorf("decode ModelCheck variant %q: required property fields is missing", tag.Value)
		}
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ModelCheck variant %q: required property type is missing", tag.Value)
		}
		var variant ModelCheckUniqueVariant
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ModelCheck variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	default:
		return fmt.Errorf("unknown ModelCheck discriminator %q", tag.Value)
	}
	return nil
}

type ModelCheckVisitor interface {
	VisitModelCheckAcceptedValuesVariant(*ModelCheckAcceptedValuesVariant) error
	VisitModelCheckNonNullVariant(*ModelCheckNonNullVariant) error
	VisitModelCheckRelationshipVariant(*ModelCheckRelationshipVariant) error
	VisitModelCheckRowCountVariant(*ModelCheckRowCountVariant) error
	VisitModelCheckUniqueVariant(*ModelCheckUniqueVariant) error
}

func (value *ModelCheck) Visit(visitor ModelCheckVisitor) error {
	if value == nil {
		return fmt.Errorf("cannot visit nil ModelCheck")
	}
	if visitor == nil {
		return fmt.Errorf("ModelCheck visitor is required")
	}
	switch variant := value.Value.(type) {
	case *ModelCheckAcceptedValuesVariant:
		if variant == nil {
			return fmt.Errorf("ModelCheck variant is nil")
		}
		return visitor.VisitModelCheckAcceptedValuesVariant(variant)
	case *ModelCheckNonNullVariant:
		if variant == nil {
			return fmt.Errorf("ModelCheck variant is nil")
		}
		return visitor.VisitModelCheckNonNullVariant(variant)
	case *ModelCheckRelationshipVariant:
		if variant == nil {
			return fmt.Errorf("ModelCheck variant is nil")
		}
		return visitor.VisitModelCheckRelationshipVariant(variant)
	case *ModelCheckRowCountVariant:
		if variant == nil {
			return fmt.Errorf("ModelCheck variant is nil")
		}
		return visitor.VisitModelCheckRowCountVariant(variant)
	case *ModelCheckUniqueVariant:
		if variant == nil {
			return fmt.Errorf("ModelCheck variant is nil")
		}
		return visitor.VisitModelCheckUniqueVariant(variant)
	case nil:
		return fmt.Errorf("ModelCheck variant is required")
	default:
		return fmt.Errorf("unsupported ModelCheck variant %T", variant)
	}
}

func (value *ModelCheck) Type() (string, error) {
	if value == nil {
		return "", fmt.Errorf("cannot inspect nil ModelCheck")
	}
	switch variant := value.Value.(type) {
	case *ModelCheckAcceptedValuesVariant:
		if variant == nil {
			return "", fmt.Errorf("ModelCheck variant is nil")
		}
		return "accepted_values", nil
	case *ModelCheckNonNullVariant:
		if variant == nil {
			return "", fmt.Errorf("ModelCheck variant is nil")
		}
		return "non_null", nil
	case *ModelCheckRelationshipVariant:
		if variant == nil {
			return "", fmt.Errorf("ModelCheck variant is nil")
		}
		return "relationship", nil
	case *ModelCheckRowCountVariant:
		if variant == nil {
			return "", fmt.Errorf("ModelCheck variant is nil")
		}
		return "row_count", nil
	case *ModelCheckUniqueVariant:
		if variant == nil {
			return "", fmt.Errorf("ModelCheck variant is nil")
		}
		return "unique", nil
	case nil:
		return "", fmt.Errorf("ModelCheck variant is required")
	default:
		return "", fmt.Errorf("unsupported ModelCheck variant %T", variant)
	}
}

type ModelCheckAcceptedValuesVariant struct {
	AcceptedValuesModelCheck
	Type string `json:"type" yaml:"type"`
}

type ModelCheckNonNullVariant struct {
	NonNullModelCheck
	Type string `json:"type" yaml:"type"`
}

type ModelCheckRelationshipVariant struct {
	RelationshipModelCheck
	Type string `json:"type" yaml:"type"`
}

type ModelCheckRowCountVariant struct {
	RowCountModelCheck
	Type string `json:"type" yaml:"type"`
}

type ModelCheckUniqueVariant struct {
	UniqueModelCheck
	Type string `json:"type" yaml:"type"`
}

type ModelDefinitionVariant interface {
	isModelDefinitionVariant()
}

type ModelDefinition struct {
	Value ModelDefinitionVariant
}

func (*DirectModelDefinition) isModelDefinitionVariant() {}
func (*SQLModelDefinition) isModelDefinitionVariant()    {}

func (value ModelDefinition) MarshalJSON() ([]byte, error) {
	switch variant := value.Value.(type) {
	case *DirectModelDefinition:
		if variant == nil {
			return nil, fmt.Errorf("ModelDefinition variant is nil")
		}
		return json.Marshal(variant)
	case *SQLModelDefinition:
		if variant == nil {
			return nil, fmt.Errorf("ModelDefinition variant is nil")
		}
		return json.Marshal(variant)
	case nil:
		return nil, fmt.Errorf("ModelDefinition variant is required")
	default:
		return nil, fmt.Errorf("unsupported ModelDefinition variant %T", variant)
	}
}

func (value *ModelDefinition) UnmarshalJSON(data []byte) error {
	if value == nil {
		return fmt.Errorf("cannot unmarshal ModelDefinition into nil receiver")
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return fmt.Errorf("decode ModelDefinition object: %w", err)
	}
	var tag struct {
		Value string `json:"type"`
	}
	if err := json.Unmarshal(data, &tag); err != nil {
		return fmt.Errorf("decode ModelDefinition discriminator: %w", err)
	}
	if tag.Value == "" {
		return fmt.Errorf("ModelDefinition discriminator type is required")
	}
	decode := func(dest any) error {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		return decoder.Decode(dest)
	}
	switch tag.Value {
	case "direct":
		if _, ok := fields["source"]; !ok {
			return fmt.Errorf("decode ModelDefinition variant %q: required property source is missing", tag.Value)
		}
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ModelDefinition variant %q: required property type is missing", tag.Value)
		}
		var variant DirectModelDefinition
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ModelDefinition variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "sql":
		if _, ok := fields["sql"]; !ok {
			return fmt.Errorf("decode ModelDefinition variant %q: required property sql is missing", tag.Value)
		}
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode ModelDefinition variant %q: required property type is missing", tag.Value)
		}
		var variant SQLModelDefinition
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode ModelDefinition variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	default:
		return fmt.Errorf("unknown ModelDefinition discriminator %q", tag.Value)
	}
	return nil
}

type ModelDefinitionVisitor interface {
	VisitDirectModelDefinition(*DirectModelDefinition) error
	VisitSQLModelDefinition(*SQLModelDefinition) error
}

func (value *ModelDefinition) Visit(visitor ModelDefinitionVisitor) error {
	if value == nil {
		return fmt.Errorf("cannot visit nil ModelDefinition")
	}
	if visitor == nil {
		return fmt.Errorf("ModelDefinition visitor is required")
	}
	switch variant := value.Value.(type) {
	case *DirectModelDefinition:
		if variant == nil {
			return fmt.Errorf("ModelDefinition variant is nil")
		}
		return visitor.VisitDirectModelDefinition(variant)
	case *SQLModelDefinition:
		if variant == nil {
			return fmt.Errorf("ModelDefinition variant is nil")
		}
		return visitor.VisitSQLModelDefinition(variant)
	case nil:
		return fmt.Errorf("ModelDefinition variant is required")
	default:
		return fmt.Errorf("unsupported ModelDefinition variant %T", variant)
	}
}

func (value *ModelDefinition) Type() (string, error) {
	if value == nil {
		return "", fmt.Errorf("cannot inspect nil ModelDefinition")
	}
	switch variant := value.Value.(type) {
	case *DirectModelDefinition:
		if variant == nil {
			return "", fmt.Errorf("ModelDefinition variant is nil")
		}
		return "direct", nil
	case *SQLModelDefinition:
		if variant == nil {
			return "", fmt.Errorf("ModelDefinition variant is nil")
		}
		return "sql", nil
	case nil:
		return "", fmt.Errorf("ModelDefinition variant is required")
	default:
		return "", fmt.Errorf("unsupported ModelDefinition variant %T", variant)
	}
}

func (value *ModelDefinition) Base() (*ModelDefinitionBase, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot inspect nil ModelDefinition")
	}
	switch variant := value.Value.(type) {
	case *DirectModelDefinition:
		if variant == nil {
			return nil, fmt.Errorf("ModelDefinition variant is nil")
		}
		return &variant.ModelDefinitionBase, nil
	case *SQLModelDefinition:
		if variant == nil {
			return nil, fmt.Errorf("ModelDefinition variant is nil")
		}
		return &variant.ModelDefinitionBase, nil
	case nil:
		return nil, fmt.Errorf("ModelDefinition variant is required")
	default:
		return nil, fmt.Errorf("unsupported ModelDefinition variant %T", variant)
	}
}

type ModelDefinitionBase struct {
	Type string `json:"type" yaml:"type"`
}

type ModelEntity struct {
	Type        string     `json:"type" yaml:"type"`
	Fields      []string   `json:"fields" yaml:"fields"`
	Description *string    `json:"description,omitempty" yaml:"description,omitempty"`
	AiContext   *AIContext `json:"aiContext,omitempty" yaml:"aiContext,omitempty"`
}

type ModelField struct {
	Datatype    string     `json:"datatype" yaml:"datatype"`
	Label       *string    `json:"label,omitempty" yaml:"label,omitempty"`
	Description *string    `json:"description,omitempty" yaml:"description,omitempty"`
	AiContext   *AIContext `json:"aiContext,omitempty" yaml:"aiContext,omitempty"`
}

type ModelGrain struct {
	Entity string `json:"entity" yaml:"entity"`
}

type ModelSpec struct {
	Definition ModelDefinition        `json:"definition" yaml:"definition"`
	Entities   map[string]ModelEntity `json:"entities" yaml:"entities"`
	Grain      ModelGrain             `json:"grain" yaml:"grain"`
	Fields     map[string]ModelField  `json:"fields" yaml:"fields"`
	Checks     *[]ModelCheck          `json:"checks,omitempty" yaml:"checks,omitempty"`
}

type MySQLConnection struct {
	ConnectionSpecBase
	Type string `json:"type" yaml:"type"`
}

type NonNullModelCheck struct {
	Type     string  `json:"type" yaml:"type"`
	Field    string  `json:"field" yaml:"field"`
	Severity *string `json:"severity,omitempty" yaml:"severity,omitempty"`
}

type ParquetReaderOptions struct {
	HivePartitioning *bool `json:"hivePartitioning,omitempty" yaml:"hivePartitioning,omitempty"`
	UnionByName      *bool `json:"unionByName,omitempty" yaml:"unionByName,omitempty"`
}

type PathSourceLocation struct {
	Type    string             `json:"type" yaml:"type"`
	Path    string             `json:"path" yaml:"path"`
	Format  string             `json:"format" yaml:"format"`
	Options *SourcePathOptions `json:"options,omitempty" yaml:"options,omitempty"`
}

type PostgresConnection struct {
	ConnectionSpecBase
	Type string `json:"type" yaml:"type"`
}

type PublicAccess string

const (
	PublicAccessPublic PublicAccess = "public"
)

type QuackConnection struct {
	ConnectionSpecBase
	Type string `json:"type" yaml:"type"`
}

type R2Connection struct {
	ConnectionSpecBase
	Type     string          `json:"type" yaml:"type"`
	Access   *PublicAccess   `json:"access,omitempty" yaml:"access,omitempty"`
	Defaults *ReaderDefaults `json:"defaults,omitempty" yaml:"defaults,omitempty"`
}

type ReaderDefaults struct {
	Csv     *CSVReaderOptions     `json:"csv,omitempty" yaml:"csv,omitempty"`
	JSON    *JSONReaderOptions    `json:"json,omitempty" yaml:"json,omitempty"`
	Parquet *ParquetReaderOptions `json:"parquet,omitempty" yaml:"parquet,omitempty"`
	Excel   *ExcelReaderOptions   `json:"excel,omitempty" yaml:"excel,omitempty"`
	Text    *TextReaderOptions    `json:"text,omitempty" yaml:"text,omitempty"`
	Blob    *BlobReaderOptions    `json:"blob,omitempty" yaml:"blob,omitempty"`
	Vortex  *VortexReaderOptions  `json:"vortex,omitempty" yaml:"vortex,omitempty"`
	Delta   *DeltaReaderOptions   `json:"delta,omitempty" yaml:"delta,omitempty"`
	Iceberg *IcebergReaderOptions `json:"iceberg,omitempty" yaml:"iceberg,omitempty"`
	Lance   *LanceReaderOptions   `json:"lance,omitempty" yaml:"lance,omitempty"`
}

type RelationSourceLocation struct {
	Catalog *string `json:"catalog,omitempty" yaml:"catalog,omitempty"`
	Schema  *string `json:"schema,omitempty" yaml:"schema,omitempty"`
	Name    string  `json:"name" yaml:"name"`
}

type RelationshipModelCheck struct {
	Type     string  `json:"type" yaml:"type"`
	Field    string  `json:"field" yaml:"field"`
	To       string  `json:"to" yaml:"to"`
	Severity *string `json:"severity,omitempty" yaml:"severity,omitempty"`
}

type ResourceMetadata struct {
	ID            string              `json:"id" yaml:"id"`
	Name          string              `json:"name" yaml:"name"`
	DisplayName   *string             `json:"displayName,omitempty" yaml:"displayName,omitempty"`
	Description   *string             `json:"description,omitempty" yaml:"description,omitempty"`
	Owner         *string             `json:"owner,omitempty" yaml:"owner,omitempty"`
	Domain        *string             `json:"domain,omitempty" yaml:"domain,omitempty"`
	Tags          *[]string           `json:"tags,omitempty" yaml:"tags,omitempty"`
	Documentation *string             `json:"documentation,omitempty" yaml:"documentation,omitempty"`
	Provenance    *ResourceProvenance `json:"provenance,omitempty" yaml:"provenance,omitempty"`
}

type ResourceProvenance struct {
	Origin *string `json:"origin,omitempty" yaml:"origin,omitempty"`
	Path   *string `json:"path,omitempty" yaml:"path,omitempty"`
	Source *string `json:"source,omitempty" yaml:"source,omitempty"`
}

type RevisionFreshness struct {
	Basis        string             `json:"basis" yaml:"basis"`
	Revision     string             `json:"revision" yaml:"revision"`
	WarningAfter *FreshnessDuration `json:"warningAfter,omitempty" yaml:"warningAfter,omitempty"`
	ErrorAfter   *FreshnessDuration `json:"errorAfter,omitempty" yaml:"errorAfter,omitempty"`
}

type RowCountModelCheck struct {
	Type     string  `json:"type" yaml:"type"`
	Minimum  *int64  `json:"minimum,omitempty" yaml:"minimum,omitempty"`
	Maximum  *int64  `json:"maximum,omitempty" yaml:"maximum,omitempty"`
	Severity *string `json:"severity,omitempty" yaml:"severity,omitempty"`
}

type S3Connection struct {
	ConnectionSpecBase
	Type     string          `json:"type" yaml:"type"`
	Access   *PublicAccess   `json:"access,omitempty" yaml:"access,omitempty"`
	Defaults *ReaderDefaults `json:"defaults,omitempty" yaml:"defaults,omitempty"`
}

type SQLModelDefinition struct {
	ModelDefinitionBase
	Type string `json:"type" yaml:"type"`
	SQL  string `json:"sql" yaml:"sql"`
}

type SQLiteConnection struct {
	ConnectionSpecBase
	Type string `json:"type" yaml:"type"`
}

type Source struct {
	APIVersion string           `json:"apiVersion" yaml:"apiVersion"`
	Kind       string           `json:"kind" yaml:"kind"`
	Metadata   ResourceMetadata `json:"metadata" yaml:"metadata"`
	Spec       SourceSpec       `json:"spec" yaml:"spec"`
}

type SourceFreshnessVariant interface {
	isSourceFreshnessVariant()
}

type SourceFreshness struct {
	Value SourceFreshnessVariant
}

func (*SourceFreshnessFieldVariant) isSourceFreshnessVariant()    {}
func (*SourceFreshnessRevisionVariant) isSourceFreshnessVariant() {}

func (value SourceFreshness) MarshalJSON() ([]byte, error) {
	switch variant := value.Value.(type) {
	case *SourceFreshnessFieldVariant:
		if variant == nil {
			return nil, fmt.Errorf("SourceFreshness variant is nil")
		}
		return json.Marshal(variant)
	case *SourceFreshnessRevisionVariant:
		if variant == nil {
			return nil, fmt.Errorf("SourceFreshness variant is nil")
		}
		return json.Marshal(variant)
	case nil:
		return nil, fmt.Errorf("SourceFreshness variant is required")
	default:
		return nil, fmt.Errorf("unsupported SourceFreshness variant %T", variant)
	}
}

func (value *SourceFreshness) UnmarshalJSON(data []byte) error {
	if value == nil {
		return fmt.Errorf("cannot unmarshal SourceFreshness into nil receiver")
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return fmt.Errorf("decode SourceFreshness object: %w", err)
	}
	var tag struct {
		Value string `json:"basis"`
	}
	if err := json.Unmarshal(data, &tag); err != nil {
		return fmt.Errorf("decode SourceFreshness discriminator: %w", err)
	}
	if tag.Value == "" {
		return fmt.Errorf("SourceFreshness discriminator basis is required")
	}
	decode := func(dest any) error {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		return decoder.Decode(dest)
	}
	switch tag.Value {
	case "field":
		if _, ok := fields["basis"]; !ok {
			return fmt.Errorf("decode SourceFreshness variant %q: required property basis is missing", tag.Value)
		}
		if _, ok := fields["field"]; !ok {
			return fmt.Errorf("decode SourceFreshness variant %q: required property field is missing", tag.Value)
		}
		var variant SourceFreshnessFieldVariant
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode SourceFreshness variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "revision":
		if _, ok := fields["basis"]; !ok {
			return fmt.Errorf("decode SourceFreshness variant %q: required property basis is missing", tag.Value)
		}
		if _, ok := fields["revision"]; !ok {
			return fmt.Errorf("decode SourceFreshness variant %q: required property revision is missing", tag.Value)
		}
		var variant SourceFreshnessRevisionVariant
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode SourceFreshness variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	default:
		return fmt.Errorf("unknown SourceFreshness discriminator %q", tag.Value)
	}
	return nil
}

type SourceFreshnessVisitor interface {
	VisitSourceFreshnessFieldVariant(*SourceFreshnessFieldVariant) error
	VisitSourceFreshnessRevisionVariant(*SourceFreshnessRevisionVariant) error
}

func (value *SourceFreshness) Visit(visitor SourceFreshnessVisitor) error {
	if value == nil {
		return fmt.Errorf("cannot visit nil SourceFreshness")
	}
	if visitor == nil {
		return fmt.Errorf("SourceFreshness visitor is required")
	}
	switch variant := value.Value.(type) {
	case *SourceFreshnessFieldVariant:
		if variant == nil {
			return fmt.Errorf("SourceFreshness variant is nil")
		}
		return visitor.VisitSourceFreshnessFieldVariant(variant)
	case *SourceFreshnessRevisionVariant:
		if variant == nil {
			return fmt.Errorf("SourceFreshness variant is nil")
		}
		return visitor.VisitSourceFreshnessRevisionVariant(variant)
	case nil:
		return fmt.Errorf("SourceFreshness variant is required")
	default:
		return fmt.Errorf("unsupported SourceFreshness variant %T", variant)
	}
}

func (value *SourceFreshness) Basis() (string, error) {
	if value == nil {
		return "", fmt.Errorf("cannot inspect nil SourceFreshness")
	}
	switch variant := value.Value.(type) {
	case *SourceFreshnessFieldVariant:
		if variant == nil {
			return "", fmt.Errorf("SourceFreshness variant is nil")
		}
		return "field", nil
	case *SourceFreshnessRevisionVariant:
		if variant == nil {
			return "", fmt.Errorf("SourceFreshness variant is nil")
		}
		return "revision", nil
	case nil:
		return "", fmt.Errorf("SourceFreshness variant is required")
	default:
		return "", fmt.Errorf("unsupported SourceFreshness variant %T", variant)
	}
}

type SourceFreshnessFieldVariant struct {
	FieldFreshness
	Basis string `json:"basis" yaml:"basis"`
}

type SourceFreshnessRevisionVariant struct {
	RevisionFreshness
	Basis string `json:"basis" yaml:"basis"`
}

type SourceLocationVariant interface {
	isSourceLocationVariant()
}

type SourceLocation struct {
	Value SourceLocationVariant
}

func (*SourceLocationPathVariant) isSourceLocationVariant()     {}
func (*SourceLocationRelationVariant) isSourceLocationVariant() {}

func (value SourceLocation) MarshalJSON() ([]byte, error) {
	switch variant := value.Value.(type) {
	case *SourceLocationPathVariant:
		if variant == nil {
			return nil, fmt.Errorf("SourceLocation variant is nil")
		}
		return json.Marshal(variant)
	case *SourceLocationRelationVariant:
		if variant == nil {
			return nil, fmt.Errorf("SourceLocation variant is nil")
		}
		return json.Marshal(variant)
	case nil:
		return nil, fmt.Errorf("SourceLocation variant is required")
	default:
		return nil, fmt.Errorf("unsupported SourceLocation variant %T", variant)
	}
}

func (value *SourceLocation) UnmarshalJSON(data []byte) error {
	if value == nil {
		return fmt.Errorf("cannot unmarshal SourceLocation into nil receiver")
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return fmt.Errorf("decode SourceLocation object: %w", err)
	}
	var tag struct {
		Value string `json:"type"`
	}
	if err := json.Unmarshal(data, &tag); err != nil {
		return fmt.Errorf("decode SourceLocation discriminator: %w", err)
	}
	if tag.Value == "" {
		return fmt.Errorf("SourceLocation discriminator type is required")
	}
	decode := func(dest any) error {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		return decoder.Decode(dest)
	}
	switch tag.Value {
	case "path":
		if _, ok := fields["format"]; !ok {
			return fmt.Errorf("decode SourceLocation variant %q: required property format is missing", tag.Value)
		}
		if _, ok := fields["path"]; !ok {
			return fmt.Errorf("decode SourceLocation variant %q: required property path is missing", tag.Value)
		}
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode SourceLocation variant %q: required property type is missing", tag.Value)
		}
		var variant SourceLocationPathVariant
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode SourceLocation variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "relation":
		if _, ok := fields["name"]; !ok {
			return fmt.Errorf("decode SourceLocation variant %q: required property name is missing", tag.Value)
		}
		if _, ok := fields["type"]; !ok {
			return fmt.Errorf("decode SourceLocation variant %q: required property type is missing", tag.Value)
		}
		var variant SourceLocationRelationVariant
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode SourceLocation variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	default:
		return fmt.Errorf("unknown SourceLocation discriminator %q", tag.Value)
	}
	return nil
}

type SourceLocationVisitor interface {
	VisitSourceLocationPathVariant(*SourceLocationPathVariant) error
	VisitSourceLocationRelationVariant(*SourceLocationRelationVariant) error
}

func (value *SourceLocation) Visit(visitor SourceLocationVisitor) error {
	if value == nil {
		return fmt.Errorf("cannot visit nil SourceLocation")
	}
	if visitor == nil {
		return fmt.Errorf("SourceLocation visitor is required")
	}
	switch variant := value.Value.(type) {
	case *SourceLocationPathVariant:
		if variant == nil {
			return fmt.Errorf("SourceLocation variant is nil")
		}
		return visitor.VisitSourceLocationPathVariant(variant)
	case *SourceLocationRelationVariant:
		if variant == nil {
			return fmt.Errorf("SourceLocation variant is nil")
		}
		return visitor.VisitSourceLocationRelationVariant(variant)
	case nil:
		return fmt.Errorf("SourceLocation variant is required")
	default:
		return fmt.Errorf("unsupported SourceLocation variant %T", variant)
	}
}

func (value *SourceLocation) Type() (string, error) {
	if value == nil {
		return "", fmt.Errorf("cannot inspect nil SourceLocation")
	}
	switch variant := value.Value.(type) {
	case *SourceLocationPathVariant:
		if variant == nil {
			return "", fmt.Errorf("SourceLocation variant is nil")
		}
		return "path", nil
	case *SourceLocationRelationVariant:
		if variant == nil {
			return "", fmt.Errorf("SourceLocation variant is nil")
		}
		return "relation", nil
	case nil:
		return "", fmt.Errorf("SourceLocation variant is required")
	default:
		return "", fmt.Errorf("unsupported SourceLocation variant %T", variant)
	}
}

type SourceLocationPathVariant struct {
	PathSourceLocation
	Type string `json:"type" yaml:"type"`
}

type SourceLocationRelationVariant struct {
	RelationSourceLocation
	Type string `json:"type" yaml:"type"`
}

type SourcePathOptions struct {
	Header           *bool   `json:"header,omitempty" yaml:"header,omitempty"`
	Delimiter        *string `json:"delimiter,omitempty" yaml:"delimiter,omitempty"`
	Quote            *string `json:"quote,omitempty" yaml:"quote,omitempty"`
	Escape           *string `json:"escape,omitempty" yaml:"escape,omitempty"`
	NullString       *string `json:"nullString,omitempty" yaml:"nullString,omitempty"`
	Format           *string `json:"format,omitempty" yaml:"format,omitempty"`
	MaximumDepth     *int32  `json:"maximumDepth,omitempty" yaml:"maximumDepth,omitempty"`
	HivePartitioning *bool   `json:"hivePartitioning,omitempty" yaml:"hivePartitioning,omitempty"`
	UnionByName      *bool   `json:"unionByName,omitempty" yaml:"unionByName,omitempty"`
	Sheet            *string `json:"sheet,omitempty" yaml:"sheet,omitempty"`
	Compression      *string `json:"compression,omitempty" yaml:"compression,omitempty"`
	Version          *string `json:"version,omitempty" yaml:"version,omitempty"`
	Snapshot         *string `json:"snapshot,omitempty" yaml:"snapshot,omitempty"`
}

type SourceSchemaVariant interface {
	isSourceSchemaVariant()
}

type SourceSchema struct {
	Value SourceSchemaVariant
}

func (*SourceSchemaCompatibleVariant) isSourceSchemaVariant() {}
func (*SourceSchemaInferredVariant) isSourceSchemaVariant()   {}
func (*SourceSchemaStrictVariant) isSourceSchemaVariant()     {}

func (value SourceSchema) MarshalJSON() ([]byte, error) {
	switch variant := value.Value.(type) {
	case *SourceSchemaCompatibleVariant:
		if variant == nil {
			return nil, fmt.Errorf("SourceSchema variant is nil")
		}
		return json.Marshal(variant)
	case *SourceSchemaInferredVariant:
		if variant == nil {
			return nil, fmt.Errorf("SourceSchema variant is nil")
		}
		return json.Marshal(variant)
	case *SourceSchemaStrictVariant:
		if variant == nil {
			return nil, fmt.Errorf("SourceSchema variant is nil")
		}
		return json.Marshal(variant)
	case nil:
		return nil, fmt.Errorf("SourceSchema variant is required")
	default:
		return nil, fmt.Errorf("unsupported SourceSchema variant %T", variant)
	}
}

func (value *SourceSchema) UnmarshalJSON(data []byte) error {
	if value == nil {
		return fmt.Errorf("cannot unmarshal SourceSchema into nil receiver")
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return fmt.Errorf("decode SourceSchema object: %w", err)
	}
	var tag struct {
		Value string `json:"mode"`
	}
	if err := json.Unmarshal(data, &tag); err != nil {
		return fmt.Errorf("decode SourceSchema discriminator: %w", err)
	}
	if tag.Value == "" {
		return fmt.Errorf("SourceSchema discriminator mode is required")
	}
	decode := func(dest any) error {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		return decoder.Decode(dest)
	}
	switch tag.Value {
	case "compatible":
		if _, ok := fields["fields"]; !ok {
			return fmt.Errorf("decode SourceSchema variant %q: required property fields is missing", tag.Value)
		}
		if _, ok := fields["mode"]; !ok {
			return fmt.Errorf("decode SourceSchema variant %q: required property mode is missing", tag.Value)
		}
		var variant SourceSchemaCompatibleVariant
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode SourceSchema variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "inferred":
		if _, ok := fields["mode"]; !ok {
			return fmt.Errorf("decode SourceSchema variant %q: required property mode is missing", tag.Value)
		}
		var variant SourceSchemaInferredVariant
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode SourceSchema variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	case "strict":
		if _, ok := fields["fields"]; !ok {
			return fmt.Errorf("decode SourceSchema variant %q: required property fields is missing", tag.Value)
		}
		if _, ok := fields["mode"]; !ok {
			return fmt.Errorf("decode SourceSchema variant %q: required property mode is missing", tag.Value)
		}
		var variant SourceSchemaStrictVariant
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode SourceSchema variant %q: %w", tag.Value, err)
		}
		value.Value = &variant
	default:
		return fmt.Errorf("unknown SourceSchema discriminator %q", tag.Value)
	}
	return nil
}

type SourceSchemaVisitor interface {
	VisitSourceSchemaCompatibleVariant(*SourceSchemaCompatibleVariant) error
	VisitSourceSchemaInferredVariant(*SourceSchemaInferredVariant) error
	VisitSourceSchemaStrictVariant(*SourceSchemaStrictVariant) error
}

func (value *SourceSchema) Visit(visitor SourceSchemaVisitor) error {
	if value == nil {
		return fmt.Errorf("cannot visit nil SourceSchema")
	}
	if visitor == nil {
		return fmt.Errorf("SourceSchema visitor is required")
	}
	switch variant := value.Value.(type) {
	case *SourceSchemaCompatibleVariant:
		if variant == nil {
			return fmt.Errorf("SourceSchema variant is nil")
		}
		return visitor.VisitSourceSchemaCompatibleVariant(variant)
	case *SourceSchemaInferredVariant:
		if variant == nil {
			return fmt.Errorf("SourceSchema variant is nil")
		}
		return visitor.VisitSourceSchemaInferredVariant(variant)
	case *SourceSchemaStrictVariant:
		if variant == nil {
			return fmt.Errorf("SourceSchema variant is nil")
		}
		return visitor.VisitSourceSchemaStrictVariant(variant)
	case nil:
		return fmt.Errorf("SourceSchema variant is required")
	default:
		return fmt.Errorf("unsupported SourceSchema variant %T", variant)
	}
}

func (value *SourceSchema) Mode() (string, error) {
	if value == nil {
		return "", fmt.Errorf("cannot inspect nil SourceSchema")
	}
	switch variant := value.Value.(type) {
	case *SourceSchemaCompatibleVariant:
		if variant == nil {
			return "", fmt.Errorf("SourceSchema variant is nil")
		}
		return "compatible", nil
	case *SourceSchemaInferredVariant:
		if variant == nil {
			return "", fmt.Errorf("SourceSchema variant is nil")
		}
		return "inferred", nil
	case *SourceSchemaStrictVariant:
		if variant == nil {
			return "", fmt.Errorf("SourceSchema variant is nil")
		}
		return "strict", nil
	case nil:
		return "", fmt.Errorf("SourceSchema variant is required")
	default:
		return "", fmt.Errorf("unsupported SourceSchema variant %T", variant)
	}
}

type SourceSchemaCompatibleVariant struct {
	CompatibleSourceSchema
	Mode string `json:"mode" yaml:"mode"`
}

type SourceSchemaField struct {
	Datatype    string  `json:"datatype" yaml:"datatype"`
	Nullable    *bool   `json:"nullable,omitempty" yaml:"nullable,omitempty"`
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`
}

type SourceSchemaInferredVariant struct {
	InferredSourceSchema
	Mode string `json:"mode" yaml:"mode"`
}

type SourceSchemaStrictVariant struct {
	StrictSourceSchema
	Mode string `json:"mode" yaml:"mode"`
}

type SourceSpec struct {
	Connection string           `json:"connection" yaml:"connection"`
	Location   SourceLocation   `json:"location" yaml:"location"`
	Schema     *SourceSchema    `json:"schema,omitempty" yaml:"schema,omitempty"`
	Freshness  *SourceFreshness `json:"freshness,omitempty" yaml:"freshness,omitempty"`
}

type StrictSourceSchema struct {
	Mode   string                       `json:"mode" yaml:"mode"`
	Fields map[string]SourceSchemaField `json:"fields" yaml:"fields"`
}

type TextReaderOptions struct {
	Delimiter *string `json:"delimiter,omitempty" yaml:"delimiter,omitempty"`
	Quote     *string `json:"quote,omitempty" yaml:"quote,omitempty"`
	Header    *bool   `json:"header,omitempty" yaml:"header,omitempty"`
}

type UniqueModelCheck struct {
	Type     string   `json:"type" yaml:"type"`
	Fields   []string `json:"fields" yaml:"fields"`
	Severity *string  `json:"severity,omitempty" yaml:"severity,omitempty"`
}

type VortexReaderOptions struct {
	Version *string `json:"version,omitempty" yaml:"version,omitempty"`
}
