// Code generated by internal/project/contracts/generate. DO NOT EDIT.
package contracts

// DefaultCSVReaderOptions returns the generated, versioned defaults for csv path sources.
func DefaultCSVReaderOptions() *CSVReaderOptions {
	delimiter := ","
	escape := "\""
	header := false
	quote := "\""
	return &CSVReaderOptions{
		Delimiter: &delimiter,
		Escape:    &escape,
		Header:    &header,
		Quote:     &quote,
	}
}

// DefaultJSONReaderOptions returns the generated, versioned defaults for json path sources.
func DefaultJSONReaderOptions() *JSONReaderOptions {
	format := "auto"
	return &JSONReaderOptions{
		Format: &format,
	}
}

// DefaultParquetReaderOptions returns the generated, versioned defaults for parquet path sources.
func DefaultParquetReaderOptions() *ParquetReaderOptions {
	hivePartitioning := false
	unionByName := false
	return &ParquetReaderOptions{
		HivePartitioning: &hivePartitioning,
		UnionByName:      &unionByName,
	}
}

// DefaultExcelReaderOptions returns the generated, versioned defaults for excel path sources.
func DefaultExcelReaderOptions() *ExcelReaderOptions {
	header := true
	return &ExcelReaderOptions{
		Header: &header,
	}
}

// DefaultTextReaderOptions returns the generated, versioned defaults for text path sources.
func DefaultTextReaderOptions() *TextReaderOptions {
	delimiter := "\t"
	header := false
	quote := "\""
	return &TextReaderOptions{
		Delimiter: &delimiter,
		Header:    &header,
		Quote:     &quote,
	}
}

// DefaultBlobReaderOptions returns the generated, versioned defaults for blob path sources.
func DefaultBlobReaderOptions() *BlobReaderOptions {
	compression := "auto"
	return &BlobReaderOptions{
		Compression: &compression,
	}
}

// DefaultVortexReaderOptions returns the generated, versioned defaults for vortex path sources.
func DefaultVortexReaderOptions() *VortexReaderOptions {
	return nil
}

// DefaultDeltaReaderOptions returns the generated, versioned defaults for delta path sources.
func DefaultDeltaReaderOptions() *DeltaReaderOptions {
	return nil
}

// DefaultIcebergReaderOptions returns the generated, versioned defaults for iceberg path sources.
func DefaultIcebergReaderOptions() *IcebergReaderOptions {
	return nil
}

// PathFormatNames is generated from PathSourceLocation.format.
var PathFormatNames = []string{"csv", "json", "parquet", "excel", "text", "blob", "vortex", "delta", "iceberg", "lance"}

// FormatProfile is generated from x-leapview-format metadata.
type FormatProfile struct {
	Name                         string
	Extensions                   []string
	ScanKind                     string
	ScanFunction                 string
	RequiredExtension            string
	SourceSecretType             string
	SourceDataIdentityCapability SourceDataIdentityCapability
	TableLike                    bool
	AllowsOptions                bool
}

var FormatRegistry = []FormatProfile{
	{Name: "csv", Extensions: []string{".csv", ".csv.gz"}, ScanKind: "table_function", ScanFunction: "read_csv", RequiredExtension: "", SourceSecretType: "", SourceDataIdentityCapability: SourceDataIdentityCapability("unavailable"), TableLike: false, AllowsOptions: true},
	{Name: "json", Extensions: []string{".json", ".jsonl", ".ndjson"}, ScanKind: "table_function", ScanFunction: "read_json", RequiredExtension: "", SourceSecretType: "", SourceDataIdentityCapability: SourceDataIdentityCapability("unavailable"), TableLike: false, AllowsOptions: true},
	{Name: "parquet", Extensions: []string{".parquet"}, ScanKind: "table_function", ScanFunction: "read_parquet", RequiredExtension: "", SourceSecretType: "", SourceDataIdentityCapability: SourceDataIdentityCapability("unavailable"), TableLike: false, AllowsOptions: true},
	{Name: "excel", Extensions: []string{".xlsx"}, ScanKind: "table_function", ScanFunction: "read_xlsx", RequiredExtension: "excel", SourceSecretType: "", SourceDataIdentityCapability: SourceDataIdentityCapability("unavailable"), TableLike: false, AllowsOptions: true},
	{Name: "text", Extensions: []string{".txt"}, ScanKind: "table_function", ScanFunction: "read_text", RequiredExtension: "", SourceSecretType: "", SourceDataIdentityCapability: SourceDataIdentityCapability("unavailable"), TableLike: false, AllowsOptions: true},
	{Name: "blob", Extensions: []string{".blob"}, ScanKind: "table_function", ScanFunction: "read_blob", RequiredExtension: "", SourceSecretType: "", SourceDataIdentityCapability: SourceDataIdentityCapability("unavailable"), TableLike: false, AllowsOptions: true},
	{Name: "vortex", Extensions: []string{".vortex"}, ScanKind: "table_function", ScanFunction: "read_vortex", RequiredExtension: "vortex", SourceSecretType: "", SourceDataIdentityCapability: SourceDataIdentityCapability("unavailable"), TableLike: false, AllowsOptions: true},
	{Name: "delta", Extensions: []string{}, ScanKind: "table_function", ScanFunction: "delta_scan", RequiredExtension: "delta", SourceSecretType: "", SourceDataIdentityCapability: SourceDataIdentityCapability("unavailable"), TableLike: true, AllowsOptions: true},
	{Name: "iceberg", Extensions: []string{}, ScanKind: "table_function", ScanFunction: "iceberg_scan", RequiredExtension: "iceberg", SourceSecretType: "", SourceDataIdentityCapability: SourceDataIdentityCapability("unavailable"), TableLike: true, AllowsOptions: true},
	{Name: "lance", Extensions: []string{".lance"}, ScanKind: "replacement", ScanFunction: "", RequiredExtension: "lance", SourceSecretType: "lance", SourceDataIdentityCapability: SourceDataIdentityCapability("unavailable"), TableLike: true, AllowsOptions: false},
}
