// Code generated by internal/project/contracts/generate. DO NOT EDIT.
package contracts

import (
	"bytes"
	"encoding/json"
	"fmt"
)

func validatePathSourceOptions(format string, options *SourcePathOptions) error {
	if options == nil {
		return nil
	}
	data, err := json.Marshal(options)
	if err != nil {
		return err
	}
	switch format {
	case "csv":
		var typed CSVReaderOptions
		return decodePathSourceOptions(data, &typed)
	case "json":
		var typed JSONReaderOptions
		return decodePathSourceOptions(data, &typed)
	case "parquet":
		var typed ParquetReaderOptions
		return decodePathSourceOptions(data, &typed)
	case "excel":
		var typed ExcelReaderOptions
		return decodePathSourceOptions(data, &typed)
	case "text":
		var typed TextReaderOptions
		return decodePathSourceOptions(data, &typed)
	case "blob":
		var typed BlobReaderOptions
		return decodePathSourceOptions(data, &typed)
	case "vortex":
		var typed VortexReaderOptions
		return decodePathSourceOptions(data, &typed)
	case "delta":
		var typed DeltaReaderOptions
		return decodePathSourceOptions(data, &typed)
	case "iceberg":
		var typed IcebergReaderOptions
		return decodePathSourceOptions(data, &typed)
	case "lance":
		var typed LanceReaderOptions
		return decodePathSourceOptions(data, &typed)
	default:
		return fmt.Errorf("unsupported path source format %q", format)
	}
}

func decodePathSourceOptions(data []byte, destination any) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	return decoder.Decode(destination)
}

func (value *SourceLocationPathVariant) UnmarshalJSON(data []byte) error {
	if value == nil {
		return fmt.Errorf("cannot unmarshal SourceLocationPathVariant into nil receiver")
	}
	type plain SourceLocationPathVariant
	var decoded plain
	if err := decodePathSourceOptions(data, &decoded); err != nil {
		return err
	}
	if decoded.Type != "path" {
		return fmt.Errorf("SourceLocation path variant type must be path")
	}
	if err := validatePathSourceOptions(decoded.Format, decoded.Options); err != nil {
		return err
	}
	*value = SourceLocationPathVariant(decoded)
	return nil
}

func (value SourceLocationPathVariant) MarshalJSON() ([]byte, error) {
	if value.Type != "path" {
		return nil, fmt.Errorf("SourceLocation path variant type must be path")
	}
	if err := validatePathSourceOptions(value.Format, value.Options); err != nil {
		return nil, err
	}
	type plain SourceLocationPathVariant
	return json.Marshal(plain(value))
}
