// Code generated by apigen data-contract Go emitter. DO NOT EDIT.
package contracts

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

type ManualPipelineSpec struct {
	Selection PipelineSelection `json:"selection" yaml:"selection"`
}

type PipelineApiVersion string

const (
	PipelineApiVersionLeapviewDevV1 PipelineApiVersion = "leapview.dev/v1"
)

type PipelineConcurrencyPolicy string

const (
	PipelineConcurrencyPolicyForbid  PipelineConcurrencyPolicy = "Forbid"
	PipelineConcurrencyPolicyReplace PipelineConcurrencyPolicy = "Replace"
)

type PipelineDocument struct {
	APIVersion PipelineApiVersion   `json:"apiVersion" yaml:"apiVersion"`
	Kind       PipelineResourceKind `json:"kind" yaml:"kind"`
	Metadata   PipelineMetadata     `json:"metadata" yaml:"metadata"`
	Spec       PipelineSpec         `json:"spec" yaml:"spec"`
}

type PipelineMetadata struct {
	ID            string    `json:"id" yaml:"id"`
	Name          string    `json:"name" yaml:"name"`
	DisplayName   *string   `json:"displayName,omitempty" yaml:"displayName,omitempty"`
	Description   *string   `json:"description,omitempty" yaml:"description,omitempty"`
	Owner         *string   `json:"owner,omitempty" yaml:"owner,omitempty"`
	Domain        *string   `json:"domain,omitempty" yaml:"domain,omitempty"`
	Tags          *[]string `json:"tags,omitempty" yaml:"tags,omitempty"`
	Documentation *string   `json:"documentation,omitempty" yaml:"documentation,omitempty"`
}

type PipelineResourceKind string

const (
	PipelineResourceKindPipeline PipelineResourceKind = "Pipeline"
)

type PipelineSelection struct {
	SemanticModel string `json:"semanticModel" yaml:"semanticModel"`
}

type PipelineSpecVariant interface {
	isPipelineSpecVariant()
}

type PipelineSpec struct {
	Value PipelineSpecVariant
}

func (*ManualPipelineSpec) isPipelineSpecVariant()    {}
func (*ScheduledPipelineSpec) isPipelineSpecVariant() {}

func (value PipelineSpec) MarshalJSON() ([]byte, error) {
	switch variant := value.Value.(type) {
	case *ManualPipelineSpec:
		if variant == nil {
			return nil, fmt.Errorf("PipelineSpec variant is nil")
		}
		return json.Marshal(variant)
	case *ScheduledPipelineSpec:
		if variant == nil {
			return nil, fmt.Errorf("PipelineSpec variant is nil")
		}
		return json.Marshal(variant)
	case nil:
		return nil, fmt.Errorf("PipelineSpec variant is required")
	default:
		return nil, fmt.Errorf("unsupported PipelineSpec variant %T", variant)
	}
}

func (value *PipelineSpec) UnmarshalJSON(data []byte) error {
	if value == nil {
		return fmt.Errorf("cannot unmarshal PipelineSpec into nil receiver")
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return fmt.Errorf("decode PipelineSpec object: %w", err)
	}
	*value = PipelineSpec{}
	var matched string
	var decoded any
	var failures []string
	decode := func(dest any) error {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		return decoder.Decode(dest)
	}
	{
		valid := true
		if _, ok := fields["selection"]; !ok {
			valid = false
			failures = append(failures, "ManualPipelineSpec: required property selection is missing")
		}
		if valid {
			var candidate ManualPipelineSpec
			if err := decode(&candidate); err == nil {
				if matched != "" {
					return fmt.Errorf("decode PipelineSpec: object matches both %s and ManualPipelineSpec", matched)
				}
				matched = "ManualPipelineSpec"
				decoded = &candidate
			} else {
				failures = append(failures, "ManualPipelineSpec: "+err.Error())
			}
		}
	}
	{
		valid := true
		if _, ok := fields["selection"]; !ok {
			valid = false
			failures = append(failures, "ScheduledPipelineSpec: required property selection is missing")
		}
		if _, ok := fields["schedules"]; !ok {
			valid = false
			failures = append(failures, "ScheduledPipelineSpec: required property schedules is missing")
		}
		if _, ok := fields["timezone"]; !ok {
			valid = false
			failures = append(failures, "ScheduledPipelineSpec: required property timezone is missing")
		}
		if _, ok := fields["startingDeadlineSeconds"]; !ok {
			valid = false
			failures = append(failures, "ScheduledPipelineSpec: required property startingDeadlineSeconds is missing")
		}
		if _, ok := fields["concurrencyPolicy"]; !ok {
			valid = false
			failures = append(failures, "ScheduledPipelineSpec: required property concurrencyPolicy is missing")
		}
		if valid {
			var candidate ScheduledPipelineSpec
			if err := decode(&candidate); err == nil {
				if matched != "" {
					return fmt.Errorf("decode PipelineSpec: object matches both %s and ScheduledPipelineSpec", matched)
				}
				matched = "ScheduledPipelineSpec"
				decoded = &candidate
			} else {
				failures = append(failures, "ScheduledPipelineSpec: "+err.Error())
			}
		}
	}
	if matched == "" {
		return fmt.Errorf("decode PipelineSpec: no object variant matched (fields=%v, errors=%s)", fields, strings.Join(failures, "; "))
	}
	switch matched {
	case "ManualPipelineSpec":
		value.Value = decoded.(*ManualPipelineSpec)
	case "ScheduledPipelineSpec":
		value.Value = decoded.(*ScheduledPipelineSpec)
	}
	return nil
}

type ScheduledPipelineSpec struct {
	Selection               PipelineSelection         `json:"selection" yaml:"selection"`
	Schedules               map[string]string         `json:"schedules" yaml:"schedules"`
	Timezone                string                    `json:"timezone" yaml:"timezone"`
	StartingDeadlineSeconds int64                     `json:"startingDeadlineSeconds" yaml:"startingDeadlineSeconds"`
	ConcurrencyPolicy       PipelineConcurrencyPolicy `json:"concurrencyPolicy" yaml:"concurrencyPolicy"`
}
