// Code generated by internal/project/contracts/generate. DO NOT EDIT.
package contracts

type ConnectorActivationMode string

const (
	ConnectorActivationManaged       ConnectorActivationMode = "managed"
	ConnectorActivationAuthored      ConnectorActivationMode = "authored"
	ConnectorActivationTargetBinding ConnectorActivationMode = "target_binding"
)

type ConnectorSupportStatus string

const (
	ConnectorSupportStable       ConnectorSupportStatus = "stable"
	ConnectorSupportExperimental ConnectorSupportStatus = "experimental"
)

type ConnectorProfile struct {
	Key                  string
	SchemaName           string
	ActivationMode       ConnectorActivationMode
	LocationCapabilities []string
	ApprovedExtensions   []string
	SecretType           string
	SupportStatus        ConnectorSupportStatus
	AdapterKey           string
}

var ConnectorRegistry = []ConnectorProfile{
	{Key: "azure_blob", SchemaName: "AzureBlobConnection", ActivationMode: ConnectorActivationMode("target_binding"), LocationCapabilities: []string{"path"}, ApprovedExtensions: []string{"azure"}, SecretType: "azure", SupportStatus: ConnectorSupportStatus("stable"), AdapterKey: "azure_blob"},
	{Key: "ducklake", SchemaName: "DuckLakeConnection", ActivationMode: ConnectorActivationMode("target_binding"), LocationCapabilities: []string{"relation"}, ApprovedExtensions: []string{"ducklake"}, SecretType: "ducklake", SupportStatus: ConnectorSupportStatus("stable"), AdapterKey: "ducklake"},
	{Key: "gcs", SchemaName: "GCSConnection", ActivationMode: ConnectorActivationMode("target_binding"), LocationCapabilities: []string{"path"}, ApprovedExtensions: []string{"httpfs"}, SecretType: "gcs", SupportStatus: ConnectorSupportStatus("stable"), AdapterKey: "gcs"},
	{Key: "http", SchemaName: "HTTPConnection", ActivationMode: ConnectorActivationMode("authored"), LocationCapabilities: []string{"path"}, ApprovedExtensions: []string{"httpfs"}, SecretType: "http", SupportStatus: ConnectorSupportStatus("stable"), AdapterKey: "http"},
	{Key: "managed", SchemaName: "ManagedConnection", ActivationMode: ConnectorActivationMode("managed"), LocationCapabilities: []string{"path"}, ApprovedExtensions: []string{}, SecretType: "none", SupportStatus: ConnectorSupportStatus("stable"), AdapterKey: "managed"},
	{Key: "mysql", SchemaName: "MySQLConnection", ActivationMode: ConnectorActivationMode("target_binding"), LocationCapabilities: []string{"relation"}, ApprovedExtensions: []string{"mysql"}, SecretType: "mysql", SupportStatus: ConnectorSupportStatus("stable"), AdapterKey: "mysql"},
	{Key: "postgres", SchemaName: "PostgresConnection", ActivationMode: ConnectorActivationMode("target_binding"), LocationCapabilities: []string{"relation"}, ApprovedExtensions: []string{"postgres"}, SecretType: "postgres", SupportStatus: ConnectorSupportStatus("stable"), AdapterKey: "postgres"},
	{Key: "quack", SchemaName: "QuackConnection", ActivationMode: ConnectorActivationMode("target_binding"), LocationCapabilities: []string{"relation"}, ApprovedExtensions: []string{"httpfs", "quack"}, SecretType: "quack", SupportStatus: ConnectorSupportStatus("experimental"), AdapterKey: "quack"},
	{Key: "r2", SchemaName: "R2Connection", ActivationMode: ConnectorActivationMode("target_binding"), LocationCapabilities: []string{"path"}, ApprovedExtensions: []string{"httpfs"}, SecretType: "r2", SupportStatus: ConnectorSupportStatus("stable"), AdapterKey: "r2"},
	{Key: "s3", SchemaName: "S3Connection", ActivationMode: ConnectorActivationMode("target_binding"), LocationCapabilities: []string{"path"}, ApprovedExtensions: []string{"httpfs"}, SecretType: "s3", SupportStatus: ConnectorSupportStatus("stable"), AdapterKey: "s3"},
	{Key: "sqlite", SchemaName: "SQLiteConnection", ActivationMode: ConnectorActivationMode("target_binding"), LocationCapabilities: []string{"relation"}, ApprovedExtensions: []string{"sqlite"}, SecretType: "sqlite", SupportStatus: ConnectorSupportStatus("stable"), AdapterKey: "sqlite"},
}

func LookupConnector(key string) (ConnectorProfile, bool) {
	for _, profile := range ConnectorRegistry {
		if profile.Key == key {
			return profile, true
		}
	}
	return ConnectorProfile{}, false
}
