// Code generated by apigen data-contract Go emitter. DO NOT EDIT.
package contracts

type AuthoringArchive struct {
}

type AuthoringPublish struct {
}

type CatalogDetails struct {
	Kind     CatalogType    `json:"kind"`
	Metadata map[string]any `json:"metadata"`
}

type CatalogGetInput struct {
	Ref CatalogRef `json:"ref"`
}

type CatalogGetResult struct {
	Item    CatalogItem    `json:"item"`
	Details CatalogDetails `json:"details"`
}

type CatalogItem struct {
	Ref         CatalogRef `json:"ref"`
	Name        string     `json:"name"`
	DisplayName *string    `json:"displayName,omitempty"`
	Description *string    `json:"description,omitempty"`
	Domain      *string    `json:"domain,omitempty"`
	Owner       *string    `json:"owner,omitempty"`
	Tags        *[]string  `json:"tags,omitempty"`
}

type CatalogListInput struct {
	Parent     *CatalogRef    `json:"parent,omitempty"`
	ChildKinds *[]CatalogType `json:"childKinds,omitempty"`
	Cursor     *string        `json:"cursor,omitempty"`
	Limit      *int32         `json:"limit,omitempty"`
}

type CatalogPage struct {
	Items      []CatalogItem `json:"items"`
	Count      int32         `json:"count"`
	HasMore    bool          `json:"hasMore"`
	NextCursor *string       `json:"nextCursor,omitempty"`
}

type CatalogRef struct {
	ID   string      `json:"id"`
	Kind CatalogType `json:"kind"`
}

type CatalogSearchInput struct {
	Query  string         `json:"query"`
	Kinds  *[]CatalogType `json:"kinds,omitempty"`
	Domain *string        `json:"domain,omitempty"`
	Cursor *string        `json:"cursor,omitempty"`
	Limit  *int32         `json:"limit,omitempty"`
}

type CatalogType string

const (
	CatalogTypeProject       CatalogType = "project"
	CatalogTypeConnection    CatalogType = "connection"
	CatalogTypeSource        CatalogType = "source"
	CatalogTypeModel         CatalogType = "model"
	CatalogTypeSemanticModel CatalogType = "semantic_model"
	CatalogTypePipeline      CatalogType = "pipeline"
	CatalogTypeDashboard     CatalogType = "dashboard"
)

type DashboardAppliedFilters struct {
	Controls          map[string]DashboardFilterControl `json:"controls"`
	Selections        []map[string]any                  `json:"selections"`
	SpatialSelections []map[string]any                  `json:"spatialSelections"`
}

type DashboardAuthoringAddPageInput struct {
	DashboardID      string                          `json:"dashboardId"`
	DraftID          string                          `json:"draftId"`
	ExpectedRevision DashboardAuthoringRevisionToken `json:"expectedRevision"`
	PageID           *string                         `json:"pageId,omitempty"`
	Title            *string                         `json:"title,omitempty"`
}

type DashboardAuthoringAddVisualInput struct {
	DashboardID      string                          `json:"dashboardId"`
	DraftID          string                          `json:"draftId"`
	ExpectedRevision DashboardAuthoringRevisionToken `json:"expectedRevision"`
	PageID           string                          `json:"pageId"`
	VisualID         *string                         `json:"visualId,omitempty"`
	ComponentID      *string                         `json:"componentId,omitempty"`
	Type             string                          `json:"type"`
	Title            *string                         `json:"title,omitempty"`
}

type DashboardAuthoringAssignFieldInput struct {
	DashboardID      string                          `json:"dashboardId"`
	DraftID          string                          `json:"draftId"`
	ExpectedRevision DashboardAuthoringRevisionToken `json:"expectedRevision"`
	PageID           string                          `json:"pageId"`
	VisualID         string                          `json:"visualId"`
	FieldID          string                          `json:"fieldId"`
	Role             string                          `json:"role"`
}

type DashboardAuthoringCommandInput struct {
	DashboardID      string                          `json:"dashboardId"`
	DraftID          string                          `json:"draftId"`
	ExpectedRevision DashboardAuthoringRevisionToken `json:"expectedRevision"`
	ContentHash      *string                         `json:"contentHash,omitempty"`
	Publish          *AuthoringPublish               `json:"publish,omitempty"`
	Archive          *AuthoringArchive               `json:"archive,omitempty"`
}

type DashboardAuthoringCreateInput struct {
	Title           string  `json:"title"`
	SemanticModelID string  `json:"semanticModelId"`
	DashboardID     *string `json:"dashboardId,omitempty"`
	Slug            *string `json:"slug,omitempty"`
}

type DashboardAuthoringDraftGetInput struct {
	DashboardID string `json:"dashboardId"`
}

type DashboardAuthoringDraftGetResult struct {
	Lifecycle map[string]any `json:"lifecycle"`
	Revision  map[string]any `json:"revision"`
}

type DashboardAuthoringExportInput struct {
	SourceKind  string `json:"sourceKind"`
	DashboardID string `json:"dashboardId"`
}

type DashboardAuthoringExportResult struct {
	Yaml string `json:"yaml"`
}

type DashboardAuthoringForkInput struct {
	SourceKind        string  `json:"sourceKind"`
	SourceDashboardID string  `json:"sourceDashboardId"`
	Title             *string `json:"title,omitempty"`
	Slug              *string `json:"slug,omitempty"`
}

type DashboardAuthoringGetInput struct {
	DashboardID string `json:"dashboardId"`
}

type DashboardAuthoringGetResult struct {
	Dashboard map[string]any `json:"dashboard"`
}

type DashboardAuthoringListInput struct {
}

type DashboardAuthoringListResult struct {
	Items        []map[string]any `json:"items"`
	Count        int32            `json:"count"`
	ProjectCount int32            `json:"projectCount"`
}

type DashboardAuthoringPreviewInput struct {
	DashboardID      string                          `json:"dashboardId"`
	DraftID          string                          `json:"draftId"`
	ExpectedRevision DashboardAuthoringRevisionToken `json:"expectedRevision"`
	Page             string                          `json:"page"`
	Filters          *map[string]any                 `json:"filters,omitempty"`
}

type DashboardAuthoringPreviewResult struct {
	Revision         map[string]any `json:"revision"`
	Definition       map[string]any `json:"definition"`
	PagePatch        map[string]any `json:"pagePatch"`
	SemanticEvidence map[string]any `json:"semanticEvidence"`
}

type DashboardAuthoringResult struct {
	Revision  map[string]any `json:"revision"`
	Lifecycle map[string]any `json:"lifecycle"`
}

type DashboardAuthoringRevisionToken struct {
	RevisionID  string `json:"revisionId"`
	Number      int64  `json:"number"`
	ContentHash string `json:"contentHash"`
}

type DashboardAuthoringSetVisibilityInput struct {
	DashboardID      string                          `json:"dashboardId"`
	DraftID          string                          `json:"draftId"`
	ExpectedRevision DashboardAuthoringRevisionToken `json:"expectedRevision"`
	Visibility       string                          `json:"visibility"`
}

type DashboardFilterControl struct {
	Type     string    `json:"type"`
	Operator *string   `json:"operator,omitempty"`
	Preset   *string   `json:"preset,omitempty"`
	From     *string   `json:"from,omitempty"`
	To       *string   `json:"to,omitempty"`
	Value    *string   `json:"value,omitempty"`
	Values   *[]string `json:"values,omitempty"`
}

type DashboardVisualColumn struct {
	ID        string          `json:"id"`
	SourceRef *string         `json:"sourceRef,omitempty"`
	Label     string          `json:"label"`
	Role      string          `json:"role"`
	DataType  string          `json:"dataType"`
	Nullable  bool            `json:"nullable"`
	Format    *map[string]any `json:"format,omitempty"`
	Grain     *string         `json:"grain,omitempty"`
}

type DashboardVisualCompleteness struct {
	ReturnedRows     int32  `json:"returnedRows"`
	AvailableRows    *int64 `json:"availableRows,omitempty"`
	Cardinality      string `json:"cardinality"`
	CardinalityCount *int64 `json:"cardinalityCount,omitempty"`
	State            string `json:"state"`
}

type DashboardVisualDiagnostic struct {
	Code     string  `json:"code"`
	Severity string  `json:"severity"`
	Message  string  `json:"message"`
	FieldID  *string `json:"fieldId,omitempty"`
}

type DashboardVisualQueryResult struct {
	QueryID         string                      `json:"queryId"`
	ServingSnapshot string                      `json:"servingSnapshot"`
	Freshness       *QueryFreshness             `json:"freshness,omitempty"`
	VisualID        string                      `json:"visualId"`
	Title           string                      `json:"title"`
	Type            string                      `json:"type"`
	Mark            *string                     `json:"mark,omitempty"`
	DatasetID       string                      `json:"datasetId"`
	Columns         []DashboardVisualColumn     `json:"columns"`
	Rows            [][]any                     `json:"rows"`
	AppliedFilters  DashboardAppliedFilters     `json:"appliedFilters"`
	Status          DashboardVisualStatus       `json:"status"`
	Diagnostics     []DashboardVisualDiagnostic `json:"diagnostics"`
	Completeness    DashboardVisualCompleteness `json:"completeness"`
	HasMore         bool                        `json:"hasMore"`
	NextCursor      *string                     `json:"nextCursor,omitempty"`
}

type DashboardVisualStatus struct {
	Kind    string  `json:"kind"`
	Message *string `json:"message,omitempty"`
}

type DocsReadInput struct {
	ID     string `json:"id"`
	Offset *int32 `json:"offset,omitempty"`
	Limit  *int32 `json:"limit,omitempty"`
}

type DocsReadResult struct {
	ID         string `json:"id"`
	Path       string `json:"path"`
	Title      string `json:"title"`
	URL        string `json:"url"`
	Content    string `json:"content"`
	LineStart  int32  `json:"lineStart"`
	LineEnd    int32  `json:"lineEnd"`
	TotalLines int32  `json:"totalLines"`
	NextOffset *int32 `json:"nextOffset,omitempty"`
	Truncated  bool   `json:"truncated"`
}

type DocsReference struct {
	ID      string `json:"id"`
	Path    string `json:"path"`
	Title   string `json:"title"`
	Summary string `json:"summary"`
	URL     string `json:"url"`
	Excerpt string `json:"excerpt"`
}

type DocsSearchInput struct {
	Query  string  `json:"query"`
	Path   *string `json:"path,omitempty"`
	Cursor *string `json:"cursor,omitempty"`
	Limit  *int32  `json:"limit,omitempty"`
}

type DocsSearchResult struct {
	Query      string          `json:"query"`
	Path       *string         `json:"path,omitempty"`
	Matches    []DocsReference `json:"matches"`
	Count      int32           `json:"count"`
	HasMore    bool            `json:"hasMore"`
	NextCursor *string         `json:"nextCursor,omitempty"`
}

type QueryFreshness struct {
	LastSuccessfulRefreshAt string `json:"lastSuccessfulRefreshAt"`
	SnapshotID              string `json:"snapshotId"`
	ServingStateID          string `json:"servingStateId"`
	Source                  string `json:"source"`
	Status                  string `json:"status"`
}

type QueryVisualCalculation struct {
	ID          string                         `json:"id"`
	Label       *string                        `json:"label,omitempty"`
	Template    string                         `json:"template"`
	Source      string                         `json:"source"`
	Axis        *string                        `json:"axis,omitempty"`
	OrderBy     *[]QueryVisualCalculationOrder `json:"orderBy,omitempty"`
	PartitionBy *[]string                      `json:"partitionBy,omitempty"`
	Reset       *string                        `json:"reset,omitempty"`
	Window      *int32                         `json:"window,omitempty"`
	Offset      *int32                         `json:"offset,omitempty"`
	Parent      *string                        `json:"parent,omitempty"`
	Lookup      *QueryVisualCalculationLookup  `json:"lookup,omitempty"`
	Hidden      *bool                          `json:"hidden,omitempty"`
	Format      *string                        `json:"format,omitempty"`
}

type QueryVisualCalculationLookup struct {
	Field string `json:"field"`
	Value string `json:"value"`
}

type QueryVisualCalculationOrder struct {
	Field     string  `json:"field"`
	Direction *string `json:"direction,omitempty"`
}

type QueryVisualCompleteness struct {
	ReturnedRows int32  `json:"returnedRows"`
	Limit        int32  `json:"limit"`
	Status       string `json:"status"`
}

type QueryVisualFieldRef struct {
	Field string  `json:"field"`
	Alias *string `json:"alias,omitempty"`
}

type QueryVisualFieldUsage struct {
	FieldID  string  `json:"fieldId"`
	Role     string  `json:"role"`
	Alias    *string `json:"alias,omitempty"`
	Label    string  `json:"label"`
	DataType *string `json:"dataType,omitempty"`
	Unit     *string `json:"unit,omitempty"`
	Format   *string `json:"format,omitempty"`
}

type QueryVisualFilterGroupInput struct {
	Filters []map[string]any `json:"filters"`
}

type QueryVisualFilterInput struct {
	Field    *string                        `json:"field,omitempty"`
	Fact     *string                        `json:"fact,omitempty"`
	Operator *string                        `json:"operator,omitempty"`
	Values   *[]string                      `json:"values,omitempty"`
	Groups   *[]QueryVisualFilterGroupInput `json:"groups,omitempty"`
}

type QueryVisualFilterUsage struct {
	Operator       string    `json:"operator"`
	FieldID        string    `json:"fieldId"`
	ResolvedFactID *string   `json:"resolvedFactId,omitempty"`
	Values         *[]string `json:"values,omitempty"`
	Path           *[]int32  `json:"path,omitempty"`
}

type QueryVisualInput struct {
	SemanticModelID string                    `json:"semanticModelId"`
	Dataset         string                    `json:"dataset"`
	Title           *string                   `json:"title,omitempty"`
	Type            QueryVisualType           `json:"type"`
	Dimensions      *[]QueryVisualFieldRef    `json:"dimensions,omitempty"`
	Series          *QueryVisualFieldRef      `json:"series,omitempty"`
	Measures        *[]QueryVisualFieldRef    `json:"measures,omitempty"`
	Fields          *[]QueryVisualFieldRef    `json:"fields,omitempty"`
	Rows            *[]QueryVisualFieldRef    `json:"rows,omitempty"`
	Columns         *[]QueryVisualTableColumn `json:"columns,omitempty"`
	Filters         *[]QueryVisualFilterInput `json:"filters,omitempty"`
	Sort            *[]QueryVisualSort        `json:"sort,omitempty"`
	Limit           *int32                    `json:"limit,omitempty"`
	Presentation    *QueryVisualPresentation  `json:"presentation,omitempty"`
	Calculations    *[]QueryVisualCalculation `json:"calculations,omitempty"`
}

type QueryVisualLabelPolicy struct {
	Density         *string   `json:"density,omitempty"`
	Priority        *[]string `json:"priority,omitempty"`
	MaxCharacters   *int32    `json:"maxCharacters,omitempty"`
	MinimumSpacing  *int32    `json:"minimumSpacing,omitempty"`
	TooltipFallback *bool     `json:"tooltipFallback,omitempty"`
}

type QueryVisualPresentation struct {
	Legend        *string                 `json:"legend,omitempty"`
	ShowLabels    *bool                   `json:"showLabels,omitempty"`
	Labels        *QueryVisualLabelPolicy `json:"labels,omitempty"`
	Stacked       *bool                   `json:"stacked,omitempty"`
	Smooth        *bool                   `json:"smooth,omitempty"`
	ShowSymbols   *bool                   `json:"showSymbols,omitempty"`
	DataZoom      *bool                   `json:"dataZoom,omitempty"`
	Area          *bool                   `json:"area,omitempty"`
	Step          *bool                   `json:"step,omitempty"`
	Orientation   *string                 `json:"orientation,omitempty"`
	LabelPosition *string                 `json:"labelPosition,omitempty"`
	SymbolSize    *float64                `json:"symbolSize,omitempty"`
	HistogramBins *int32                  `json:"histogramBins,omitempty"`
	SeriesTypes   *map[string]string      `json:"seriesTypes,omitempty"`
	DualAxis      *bool                   `json:"dualAxis,omitempty"`
	Rose          *bool                   `json:"rose,omitempty"`
	CenterLabel   *string                 `json:"centerLabel,omitempty"`
	InnerRadius   *float64                `json:"innerRadius,omitempty"`
	OuterRadius   *float64                `json:"outerRadius,omitempty"`
	Align         *string                 `json:"align,omitempty"`
	Sort          *string                 `json:"sort,omitempty"`
	InitialDepth  *int32                  `json:"initialDepth,omitempty"`
	Basemap       *string                 `json:"basemap,omitempty"`
	Roam          *bool                   `json:"roam,omitempty"`
	Layout        *string                 `json:"layout,omitempty"`
	Breadcrumb    *bool                   `json:"breadcrumb,omitempty"`
	NodeGap       *float64                `json:"nodeGap,omitempty"`
	Curveness     *float64                `json:"curveness,omitempty"`
	Focus         *string                 `json:"focus,omitempty"`
	Minimum       *float64                `json:"minimum,omitempty"`
	Maximum       *float64                `json:"maximum,omitempty"`
	ProgressWidth *float64                `json:"progressWidth,omitempty"`
	Thresholds    *[]QueryVisualThreshold `json:"thresholds,omitempty"`
	Note          *string                 `json:"note,omitempty"`
	Tone          *string                 `json:"tone,omitempty"`
}

type QueryVisualResult struct {
	Ok               bool                        `json:"ok"`
	QueryID          string                      `json:"queryId"`
	ServingSnapshot  string                      `json:"servingSnapshot"`
	Freshness        *QueryFreshness             `json:"freshness,omitempty"`
	Type             string                      `json:"type"`
	ID               string                      `json:"id"`
	Title            string                      `json:"title"`
	SemanticModelRef CatalogRef                  `json:"semanticModelRef"`
	DatasetID        string                      `json:"datasetId"`
	Fields           []QueryVisualFieldUsage     `json:"fields"`
	Filters          []QueryVisualFilterUsage    `json:"filters"`
	Completeness     QueryVisualCompleteness     `json:"completeness"`
	Status           DashboardVisualStatus       `json:"status"`
	Diagnostics      []DashboardVisualDiagnostic `json:"diagnostics"`
	Summary          string                      `json:"summary"`
	Signal           string                      `json:"signal"`
}

type QueryVisualSort struct {
	Field     string  `json:"field"`
	Direction *string `json:"direction,omitempty"`
}

type QueryVisualTableColumn struct {
	Key         string                            `json:"key"`
	Label       string                            `json:"label"`
	Align       *string                           `json:"align,omitempty"`
	Role        *string                           `json:"role,omitempty"`
	Group       *string                           `json:"group,omitempty"`
	Measure     *string                           `json:"measure,omitempty"`
	ColumnValue *string                           `json:"columnValue,omitempty"`
	Width       *int32                            `json:"width,omitempty"`
	Format      *string                           `json:"format,omitempty"`
	Formatting  *[]QueryVisualTableFormattingRule `json:"formatting,omitempty"`
}

type QueryVisualTableFormattingRule struct {
	Kind       string             `json:"kind"`
	Values     *map[string]string `json:"values,omitempty"`
	Min        *float64           `json:"min,omitempty"`
	Max        *float64           `json:"max,omitempty"`
	Color      *string            `json:"color,omitempty"`
	Background *string            `json:"background,omitempty"`
	LowColor   *string            `json:"lowColor,omitempty"`
	HighColor  *string            `json:"highColor,omitempty"`
}

type QueryVisualThreshold struct {
	Value float64 `json:"value"`
	Tone  string  `json:"tone"`
}

type QueryVisualType string

const (
	QueryVisualTypeLine        QueryVisualType = "line"
	QueryVisualTypeArea        QueryVisualType = "area"
	QueryVisualTypeBar         QueryVisualType = "bar"
	QueryVisualTypeColumn      QueryVisualType = "column"
	QueryVisualTypePie         QueryVisualType = "pie"
	QueryVisualTypeDonut       QueryVisualType = "donut"
	QueryVisualTypeScatter     QueryVisualType = "scatter"
	QueryVisualTypeFunnel      QueryVisualType = "funnel"
	QueryVisualTypeTreemap     QueryVisualType = "treemap"
	QueryVisualTypeGauge       QueryVisualType = "gauge"
	QueryVisualTypeHeatmap     QueryVisualType = "heatmap"
	QueryVisualTypeSankey      QueryVisualType = "sankey"
	QueryVisualTypeGraph       QueryVisualType = "graph"
	QueryVisualTypeMap         QueryVisualType = "map"
	QueryVisualTypeCandlestick QueryVisualType = "candlestick"
	QueryVisualTypeBoxplot     QueryVisualType = "boxplot"
	QueryVisualTypeCombo       QueryVisualType = "combo"
	QueryVisualTypeWaterfall   QueryVisualType = "waterfall"
	QueryVisualTypeHistogram   QueryVisualType = "histogram"
	QueryVisualTypeRadar       QueryVisualType = "radar"
	QueryVisualTypeTree        QueryVisualType = "tree"
	QueryVisualTypeSunburst    QueryVisualType = "sunburst"
	QueryVisualTypeKpi         QueryVisualType = "kpi"
	QueryVisualTypeTable       QueryVisualType = "table"
	QueryVisualTypeMatrix      QueryVisualType = "matrix"
	QueryVisualTypePivot       QueryVisualType = "pivot"
)
