apiVersion: leapview.dev/v1
kind: Project
metadata:
  id: project:leapview-evaluation
  name: leapview-evaluation
spec:
  connections:
    include:
      - connections/*.yaml
  sources:
    include:
      - sources/*.yaml
  models:
    include:
      - models/*.yaml
  semanticModels:
    include:
      - semantic-models/*.yaml
  pipelines:
    include:
      - pipelines/*.yaml
  dashboards:
    include:
      - dashboards/*.yaml
  access:
    include:
      - access/*.yaml
