// Command agenttooldocgen renders the canonical runtime agent tool catalog
// into public machine-readable and Markdown reference documentation.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	agenttools "github.com/flidai/leapview/internal/agent/tools"
	apiaggregate "github.com/flidai/leapview/internal/app/api/aggregate"
)

const generatedMarker = "<!-- Code generated by internal/app/tools/agenttooldocgen; DO NOT EDIT. -->"
const maxInlineSchemaBytes = 32 * 1024

type machineManifest struct {
	SchemaVersion int                        `json:"schemaVersion"`
	Tools         []agenttools.ToolReference `json:"tools"`
}

type generatedCatalog struct {
	Title     string              `json:"title"`
	Documents []generatedDocument `json:"documents"`
}

type generatedDocument struct {
	Slug    string `json:"slug"`
	Title   string `json:"title"`
	Summary string `json:"summary"`
}

func main() {
	out := flag.String("out", "docs/reference/agent-tools", "generated agent tool reference directory")
	check := flag.Bool("check", false, "verify generated output is current")
	flag.Parse()
	var err error
	if *check {
		err = checkGenerated(*out)
	} else {
		err = generate(*out)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func checkGenerated(out string) error {
	temporary, err := os.MkdirTemp("", "leapview-agent-tool-docs-*")
	if err != nil {
		return fmt.Errorf("create temporary output: %w", err)
	}
	defer os.RemoveAll(temporary)
	if err := generate(temporary); err != nil {
		return err
	}
	current, err := readGeneratedTree(out)
	if err != nil {
		return err
	}
	expected, err := readGeneratedTree(temporary)
	if err != nil {
		return err
	}
	if len(current) != len(expected) {
		return fmt.Errorf("%s is out of date; run task agent-tool-docs:generate", out)
	}
	for name, contents := range expected {
		if !bytes.Equal(current[name], contents) {
			return fmt.Errorf("%s is out of date; run task agent-tool-docs:generate", filepath.Join(out, name))
		}
	}
	return nil
}

func readGeneratedTree(root string) (map[string][]byte, error) {
	files := map[string][]byte{}
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		name, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		files[filepath.ToSlash(name)], err = os.ReadFile(path)
		return err
	})
	if err != nil {
		return nil, fmt.Errorf("read generated output %s: %w", root, err)
	}
	return files, nil
}

func generate(out string) error {
	tools, err := agenttools.ReferenceCatalog(agentAPIGenOperations())
	if err != nil {
		return fmt.Errorf("load canonical agent tool catalog: %w", err)
	}
	if err := os.RemoveAll(out); err != nil {
		return fmt.Errorf("clear output: %w", err)
	}
	if err := os.MkdirAll(out, 0o755); err != nil {
		return fmt.Errorf("create output: %w", err)
	}
	manifest, err := json.MarshalIndent(machineManifest{SchemaVersion: 1, Tools: tools}, "", "  ")
	if err != nil {
		return fmt.Errorf("encode manifest: %w", err)
	}
	if err := os.WriteFile(filepath.Join(out, "manifest.json"), append(manifest, '\n'), 0o644); err != nil {
		return err
	}
	documents := make([]generatedDocument, 0, len(tools))
	for _, tool := range tools {
		documents = append(documents, generatedDocument{
			Slug: tool.Name, Title: tool.Name, Summary: firstSentence(tool.Description),
		})
		if err := os.WriteFile(filepath.Join(out, tool.Name+".md"), []byte(renderTool(tool)), 0o644); err != nil {
			return err
		}
	}
	catalog, err := json.MarshalIndent(generatedCatalog{Title: "Agent tool reference", Documents: documents}, "", "  ")
	if err != nil {
		return fmt.Errorf("encode catalog: %w", err)
	}
	if err := os.WriteFile(filepath.Join(out, "catalog.json"), append(catalog, '\n'), 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(out, "index.md"), []byte(renderIndex(tools)), 0o644)
}

func agentAPIGenOperations() []agenttools.APIGenOperation {
	generated := apiaggregate.GetAPIGenOperationContracts()
	contracts := make(map[string]agenttools.OperationContract, len(generated))
	for operationID, contract := range generated {
		contracts[operationID] = agenttools.OperationContract{
			OperationID: contract.OperationID, Method: contract.Method, Path: contract.Path,
			Protected: contract.Protected, AuthzMode: contract.AuthzMode, Manual: contract.Manual,
			Extensions: contract.Extensions,
		}
	}
	return agenttools.BuildAPIGenOperations(contracts, apiaggregate.GetAPIGenToolContracts())
}

func renderIndex(tools []agenttools.ToolReference) string {
	var out strings.Builder
	out.WriteString(generatedMarker + "\n\n# Agent tool reference\n\n")
	out.WriteString("The exact tool catalog exposed by built-in chat, deployment MCP, and `leapview agent tools`. Names, metadata, defaults, and schemas are generated from the canonical runtime providers.\n\n")
	out.WriteString("Machine-readable: [complete tool manifest](/docs/agent-tools/manifest.json). Focused JSON and Markdown slices are available at `/docs/agent-tools/tools/{name}.json` and `.md`.\n\n")
	out.WriteString("## Tools\n\n| Tool | Authorization | Effect | Description |\n| --- | --- | --- | --- |\n")
	for _, tool := range tools {
		out.WriteString("| [`" + tool.Name + "`](/docs/agent-tools/" + tool.Name + ") | `" + toolAuthorization(tool) + "` | `" + tool.Effect + "` | " + escapeTable(firstSentence(tool.Description)) + " |\n")
	}
	return out.String()
}

func renderTool(tool agenttools.ToolReference) string {
	var out strings.Builder
	out.WriteString(generatedMarker + "\n\n# " + tool.Name + "\n\n")
	out.WriteString(strings.TrimSpace(tool.Description) + "\n\n")
	out.WriteString("Machine-readable: [focused JSON](/docs/agent-tools/tools/" + tool.Name + ".json) · [complete manifest](/docs/agent-tools/manifest.json)\n\n")
	out.WriteString("## Contract\n\n| Property | Value |\n| --- | --- |\n")
	out.WriteString("| Authorization | `" + toolAuthorization(tool) + "` |\n")
	out.WriteString("| Effect | `" + tool.Effect + "` |\n")
	out.WriteString("| Operation | `" + tool.OperationID + "` |\n")
	out.WriteString("| Tags | " + codeList(tool.Tags) + " |\n")
	out.WriteString("| Defaults | `" + escapeTable(compactJSON(tool.Defaults)) + "` |\n")
	out.WriteString("| MCP annotations | " + annotationSummary(tool.Annotations) + " |\n")
	writeSchema(&out, "Input schema", tool.InputSchema, tool.Name)
	writeSchema(&out, "Output schema", tool.OutputSchema, tool.Name)
	return out.String()
}

func toolAuthorization(tool agenttools.ToolReference) string {
	if tool.AuthzMode == "authenticated" {
		return "authenticated"
	}
	return tool.Privilege
}

func annotationSummary(annotations agenttools.ToolAnnotations) string {
	access := "read/write"
	if annotations.ReadOnlyHint {
		access = "read-only"
	}
	idempotency := "not idempotent"
	if annotations.IdempotentHint {
		idempotency = "idempotent"
	}
	destructiveness := "non-destructive"
	if annotations.DestructiveHint {
		destructiveness = "destructive"
	}
	world := "closed-world"
	if annotations.OpenWorldHint {
		world = "open-world"
	}
	return strings.Join([]string{access, idempotency, destructiveness, world}, ", ")
}

func writeSchema(out *strings.Builder, heading string, schema json.RawMessage, toolName string) {
	out.WriteString("\n## " + heading + "\n\n")
	if len(schema) > maxInlineSchemaBytes {
		out.WriteString("This closed schema is too large to inline usefully. Read the exact generated schema in the [focused JSON contract](/docs/agent-tools/tools/" + toolName + ".json).\n")
		return
	}
	out.WriteString("```json\n" + prettyJSON(schema) + "\n```\n")
}

func firstSentence(value string) string {
	value = strings.TrimSpace(value)
	if index := strings.Index(value, ". "); index >= 0 {
		return value[:index+1]
	}
	return value
}

func codeList(values []string) string {
	if len(values) == 0 {
		return "none"
	}
	encoded := make([]string, 0, len(values))
	for _, value := range values {
		encoded = append(encoded, "`"+value+"`")
	}
	return strings.Join(encoded, ", ")
}

func compactJSON(value any) string {
	encoded, _ := json.Marshal(value)
	return string(encoded)
}

func prettyJSON(value json.RawMessage) string {
	var output bytes.Buffer
	if err := json.Indent(&output, value, "", "  "); err != nil {
		return string(value)
	}
	return output.String()
}

func escapeTable(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}
