package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateWritesCanonicalManifestAndReferencePages(t *testing.T) {
	out := filepath.Join(t.TempDir(), "agent-tools")
	if err := generate(out); err != nil {
		t.Fatalf("generate: %v", err)
	}
	manifestBytes, err := os.ReadFile(filepath.Join(out, "manifest.json"))
	if err != nil {
		t.Fatal(err)
	}
	var manifest machineManifest
	if err := json.Unmarshal(manifestBytes, &manifest); err != nil {
		t.Fatalf("decode manifest: %v", err)
	}
	if manifest.SchemaVersion != 1 || len(manifest.Tools) != 20 {
		t.Fatalf("manifest = %#v", manifest)
	}
	for _, tool := range manifest.Tools {
		if len(tool.InputSchema) == 0 || len(tool.OutputSchema) == 0 {
			t.Fatalf("tool %q omitted schemas", tool.Name)
		}
		switch tool.Effect {
		case "read":
			if !tool.Annotations.ReadOnlyHint || !tool.Annotations.IdempotentHint || tool.Annotations.DestructiveHint {
				t.Fatalf("read tool %q annotations = %#v", tool.Name, tool.Annotations)
			}
		case "write":
			if tool.Annotations.ReadOnlyHint || tool.Annotations.IdempotentHint || tool.Annotations.DestructiveHint {
				t.Fatalf("write tool %q annotations = %#v", tool.Name, tool.Annotations)
			}
		case "destructive":
			if tool.Annotations.ReadOnlyHint || tool.Annotations.IdempotentHint || !tool.Annotations.DestructiveHint {
				t.Fatalf("destructive tool %q annotations = %#v", tool.Name, tool.Annotations)
			}
		default:
			t.Fatalf("tool %q has unsupported effect %q", tool.Name, tool.Effect)
		}
		page, err := os.ReadFile(filepath.Join(out, tool.Name+".md"))
		if err != nil {
			t.Fatal(err)
		}
		for _, want := range []string{
			"Code generated by internal/app/tools/agenttooldocgen",
			"# " + tool.Name,
			"## Input schema",
			"## Output schema",
		} {
			if !strings.Contains(string(page), want) {
				t.Fatalf("%s.md missing %q", tool.Name, want)
			}
		}
	}
	commandPage, err := os.ReadFile(filepath.Join(out, "execute_dashboard_command.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(commandPage), "Publish or archive") {
		t.Fatal("execute_dashboard_command page omitted publish/archive scope")
	}
	index, err := os.ReadFile(filepath.Join(out, "index.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(index), "/docs/agent-tools/manifest.json") {
		t.Fatalf("index missing machine manifest link:\n%s", index)
	}
}

func TestCheckGeneratedDetectsDrift(t *testing.T) {
	out := filepath.Join(t.TempDir(), "agent-tools")
	if err := generate(out); err != nil {
		t.Fatalf("generate: %v", err)
	}
	if err := checkGenerated(out); err != nil {
		t.Fatalf("check fresh output: %v", err)
	}
	if err := os.WriteFile(filepath.Join(out, "catalog_search.md"), []byte("stale\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := checkGenerated(out); err == nil {
		t.Fatal("check accepted stale generated output")
	}
}
