// Package postgres implements LeapView's canonical transactional PostgreSQL
// event log. Events are appended through a caller-owned transaction; source
// mutations and their event record therefore share one commit/rollback
// boundary. Delivery, transport, and consumer lifecycle state deliberately do
// not belong to this capability.
package postgres

import (
	"bytes"
	"context"
	"crypto/rand"
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/flidai/leapview/pkg/strictjson"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// Tx is the deliberately small native pgx transaction surface used by this
// capability. pgx.Tx and pgxpool.Tx both satisfy it; the repository never
// opens, commits, or rolls back a transaction.
type Tx interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
	QueryRow(context.Context, string, ...any) pgx.Row
}

// Repository is stateless. Pointer identity is used by application
// composition to prove that adapters retain the canonical authority supplied
// by the authority graph.
type Repository struct{}

//go:embed schema.sql
var schemaSQL string

// SchemaSQL returns the forward event capability schema. It contains no
// transaction control; callers apply it using their migration transaction.
func SchemaSQL() string { return schemaSQL }

// EventInput describes one domain event. EventID is optional; when omitted a
// UUIDv7 is generated by the repository.
type EventInput struct {
	EventID       string
	ScopeID       string
	AggregateType string
	AggregateID   string
	EventType     string
	SchemaVersion int64
	CorrelationID string
	Payload       json.RawMessage
}

// Event is the immutable event-log record returned after append.
type Event struct {
	EventID          string
	ScopeID          string
	AggregateType    string
	AggregateID      string
	AggregateVersion int64
	EventType        string
	SchemaVersion    int64
	OccurredAt       time.Time
	CorrelationID    string
	Payload          json.RawMessage
}

// EventConflictError reports a retry using an existing event identity with a
// different immutable field.
type EventConflictError struct {
	EventID string
	Field   string
}

func (e *EventConflictError) Error() string {
	return fmt.Sprintf("event %s conflicts on %s", e.EventID, e.Field)
}

// New returns a stateless event repository.
func New() *Repository { return &Repository{} }

// AppendEvent validates and appends one event in tx. Explicit identities are
// idempotent: an exact retry returns the original immutable row, while a
// changed field returns EventConflictError. Aggregate versions are allocated
// by a row lock and are contiguous under concurrent writers.
func (r *Repository) AppendEvent(ctx context.Context, tx Tx, in EventInput) (Event, error) {
	if err := validateTxContext(ctx, tx); err != nil {
		return Event{}, err
	}
	payload, err := canonicalObject(in.Payload, 65536)
	if err != nil {
		return Event{}, fmt.Errorf("event payload: %w", err)
	}
	scope, err := boundedID("scope", in.ScopeID, 255)
	if err != nil {
		return Event{}, err
	}
	aggregateType, err := boundedID("aggregate type", in.AggregateType, 255)
	if err != nil {
		return Event{}, err
	}
	aggregateID, err := boundedID("aggregate id", in.AggregateID, 255)
	if err != nil {
		return Event{}, err
	}
	eventType, err := boundedID("event type", in.EventType, 255)
	if err != nil {
		return Event{}, err
	}
	if in.SchemaVersion <= 0 {
		return Event{}, errors.New("event schema version must be positive")
	}
	eventID := in.EventID
	if eventID != strings.TrimSpace(eventID) {
		return Event{}, errors.New("event id must not contain surrounding whitespace")
	}
	if eventID == "" {
		eventID, err = uuidv7()
		if err != nil {
			return Event{}, fmt.Errorf("generate event id: %w", err)
		}
	}
	if err := validateUUIDv7("event id", eventID); err != nil {
		return Event{}, err
	}
	correlationID := in.CorrelationID
	if correlationID != strings.TrimSpace(correlationID) {
		return Event{}, errors.New("correlation id must not contain surrounding whitespace")
	}
	if correlationID != "" {
		if err := validateUUID("correlation id", correlationID); err != nil {
			return Event{}, err
		}
	}

	// Serialize retries for one explicit identity before the lookup. This is
	// also what prevents a racing retry from consuming an aggregate version.
	if _, err := tx.Exec(ctx, `SELECT pg_advisory_xact_lock(hashtextextended($1, 0))`, eventID); err != nil {
		return Event{}, fmt.Errorf("lock event identity: %w", err)
	}
	existing, err := getEvent(ctx, tx, eventID)
	if err == nil {
		if existing.ScopeID != scope {
			return Event{}, &EventConflictError{EventID: eventID, Field: "scope_id"}
		}
		if existing.AggregateType != aggregateType {
			return Event{}, &EventConflictError{EventID: eventID, Field: "aggregate_type"}
		}
		if existing.AggregateID != aggregateID {
			return Event{}, &EventConflictError{EventID: eventID, Field: "aggregate_id"}
		}
		if existing.EventType != eventType {
			return Event{}, &EventConflictError{EventID: eventID, Field: "event_type"}
		}
		if existing.SchemaVersion != in.SchemaVersion {
			return Event{}, &EventConflictError{EventID: eventID, Field: "schema_version"}
		}
		if existing.CorrelationID != correlationID {
			return Event{}, &EventConflictError{EventID: eventID, Field: "correlation_id"}
		}
		var payloadMatches bool
		if err := tx.QueryRow(ctx, `SELECT payload = $2::jsonb FROM event.event_log WHERE event_id = $1::uuid`, eventID, payload).Scan(&payloadMatches); err != nil {
			return Event{}, fmt.Errorf("compare existing event payload: %w", err)
		}
		if !payloadMatches {
			return Event{}, &EventConflictError{EventID: eventID, Field: "payload"}
		}
		return existing, nil
	}
	if !errors.Is(err, pgx.ErrNoRows) {
		return Event{}, fmt.Errorf("check event identity: %w", err)
	}

	// The explicit aggregate row is locked by UPDATE, so versions are never
	// derived from MAX() and concurrent writers cannot create gaps or clashes.
	if _, err := tx.Exec(ctx, `
INSERT INTO event.event_aggregate (scope_id, aggregate_type, aggregate_id, next_version)
VALUES ($1, $2, $3, 1)
ON CONFLICT (scope_id, aggregate_type, aggregate_id) DO NOTHING`, scope, aggregateType, aggregateID); err != nil {
		return Event{}, fmt.Errorf("ensure event aggregate: %w", err)
	}
	var version int64
	if err := tx.QueryRow(ctx, `
UPDATE event.event_aggregate
SET next_version = next_version + 1, updated_at = clock_timestamp()
WHERE scope_id = $1 AND aggregate_type = $2 AND aggregate_id = $3
RETURNING next_version - 1`, scope, aggregateType, aggregateID).Scan(&version); err != nil {
		return Event{}, fmt.Errorf("allocate aggregate version: %w", err)
	}
	var occurredAt time.Time
	var storedPayload string
	if err := tx.QueryRow(ctx, `
INSERT INTO event.event_log
    (event_id, scope_id, aggregate_type, aggregate_id, aggregate_version,
     event_type, schema_version, occurred_at, correlation_id, payload)
VALUES ($1::uuid, $2, $3, $4, $5, $6, $7, clock_timestamp(), NULLIF($8, '')::uuid, $9::jsonb)
RETURNING occurred_at, payload::text`, eventID, scope, aggregateType, aggregateID,
		version, eventType, in.SchemaVersion, correlationID, payload).Scan(&occurredAt, &storedPayload); err != nil {
		return Event{}, fmt.Errorf("insert durable event: %w", err)
	}
	if occurredAt.IsZero() || storedPayload == "" {
		return Event{}, errors.New("insert durable event returned invalid projection")
	}
	return Event{EventID: eventID, ScopeID: scope, AggregateType: aggregateType,
		AggregateID: aggregateID, AggregateVersion: version, EventType: eventType,
		SchemaVersion: in.SchemaVersion, OccurredAt: occurredAt.UTC(),
		CorrelationID: correlationID, Payload: json.RawMessage(storedPayload)}, nil
}

// GetEvent reads one durable event by identity.
func (r *Repository) GetEvent(ctx context.Context, tx Tx, eventID string) (Event, error) {
	if err := validateTxContext(ctx, tx); err != nil {
		return Event{}, err
	}
	if err := validateUUIDv7("event id", eventID); err != nil {
		return Event{}, err
	}
	event, err := getEvent(ctx, tx, eventID)
	if err != nil {
		return Event{}, fmt.Errorf("get durable event: %w", err)
	}
	return event, nil
}

func getEvent(ctx context.Context, tx Tx, eventID string) (Event, error) {
	var event Event
	var occurredAt time.Time
	var payload string
	err := tx.QueryRow(ctx, `
SELECT event_id::text, scope_id, aggregate_type, aggregate_id, aggregate_version,
       event_type, schema_version, occurred_at,
       COALESCE(correlation_id::text, ''), payload::text
FROM event.event_log
WHERE event_id = $1::uuid`, eventID).Scan(
		&event.EventID, &event.ScopeID, &event.AggregateType, &event.AggregateID,
		&event.AggregateVersion, &event.EventType, &event.SchemaVersion,
		&occurredAt, &event.CorrelationID, &payload)
	if err != nil {
		return Event{}, err
	}
	if occurredAt.IsZero() || payload == "" {
		return Event{}, errors.New("durable event has invalid projection")
	}
	event.OccurredAt = occurredAt.UTC()
	event.Payload = json.RawMessage(payload)
	return event, nil
}

// Prune executes the owner-controlled bounded retention function. The
// maintenance coordinator supplies tx and owns its commit/rollback boundary.
func (r *Repository) Prune(ctx context.Context, tx Tx, before time.Time) (int64, error) {
	if err := validateTxContext(ctx, tx); err != nil {
		return 0, err
	}
	if before.IsZero() {
		return 0, errors.New("prune cutoff is required")
	}
	var removed int64
	if err := tx.QueryRow(ctx, `SELECT event.prune_event_log($1, $2)`, before.UTC(), int32(1000)).Scan(&removed); err != nil {
		return 0, fmt.Errorf("prune durable events: %w", err)
	}
	return removed, nil
}

func validateTxContext(ctx context.Context, tx Tx) error {
	if tx == nil {
		return errors.New("event PostgreSQL transaction is nil")
	}
	if ctx == nil {
		return errors.New("event context is nil")
	}
	return nil
}

func boundedID(label, value string, max int) (string, error) {
	trimmed := strings.TrimSpace(value)
	if value != trimmed {
		return "", fmt.Errorf("%s must not contain surrounding whitespace", label)
	}
	if value == "" {
		return "", fmt.Errorf("%s is required", label)
	}
	if len(value) > max {
		return "", fmt.Errorf("%s exceeds %d bytes", label, max)
	}
	return value, nil
}

func validateUUID(label, value string) error {
	if len(value) != 36 || value[8] != '-' || value[13] != '-' || value[18] != '-' || value[23] != '-' {
		return fmt.Errorf("%s must be a UUID", label)
	}
	var raw [16]byte
	if _, err := hex.Decode(raw[:], []byte(strings.ReplaceAll(value, "-", ""))); err != nil {
		return fmt.Errorf("%s must be a UUID: %w", label, err)
	}
	return nil
}

// CanonicalCorrelationID projects an opaque request/client correlation into
// the event-log UUID field. Non-UUID values remain available on the audit row,
// while the canonical event envelope represents them as SQL NULL.
func CanonicalCorrelationID(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	parsed, err := uuid.Parse(value)
	if err != nil || parsed.String() != value {
		return ""
	}
	return value
}

func validateUUIDv7(label, value string) error {
	if value == "" || value != strings.TrimSpace(value) || value != strings.ToLower(value) {
		return fmt.Errorf("%s must be a canonical lowercase UUIDv7", label)
	}
	if err := validateUUID(label, value); err != nil {
		return fmt.Errorf("%s must be a canonical lowercase UUIDv7", label)
	}
	var raw [16]byte
	if _, err := hex.Decode(raw[:], []byte(strings.ReplaceAll(value, "-", ""))); err != nil {
		return fmt.Errorf("%s must be a canonical lowercase UUIDv7", label)
	}
	if raw[6]>>4 != 7 || raw[8]&0xc0 != 0x80 {
		return fmt.Errorf("%s must be a canonical lowercase UUIDv7", label)
	}
	return nil
}

func canonicalObject(raw json.RawMessage, maxBytes int64) (json.RawMessage, error) {
	if len(raw) == 0 {
		raw = json.RawMessage(`{}`)
	}
	var validated json.RawMessage
	if err := strictjson.DecodeWithOptions(raw, &validated, strictjson.Options{
		MaxBytes: maxBytes, MaxDepth: 100,
		DuplicateKeys: strictjson.CaseSensitiveKeys, AllowUnknownFields: true,
	}); err != nil {
		return nil, err
	}
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.UseNumber()
	var object map[string]any
	if err := decoder.Decode(&object); err != nil {
		return nil, err
	}
	if object == nil {
		return nil, errors.New("must be a JSON object")
	}
	canonical, err := json.Marshal(object)
	if err != nil {
		return nil, err
	}
	if int64(len(canonical)) > maxBytes {
		return nil, fmt.Errorf("exceeds %d bytes after canonicalization", maxBytes)
	}
	return canonical, nil
}

// uuidv7 creates a sortable UUIDv7 without another runtime dependency.
func uuidv7() (string, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	ms := uint64(time.Now().UnixMilli())
	b[0], b[1], b[2], b[3], b[4], b[5] = byte(ms>>40), byte(ms>>32), byte(ms>>24), byte(ms>>16), byte(ms>>8), byte(ms)
	b[6] = (b[6] & 0x0f) | 0x70
	b[8] = (b[8] & 0x3f) | 0x80
	var out [36]byte
	hex.Encode(out[0:8], b[0:4])
	out[8] = '-'
	hex.Encode(out[9:13], b[4:6])
	out[13] = '-'
	hex.Encode(out[14:18], b[6:8])
	out[18] = '-'
	hex.Encode(out[19:23], b[8:10])
	out[23] = '-'
	hex.Encode(out[24:36], b[10:16])
	return string(out[:]), nil
}
