// Package postgres implements LeapView's canonical transactional PostgreSQL
// event log. Events are appended through a caller-owned transaction; source
// mutations and their event record therefore share one commit/rollback
// boundary. Delivery, transport, and consumer lifecycle state deliberately do
// not belong to this capability.
package postgres

import (
	"bytes"
	"context"
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	eventdb "github.com/flidai/leapview/internal/platform/events/postgres/internal/db"
	"github.com/flidai/leapview/pkg/strictjson"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

// Tx is deliberately the complete native transaction contract. A pool must
// never satisfy caller-owned mutation APIs by structural coincidence.
type Tx = pgx.Tx

// Repository is stateless. Its non-zero marker preserves pointer identity so
// application composition can prove that adapters retain the canonical
// authority supplied by the authority graph.
type Repository struct{ identity byte }

//go:embed schema.sql
var schemaSQL string

// SchemaSQL returns the forward event capability schema. It contains no
// transaction control; callers apply it using their migration transaction.
func SchemaSQL() string { return schemaSQL }

// EventInput describes one domain event. EventID is optional; when omitted a
// UUIDv7 is generated by the repository.
type EventInput struct {
	EventID       string
	ScopeID       string
	AggregateType string
	AggregateID   string
	EventType     string
	SchemaVersion int64
	CorrelationID string
	Payload       json.RawMessage
}

// Event is the immutable event-log record returned after append.
type Event struct {
	EventID          string
	ScopeID          string
	AggregateType    string
	AggregateID      string
	AggregateVersion int64
	EventType        string
	SchemaVersion    int64
	OccurredAt       time.Time
	CorrelationID    string
	Payload          json.RawMessage
}

// EventConflictError reports a retry using an existing event identity with a
// different immutable field.
type EventConflictError struct {
	EventID string
	Field   string
}

func (e *EventConflictError) Error() string {
	return fmt.Sprintf("event %s conflicts on %s", e.EventID, e.Field)
}

// New returns a stateless event repository.
func New() *Repository { return &Repository{identity: 1} }

// AppendEvent validates and appends one event in tx. Explicit identities are
// idempotent: an exact retry returns the original immutable row, while a
// changed field returns EventConflictError. Aggregate versions are allocated
// by a row lock and are contiguous under concurrent writers.
func (r *Repository) AppendEvent(ctx context.Context, tx Tx, in EventInput) (Event, error) {
	if err := validateTxContext(ctx, tx); err != nil {
		return Event{}, err
	}
	payload, err := canonicalObject(in.Payload, 65536)
	if err != nil {
		return Event{}, fmt.Errorf("event payload: %w", err)
	}
	scope, err := boundedID("scope", in.ScopeID, 255)
	if err != nil {
		return Event{}, err
	}
	aggregateType, err := boundedID("aggregate type", in.AggregateType, 255)
	if err != nil {
		return Event{}, err
	}
	aggregateID, err := boundedID("aggregate id", in.AggregateID, 255)
	if err != nil {
		return Event{}, err
	}
	eventType, err := boundedID("event type", in.EventType, 255)
	if err != nil {
		return Event{}, err
	}
	if in.SchemaVersion <= 0 {
		return Event{}, errors.New("event schema version must be positive")
	}
	eventID := in.EventID
	if eventID != strings.TrimSpace(eventID) {
		return Event{}, errors.New("event id must not contain surrounding whitespace")
	}
	if eventID == "" {
		generated, generateErr := uuid.NewV7()
		if generateErr != nil {
			return Event{}, fmt.Errorf("generate event id: %w", generateErr)
		}
		eventID = generated.String()
	}
	if err := validateUUIDv7("event id", eventID); err != nil {
		return Event{}, err
	}
	correlationID := in.CorrelationID
	if correlationID != strings.TrimSpace(correlationID) {
		return Event{}, errors.New("correlation id must not contain surrounding whitespace")
	}
	if correlationID != "" {
		if err := validateUUID("correlation id", correlationID); err != nil {
			return Event{}, err
		}
	}

	// Serialize retries for one explicit identity before the lookup. This is
	// also what prevents a racing retry from consuming an aggregate version.
	if err := eventdb.New(tx).LockEventIdentity(ctx, eventID); err != nil {
		return Event{}, fmt.Errorf("lock event identity: %w", err)
	}
	existing, err := getEvent(ctx, tx, eventID)
	if err == nil {
		if existing.ScopeID != scope {
			return Event{}, &EventConflictError{EventID: eventID, Field: "scope_id"}
		}
		if existing.AggregateType != aggregateType {
			return Event{}, &EventConflictError{EventID: eventID, Field: "aggregate_type"}
		}
		if existing.AggregateID != aggregateID {
			return Event{}, &EventConflictError{EventID: eventID, Field: "aggregate_id"}
		}
		if existing.EventType != eventType {
			return Event{}, &EventConflictError{EventID: eventID, Field: "event_type"}
		}
		if existing.SchemaVersion != in.SchemaVersion {
			return Event{}, &EventConflictError{EventID: eventID, Field: "schema_version"}
		}
		if existing.CorrelationID != correlationID {
			return Event{}, &EventConflictError{EventID: eventID, Field: "correlation_id"}
		}
		payloadMatches, err := eventdb.New(tx).CompareEventPayload(ctx, eventdb.CompareEventPayloadParams{
			EventID: dbUUID(eventID),
			Payload: payload,
		})
		if err != nil {
			return Event{}, fmt.Errorf("compare existing event payload: %w", err)
		}
		if !payloadMatches {
			return Event{}, &EventConflictError{EventID: eventID, Field: "payload"}
		}
		return existing, nil
	}
	if !errors.Is(err, pgx.ErrNoRows) {
		return Event{}, fmt.Errorf("check event identity: %w", err)
	}

	// The explicit aggregate row is locked by UPDATE, so versions are never
	// derived from MAX() and concurrent writers cannot create gaps or clashes.
	if err := eventdb.New(tx).EnsureEventAggregate(ctx, eventdb.EnsureEventAggregateParams{
		ScopeID: scope, AggregateType: aggregateType, AggregateID: aggregateID,
	}); err != nil {
		return Event{}, fmt.Errorf("ensure event aggregate: %w", err)
	}
	version, err := eventdb.New(tx).AllocateAggregateVersion(ctx, eventdb.AllocateAggregateVersionParams{
		ScopeID: scope, AggregateType: aggregateType, AggregateID: aggregateID,
	})
	if err != nil {
		return Event{}, fmt.Errorf("allocate aggregate version: %w", err)
	}
	inserted, err := eventdb.New(tx).InsertEvent(ctx, eventdb.InsertEventParams{
		EventID: dbUUID(eventID), ScopeID: scope, AggregateType: aggregateType,
		AggregateID: aggregateID, AggregateVersion: version, EventType: eventType,
		SchemaVersion: in.SchemaVersion, CorrelationID: dbUUID(correlationID), Payload: payload,
	})
	if err != nil {
		return Event{}, fmt.Errorf("insert durable event: %w", err)
	}
	event := Event{EventID: eventID, ScopeID: scope, AggregateType: aggregateType,
		AggregateID: aggregateID, AggregateVersion: version, EventType: eventType,
		SchemaVersion: in.SchemaVersion, OccurredAt: inserted.OccurredAt.Time.UTC(),
		CorrelationID: correlationID, Payload: json.RawMessage(inserted.Payload)}
	if err := ValidateEventProjection(event); err != nil {
		return Event{}, fmt.Errorf("insert durable event returned invalid projection: %w", err)
	}
	return event, nil
}

// GetEvent reads one durable event by identity.
func (r *Repository) GetEvent(ctx context.Context, tx Tx, eventID string) (Event, error) {
	if err := validateTxContext(ctx, tx); err != nil {
		return Event{}, err
	}
	if err := validateUUIDv7("event id", eventID); err != nil {
		return Event{}, err
	}
	event, err := getEvent(ctx, tx, eventID)
	if err != nil {
		return Event{}, fmt.Errorf("get durable event: %w", err)
	}
	return event, nil
}

func getEvent(ctx context.Context, tx Tx, eventID string) (Event, error) {
	row, err := eventdb.New(tx).GetEventByID(ctx, dbUUID(eventID))
	if err != nil {
		return Event{}, err
	}
	event := Event{EventID: row.EventID, ScopeID: row.ScopeID,
		AggregateType: row.AggregateType, AggregateID: row.AggregateID,
		AggregateVersion: row.AggregateVersion, EventType: row.EventType,
		SchemaVersion: row.SchemaVersion, OccurredAt: row.OccurredAt.Time.UTC(),
		CorrelationID: row.CorrelationID, Payload: json.RawMessage(row.Payload)}
	if err := ValidateEventProjection(event); err != nil {
		return Event{}, fmt.Errorf("durable event has invalid projection: %w", err)
	}
	return event, nil
}

// ValidateEventProjection validates the complete immutable event projection
// returned by the event authority. Keeping this at the platform boundary
// prevents every capability adapter from implementing a subtly different
// post-append/readback check.
func ValidateEventProjection(event Event) error {
	if err := validateUUIDv7("event id", event.EventID); err != nil {
		return err
	}
	for label, value := range map[string]string{
		"scope": event.ScopeID, "aggregate type": event.AggregateType,
		"aggregate id": event.AggregateID, "event type": event.EventType,
	} {
		if _, err := boundedID(label, value, 255); err != nil {
			return err
		}
	}
	if event.AggregateVersion <= 0 {
		return errors.New("aggregate version must be positive")
	}
	if event.SchemaVersion <= 0 {
		return errors.New("event schema version must be positive")
	}
	if event.OccurredAt.IsZero() {
		return errors.New("event occurred-at timestamp is required")
	}
	if event.CorrelationID != "" {
		if event.CorrelationID != strings.TrimSpace(event.CorrelationID) {
			return errors.New("correlation id must not contain surrounding whitespace")
		}
		if err := validateUUID("correlation id", event.CorrelationID); err != nil {
			return err
		}
	}
	if len(event.Payload) == 0 {
		return errors.New("event payload is required")
	}
	if _, err := canonicalObject(event.Payload, 65536); err != nil {
		return fmt.Errorf("event payload: %w", err)
	}
	return nil
}

// Prune executes the owner-controlled bounded retention function. The
// maintenance coordinator supplies tx and owns its commit/rollback boundary.
func (r *Repository) Prune(ctx context.Context, tx Tx, before time.Time) (int64, error) {
	if err := validateTxContext(ctx, tx); err != nil {
		return 0, err
	}
	if before.IsZero() {
		return 0, errors.New("prune cutoff is required")
	}
	removed, err := eventdb.New(tx).PruneEventLog(ctx, eventdb.PruneEventLogParams{
		Before: pgtype.Timestamptz{Time: before.UTC(), Valid: true}, Batch: 1000,
	})
	if err != nil {
		return 0, fmt.Errorf("prune durable events: %w", err)
	}
	return removed, nil
}

func dbUUID(value string) pgtype.UUID {
	if value == "" {
		return pgtype.UUID{}
	}
	parsed, err := uuid.Parse(value)
	if err != nil {
		return pgtype.UUID{}
	}
	return pgtype.UUID{Bytes: parsed, Valid: true}
}

func validateTxContext(ctx context.Context, tx Tx) error {
	// Event append is a trust boundary: require both caller-owned transaction
	// and request context before writing canonical durable evidence.
	if ctx == nil {
		return errors.New("event context is nil")
	}
	if tx == nil {
		return errors.New("event PostgreSQL transaction is nil")
	}
	return nil
}

func boundedID(label, value string, max int) (string, error) {
	trimmed := strings.TrimSpace(value)
	if value != trimmed {
		return "", fmt.Errorf("%s must not contain surrounding whitespace", label)
	}
	if value == "" {
		return "", fmt.Errorf("%s is required", label)
	}
	if len(value) > max {
		return "", fmt.Errorf("%s exceeds %d bytes", label, max)
	}
	return value, nil
}

func validateUUID(label, value string) error {
	if len(value) != 36 || value[8] != '-' || value[13] != '-' || value[18] != '-' || value[23] != '-' {
		return fmt.Errorf("%s must be a UUID", label)
	}
	var raw [16]byte
	if _, err := hex.Decode(raw[:], []byte(strings.ReplaceAll(value, "-", ""))); err != nil {
		return fmt.Errorf("%s must be a UUID: %w", label, err)
	}
	return nil
}

// CanonicalCorrelationID projects an opaque request/client correlation into
// the event-log UUID field. Non-UUID values remain available on the audit row,
// while the canonical event envelope represents them as SQL NULL.
func CanonicalCorrelationID(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	parsed, err := uuid.Parse(value)
	if err != nil || parsed.String() != value {
		return ""
	}
	return value
}

func validateUUIDv7(label, value string) error {
	if value == "" || value != strings.TrimSpace(value) || value != strings.ToLower(value) {
		return fmt.Errorf("%s must be a canonical lowercase UUIDv7", label)
	}
	if err := validateUUID(label, value); err != nil {
		return fmt.Errorf("%s must be a canonical lowercase UUIDv7", label)
	}
	var raw [16]byte
	if _, err := hex.Decode(raw[:], []byte(strings.ReplaceAll(value, "-", ""))); err != nil {
		return fmt.Errorf("%s must be a canonical lowercase UUIDv7", label)
	}
	if raw[6]>>4 != 7 || raw[8]&0xc0 != 0x80 {
		return fmt.Errorf("%s must be a canonical lowercase UUIDv7", label)
	}
	return nil
}

func canonicalObject(raw json.RawMessage, maxBytes int64) (json.RawMessage, error) {
	if len(raw) == 0 {
		raw = json.RawMessage(`{}`)
	}
	var validated json.RawMessage
	if err := strictjson.DecodeWithOptions(raw, &validated, strictjson.Options{
		MaxBytes: maxBytes, MaxDepth: 100,
		DuplicateKeys: strictjson.CaseSensitiveKeys, AllowUnknownFields: true,
	}); err != nil {
		return nil, err
	}
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.UseNumber()
	var object map[string]any
	if err := decoder.Decode(&object); err != nil {
		return nil, err
	}
	if object == nil {
		return nil, errors.New("must be a JSON object")
	}
	canonical, err := json.Marshal(object)
	if err != nil {
		return nil, err
	}
	if int64(len(canonical)) > maxBytes {
		return nil, fmt.Errorf("exceeds %d bytes after canonicalization", maxBytes)
	}
	return canonical, nil
}
