// Package schemas exposes the generated public JSON Schema artifacts to Go
// code that validates authored resources. The files under schemas/json are
// the single source of truth; this package only embeds those generated bytes.
package schemas

import _ "embed"

//go:embed json/dashboard-document.schema.json
var DashboardDocumentSchema []byte

//go:embed json/pipeline.schema.json
var PipelineSchema []byte
