// Command permissiondocgen renders the canonical typed permission catalog into
// the public Markdown reference.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/flidai/leapview/internal/access"
	projectgraph "github.com/flidai/leapview/internal/project/graph"
)

const generatedMarker = "<!-- Code generated by internal/app/tools/permissiondocgen; DO NOT EDIT. -->"

func main() {
	out := flag.String("out", "docs/articles/reference/permissions.md", "generated permission reference path")
	check := flag.Bool("check", false, "verify generated output is current")
	flag.Parse()

	var err error
	if *check {
		err = checkGenerated(*out)
	} else {
		err = generate(*out)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(out string) error {
	contents := []byte(renderPermissions(access.PermissionCatalog(), access.PermissionRolePresets()))
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return fmt.Errorf("create permission documentation directory: %w", err)
	}
	if err := os.WriteFile(out, contents, 0o644); err != nil {
		return fmt.Errorf("write permission documentation: %w", err)
	}
	return nil
}

func checkGenerated(out string) error {
	current, err := os.ReadFile(out)
	if err != nil {
		return fmt.Errorf("read generated permission documentation: %w", err)
	}
	expected := []byte(renderPermissions(access.PermissionCatalog(), access.PermissionRolePresets()))
	if !bytes.Equal(current, expected) {
		return fmt.Errorf("%s is out of date; run task permission-docs:generate", out)
	}
	return nil
}

func renderPermissions(catalog []access.PermissionDefinition, presets []access.PermissionRolePreset) string {
	var out strings.Builder
	out.WriteString(generatedMarker + "\n\n")
	out.WriteString("# Typed permission catalog\n\n")
	out.WriteString("This reference is generated from LeapView's canonical Go permission catalog. It describes the typed action identities, target scopes, prerequisites, delegation flags, and versioned role expansions used by the resource-authorization contract.\n\n")
	out.WriteString("Catalog profile: `" + access.PermissionCatalogProfile + "`. Persisted credentials and assignments must retain this profile when they adopt typed permission pairs.\n\n")
	out.WriteString("Catalog presence defines stable vocabulary, not blanket runtime availability. `UI selectable` means a picker may offer the action only when its current authority provider supplies a matching target pair; unsupported or unqualified operations remain unavailable.\n\n")
	out.WriteString("## Actions\n\n")
	out.WriteString("| Action | Family | Scope | Resource kinds | Check kinds | Prerequisites | Delegable | UI selectable | Description |\n")
	out.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
	for _, definition := range catalog {
		fmt.Fprintf(&out, "| `%s` | %s | `%s` | %s | %s | %s | %s | %s | %s |\n",
			definition.Action,
			escapeTable(definition.Family),
			definition.Scope,
			formatKinds(definition.ResourceKinds),
			formatKinds(definition.CheckKinds),
			formatActions(definition.Prerequisites),
			formatBool(definition.Delegable),
			formatBool(definition.UISelectable),
			escapeTable(definition.Description),
		)
	}

	out.WriteString("\n## Versioned role expansions\n\n")
	out.WriteString("Role names are presentation presets over explicit typed actions. They do not bypass target, credential, prerequisite, or policy checks.\n\n")
	out.WriteString("| Role | Profile | Actions | Description |\n")
	out.WriteString("| --- | --- | --- | --- |\n")
	for _, preset := range presets {
		fmt.Fprintf(&out, "| `%s` | `%s` | %s | %s |\n",
			escapeTable(string(preset.Role)),
			escapeTable(preset.Profile),
			formatActions(preset.Actions),
			escapeTable(preset.Description),
		)
	}
	return out.String()
}

func formatKinds(kinds []projectgraph.Kind) string {
	if len(kinds) == 0 {
		return "—"
	}
	values := make([]string, 0, len(kinds))
	for _, kind := range kinds {
		values = append(values, "`"+string(kind)+"`")
	}
	return strings.Join(values, ", ")
}

func formatActions(actions []access.Action) string {
	if len(actions) == 0 {
		return "—"
	}
	values := make([]string, 0, len(actions))
	for _, action := range actions {
		values = append(values, "`"+string(action)+"`")
	}
	return strings.Join(values, ", ")
}

func formatBool(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

func escapeTable(value string) string {
	return strings.NewReplacer("|", "\\|", "\r", " ", "\n", " ").Replace(value)
}
