// Code generated by apigen data-contract Go emitter. DO NOT EDIT.
package contracts

type DashboardEnvelope struct {
	Page    DashboardPageSignal        `json:"page"`
	Filters DashboardFilters           `json:"filters"`
	Visuals map[string]DashboardVisual `json:"visuals"`
	Tables  map[string]DashboardTable  `json:"tables"`
}

type DashboardFilterControl struct {
	Type   string    `json:"type"`
	Value  *string   `json:"value,omitempty"`
	Values *[]string `json:"values,omitempty"`
}

type DashboardFilters struct {
	Controls map[string]DashboardFilterControl `json:"controls"`
}

type DashboardPageSignal struct {
	DashboardId string `json:"dashboardId"`
	PageId      string `json:"pageId"`
	Title       string `json:"title"`
}

type DashboardTable struct {
	Id      string           `json:"id"`
	Columns []string         `json:"columns"`
	Rows    []map[string]any `json:"rows"`
}

type DashboardVisual struct {
	Id    string         `json:"id"`
	Kind  string         `json:"kind"`
	Title string         `json:"title"`
	Data  map[string]any `json:"data"`
}
