// Command permissioncontractgen renders the reviewed access catalog into the
// transport and persistence contracts that must agree with it exactly.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/flidai/leapview/internal/access"
	projectgraph "github.com/flidai/leapview/internal/project/graph"
)

const generatedMarker = "// Code generated by internal/app/tools/permissioncontractgen; DO NOT EDIT."

type outputPaths struct {
	typeSpec string
	json     string
	sql      string
}

type contract struct {
	Profile string           `json:"profile"`
	Actions []actionContract `json:"actions"`
	Roles   []roleContract   `json:"roles"`
}

type actionContract struct {
	Action        string   `json:"action"`
	Family        string   `json:"family"`
	Description   string   `json:"description"`
	Scope         string   `json:"scope"`
	ResourceKinds []string `json:"resourceKinds"`
	CheckKinds    []string `json:"checkKinds"`
	Prerequisites []string `json:"prerequisites"`
	Delegable     bool     `json:"delegable"`
	UISelectable  bool     `json:"uiSelectable"`
}

type roleContract struct {
	Role        string   `json:"role"`
	Profile     string   `json:"profile"`
	Description string   `json:"description"`
	Actions     []string `json:"actions"`
}

func main() {
	root := flag.String("root", ".", "repository root")
	check := flag.Bool("check", false, "verify generated contracts are current")
	flag.Parse()

	paths := defaultOutputPaths(*root)
	var err error
	if *check {
		err = checkGenerated(paths)
	} else {
		err = generate(paths)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func defaultOutputPaths(root string) outputPaths {
	return outputPaths{
		typeSpec: filepath.Join(root, "api", "typespec", "generated", "permissions.tsp"),
		json:     filepath.Join(root, "internal", "access", "generated", "permission_catalog.json"),
		sql:      filepath.Join(root, "internal", "access", "postgres", "permission_contract.sql"),
	}
}

func generate(paths outputPaths) error {
	value, err := loadContract()
	if err != nil {
		return err
	}
	files := map[string][]byte{
		paths.typeSpec: []byte(renderTypeSpec(value)),
		paths.json:     renderJSON(value),
		paths.sql:      []byte(renderSQL(value)),
	}
	for path, contents := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create generated contract directory for %s: %w", path, err)
		}
		if err := os.WriteFile(path, contents, 0o644); err != nil {
			return fmt.Errorf("write generated permission contract %s: %w", path, err)
		}
	}
	return nil
}

func checkGenerated(paths outputPaths) error {
	value, err := loadContract()
	if err != nil {
		return err
	}
	expected := map[string][]byte{
		paths.typeSpec: []byte(renderTypeSpec(value)),
		paths.json:     renderJSON(value),
		paths.sql:      []byte(renderSQL(value)),
	}
	for path, want := range expected {
		got, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read generated permission contract %s: %w", path, err)
		}
		if !bytes.Equal(got, want) {
			return fmt.Errorf("%s is out of date; run task permission-contracts:generate", path)
		}
	}
	return nil
}

func loadContract() (contract, error) {
	definitions := access.PermissionCatalog()
	if err := access.ValidatePermissionCatalog(definitions); err != nil {
		return contract{}, fmt.Errorf("validate canonical permission catalog: %w", err)
	}
	presets := access.PermissionRolePresets()
	if err := access.ValidatePermissionRolePresets(presets, definitions); err != nil {
		return contract{}, fmt.Errorf("validate canonical permission role presets: %w", err)
	}
	value := contract{Profile: access.PermissionCatalogProfile}
	value.Actions = make([]actionContract, 0, len(definitions))
	for _, definition := range definitions {
		value.Actions = append(value.Actions, actionContract{
			Action:        string(definition.Action),
			Family:        definition.Family,
			Description:   definition.Description,
			Scope:         string(definition.Scope),
			ResourceKinds: stringKinds(definition.ResourceKinds),
			CheckKinds:    stringKinds(definition.CheckKinds),
			Prerequisites: stringActions(definition.Prerequisites),
			Delegable:     definition.Delegable,
			UISelectable:  definition.UISelectable,
		})
	}
	value.Roles = make([]roleContract, 0, len(presets))
	for _, preset := range presets {
		value.Roles = append(value.Roles, roleContract{
			Role:        string(preset.Role),
			Profile:     preset.Profile,
			Description: preset.Description,
			Actions:     stringActions(preset.Actions),
		})
	}
	return value, nil
}

func stringKinds(values []projectgraph.Kind) []string {
	result := make([]string, len(values))
	for index, value := range values {
		result[index] = string(value)
	}
	return result
}

func stringActions(values []access.Action) []string {
	result := make([]string, len(values))
	for index, value := range values {
		result[index] = string(value)
	}
	return result
}

func renderJSON(value contract) []byte {
	encoded, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		panic(fmt.Sprintf("marshal permission contract: %v", err))
	}
	return append(encoded, '\n')
}

func renderTypeSpec(value contract) string {
	var out strings.Builder
	out.WriteString(generatedMarker + "\n\n")
	out.WriteString("// The Go catalog in internal/access is authoritative for these product values.\n")
	out.WriteString("namespace LeapViewAPI.Protocol;\n\n")
	out.WriteString("@pattern(\"^[A-Za-z0-9][A-Za-z0-9_.:-]*$\")\n")
	out.WriteString("scalar PermissionResourceId extends string;\n\n")

	out.WriteString("enum ResourceKind {\n")
	for _, kind := range permissionKinds(value) {
		fmt.Fprintf(&out, "  %s: \"%s\";\n", typeSpecKindMember(kind), kind)
	}
	out.WriteString("}\n\n")

	out.WriteString("enum PermissionAction {\n")
	for _, action := range value.Actions {
		fmt.Fprintf(&out, "  %s: \"%s\";\n", typeSpecActionMember(action.Action), action.Action)
	}
	out.WriteString("}\n\n")

	out.WriteString("enum PermissionCatalogProfile {\n")
	fmt.Fprintf(&out, "  %s: \"%s\";\n", typeSpecProfileMember(value.Profile), value.Profile)
	out.WriteString("}\n\n")

	out.WriteString("enum PermissionScope {\n")
	for _, scope := range []string{"instance", "project", "resource"} {
		fmt.Fprintf(&out, "  %s;\n", scope)
	}
	out.WriteString("}\n\n")

	out.WriteString("@example(#{\n")
	out.WriteString("  scope: PermissionScope.resource,\n")
	out.WriteString("  projectId: \"project:analytics\",\n")
	out.WriteString("  resourceKind: ResourceKind.dashboardKind,\n")
	out.WriteString("  resourceId: \"dashboard:sales\",\n")
	out.WriteString("})\n")
	out.WriteString("model PermissionTarget {\n")
	out.WriteString("  scope: PermissionScope;\n")
	out.WriteString("  instanceId?: string;\n")
	out.WriteString("  projectId?: PermissionResourceId;\n")
	out.WriteString("  resourceKind?: ResourceKind;\n")
	out.WriteString("  resourceId?: PermissionResourceId;\n")
	out.WriteString("  includeFuture?: boolean;\n")
	out.WriteString("}\n\n")
	out.WriteString("model PermissionPair {\n")
	out.WriteString("  action: PermissionAction;\n")
	out.WriteString("  target: PermissionTarget;\n")
	out.WriteString("  profile: PermissionCatalogProfile;\n")
	out.WriteString("}\n")
	return out.String()
}

func permissionKinds(value contract) []string {
	seen := make(map[string]struct{})
	for _, action := range value.Actions {
		for _, kind := range append(append([]string(nil), action.ResourceKinds...), action.CheckKinds...) {
			seen[kind] = struct{}{}
		}
	}
	preferred := []string{"project", "connection", "source", "model", "semantic_model", "pipeline", "dashboard"}
	result := make([]string, 0, len(seen))
	for _, kind := range preferred {
		if _, ok := seen[kind]; ok {
			result = append(result, kind)
			delete(seen, kind)
		}
	}
	extra := make([]string, 0, len(seen))
	for kind := range seen {
		extra = append(extra, kind)
	}
	sort.Strings(extra)
	return append(result, extra...)
}

func typeSpecActionMember(action string) string {
	return typeSpecCamelMember(action, false)
}

func typeSpecKindMember(kind string) string {
	switch kind {
	case "project", "connection":
		return kind
	case "source", "model", "pipeline", "dashboard":
		return kind + "Kind"
	case "semantic_model":
		return "semanticModel"
	default:
		return typeSpecCamelMember(kind, true)
	}
}

func typeSpecProfileMember(profile string) string {
	if profile == "leapview.permissions/v1" {
		return "v1"
	}
	return typeSpecCamelMember(profile, true)
}

func typeSpecCamelMember(value string, upperFirst bool) string {
	var out strings.Builder
	upper := upperFirst
	for _, char := range value {
		if char == '.' || char == '_' || char == '-' || char == ':' || char == '/' {
			upper = true
			continue
		}
		if upper {
			if char >= 'a' && char <= 'z' {
				char -= 'a' - 'A'
			}
			upper = false
		}
		out.WriteRune(char)
	}
	return out.String()
}

func renderSQL(value contract) string {
	var out strings.Builder
	out.WriteString("-- Code generated by internal/app/tools/permissioncontractgen; DO NOT EDIT.\n")
	out.WriteString("-- The function is generated from internal/access.PermissionCatalog.\n")
	out.WriteString("-- A forward PostgreSQL migration can install this contract without\n")
	out.WriteString("-- changing the immutable Goose baseline.\n\n")
	out.WriteString("CREATE OR REPLACE FUNCTION access.valid_permission_pairs(profile text, value jsonb)\n")
	out.WriteString("RETURNS boolean LANGUAGE plpgsql IMMUTABLE AS $$\n")
	out.WriteString("DECLARE\n")
	for _, declaration := range []string{
		"    item jsonb;",
		"    target jsonb;",
		"    action_name text;",
		"    target_scope text;",
		"    expected_scope text;",
		"    resource_kind text;",
		"    include_future boolean;",
		"    allowed_resource_kinds text[];",
		"    seen_items jsonb := '[]'::jsonb;",
	} {
		out.WriteString(declaration + "\n")
	}
	out.WriteString("BEGIN\n")
	out.WriteString("    IF profile IS NULL OR value IS NULL THEN\n")
	out.WriteString("        RETURN profile IS NULL AND value IS NULL;\n")
	out.WriteString("    END IF;\n")
	fmt.Fprintf(&out, "    IF profile <> %s OR jsonb_typeof(value) <> 'array' THEN RETURN FALSE; END IF;\n", sqlString(value.Profile))
	out.WriteString("    IF jsonb_array_length(value) > 256 OR octet_length(value::text) > 65536 THEN RETURN FALSE; END IF;\n")
	out.WriteString("    FOR item IN SELECT jsonb_array_elements(value) LOOP\n")
	out.WriteString("        IF jsonb_typeof(item) <> 'object'\n")
	out.WriteString("           OR (SELECT count(*) FROM jsonb_object_keys(item)) <> 3\n")
	out.WriteString("           OR EXISTS (SELECT 1 FROM jsonb_object_keys(item) AS key WHERE key NOT IN ('action', 'target', 'profile'))\n")
	out.WriteString("           OR jsonb_typeof(item->'action') <> 'string'\n")
	out.WriteString("           OR jsonb_typeof(item->'profile') <> 'string'\n")
	out.WriteString("           OR jsonb_typeof(item->'target') <> 'object'\n")
	out.WriteString("           OR item->>'profile' <> profile THEN\n")
	out.WriteString("            RETURN FALSE;\n")
	out.WriteString("        END IF;\n")
	out.WriteString("        IF EXISTS (SELECT 1 FROM jsonb_array_elements(seen_items) AS seen(seen_item) WHERE seen.seen_item = item) THEN\n")
	out.WriteString("            RETURN FALSE;\n")
	out.WriteString("        END IF;\n")
	out.WriteString("        seen_items := seen_items || jsonb_build_array(item);\n")
	out.WriteString("        target := item->'target';\n")
	out.WriteString("        IF (SELECT count(*) FROM jsonb_object_keys(target)) < 1\n")
	out.WriteString("           OR EXISTS (SELECT 1 FROM jsonb_object_keys(target) AS key WHERE key NOT IN ('scope', 'instanceId', 'projectId', 'resourceKind', 'resourceId', 'includeFuture'))\n")
	out.WriteString("           OR NOT (target ? 'scope') OR jsonb_typeof(target->'scope') <> 'string' THEN\n")
	out.WriteString("            RETURN FALSE;\n")
	out.WriteString("        END IF;\n")
	out.WriteString("        IF (target ? 'instanceId' AND jsonb_typeof(target->'instanceId') <> 'string')\n")
	out.WriteString("           OR (target ? 'projectId' AND jsonb_typeof(target->'projectId') <> 'string')\n")
	out.WriteString("           OR (target ? 'resourceKind' AND jsonb_typeof(target->'resourceKind') <> 'string')\n")
	out.WriteString("           OR (target ? 'resourceId' AND jsonb_typeof(target->'resourceId') <> 'string')\n")
	out.WriteString("           OR (target ? 'includeFuture' AND jsonb_typeof(target->'includeFuture') <> 'boolean') THEN\n")
	out.WriteString("            RETURN FALSE;\n")
	out.WriteString("        END IF;\n")
	out.WriteString("        action_name := item->>'action';\n")
	out.WriteString("        target_scope := target->>'scope';\n")
	out.WriteString("        expected_scope := NULL;\n")
	out.WriteString("        allowed_resource_kinds := ARRAY[]::text[];\n")
	for index, action := range value.Actions {
		keyword := "IF"
		if index > 0 {
			keyword = "ELSIF"
		}
		fmt.Fprintf(&out, "        %s action_name = %s THEN\n", keyword, sqlString(action.Action))
		fmt.Fprintf(&out, "            expected_scope := %s;\n", sqlString(action.Scope))
		if len(action.ResourceKinds) == 0 {
			out.WriteString("            allowed_resource_kinds := ARRAY[]::text[];\n")
		} else {
			out.WriteString("            allowed_resource_kinds := ARRAY[")
			for kindIndex, kind := range action.ResourceKinds {
				if kindIndex > 0 {
					out.WriteString(", ")
				}
				out.WriteString(sqlString(kind))
			}
			out.WriteString("]::text[];\n")
		}
	}
	out.WriteString("        ELSE\n")
	out.WriteString("            RETURN FALSE;\n")
	out.WriteString("        END IF;\n")
	out.WriteString("        IF target_scope = 'instance' THEN\n")
	out.WriteString("            IF expected_scope <> 'instance' OR NOT (target ? 'instanceId')\n")
	out.WriteString("               OR target->>'instanceId' = '' OR target->>'instanceId' <> btrim(target->>'instanceId')\n")
	out.WriteString("               OR octet_length(target->>'instanceId') > 255\n")
	out.WriteString("               OR position(chr(9) in target->>'instanceId') > 0\n")
	out.WriteString("               OR position(chr(10) in target->>'instanceId') > 0\n")
	out.WriteString("               OR position(chr(13) in target->>'instanceId') > 0\n")
	out.WriteString("               OR target ? 'projectId' OR target ? 'resourceKind' OR target ? 'resourceId'\n")
	out.WriteString("               OR COALESCE((target->>'includeFuture')::boolean, FALSE) THEN RETURN FALSE; END IF;\n")
	out.WriteString("        ELSIF target_scope = 'project' THEN\n")
	out.WriteString("            IF expected_scope = 'instance' OR NOT (target ? 'projectId')\n")
	out.WriteString("               OR target->>'projectId' !~ '^[A-Za-z0-9][A-Za-z0-9_.:-]*$'\n")
	out.WriteString("               OR target ? 'instanceId' OR target ? 'resourceId' THEN RETURN FALSE; END IF;\n")
	out.WriteString("            include_future := COALESCE((target->>'includeFuture')::boolean, FALSE);\n")
	out.WriteString("            IF include_future THEN\n")
	out.WriteString("                IF expected_scope <> 'resource' OR NOT (target ? 'resourceKind') THEN RETURN FALSE; END IF;\n")
	out.WriteString("                resource_kind := target->>'resourceKind';\n")
	// The array comparison is generated from each definition's ResourceKinds.
	out.WriteString("                IF NOT (resource_kind = ANY(allowed_resource_kinds)) THEN RETURN FALSE; END IF;\n")
	out.WriteString("            ELSE\n")
	out.WriteString("                IF expected_scope <> 'project' OR target ? 'resourceKind' THEN RETURN FALSE; END IF;\n")
	out.WriteString("            END IF;\n")
	out.WriteString("        ELSIF target_scope = 'resource' THEN\n")
	out.WriteString("            IF expected_scope <> 'resource' OR NOT (target ? 'projectId')\n")
	out.WriteString("               OR target->>'projectId' !~ '^[A-Za-z0-9][A-Za-z0-9_.:-]*$'\n")
	out.WriteString("               OR NOT (target ? 'resourceKind') OR NOT (target ? 'resourceId')\n")
	out.WriteString("               OR target->>'resourceKind' <> btrim(target->>'resourceKind')\n")
	out.WriteString("               OR NOT (target->>'resourceKind' = ANY(allowed_resource_kinds))\n")
	out.WriteString("               OR target->>'resourceId' !~ '^[A-Za-z0-9][A-Za-z0-9_.:-]*$'\n")
	out.WriteString("               OR target ? 'instanceId'\n")
	out.WriteString("               OR COALESCE((target->>'includeFuture')::boolean, FALSE) THEN RETURN FALSE; END IF;\n")
	out.WriteString("        ELSE\n")
	out.WriteString("            RETURN FALSE;\n")
	out.WriteString("        END IF;\n")
	out.WriteString("    END LOOP;\n")
	out.WriteString("    RETURN TRUE;\n")
	out.WriteString("EXCEPTION WHEN invalid_text_representation THEN\n")
	out.WriteString("    RETURN FALSE;\n")
	out.WriteString("END $$;\n")
	return out.String()
}

func sqlString(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}
